"""BPHS bhāva-phala rules — GENERATED, do not hand-edit.

Source: Bṛhat Parāśara Horā Śāstra, Vol I (R. Santhanam translation).
  · LORD_IN_HOUSE — ch.24 "Effects of the Bhāva Lords", vv.1-144 (one verse per
    (lord_house, placed_house) pair). `effect` is the śloka verbatim; a
    `lagna_exception` is tagged `exception_source` "sloka" or "notes"; `notes_caveat`
    is Santhanam's COMMENTARY, never Parāśara — kept separate, never merged.
  · HOUSE_SIGNIFICATIONS — ch.11 "Judgement of Houses", vv.2-13.
  · HOUSE_KARAKA — ch.32 "Planetary Karakatwas", vv.31-34.
  · COMBINATION_RULE — ch.24 vv.145-148: the ONLY BPHS-licensed way to combine
    lord-in-house results (a planet owning two bhāvas → both lordships; contrary →
    nullify; full/half/quarter by strength). Anything beyond it is uncited.

Extracted and 100%-verified against the scan (all 144 present, mapping exact,
4 verses spot-matched to the printed ślokas incl. the Sanskrit). BPHS gives NO
systematic seven-graha-in-bhāva table in Vol I — planet-in-house is a sourced
refusal, handled in bhava_phala.py, not here.
"""

# (lord_house, placed_house) -> {verse, effect, lagna_exception, exception_source, notes_caveat}
LORD_IN_HOUSE = {
    (1, 1): {"verse": 1, "effect": "Should the ascendant lord be in the ascendant itself, the native will be endowed with physical happiness (i.e. good health) and prowess. He will be intelligent, fickle-minded, will have two wives and will unite with other females.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The position of the ascendant lord in the ascendant itself will make the native fearless and longlived."},
    (1, 2): {"verse": 2, "effect": "If the lord of the ascendant is in the 2nd, he will be gainful, scholarly, happy, endowed with good qualities, be religious, honourable and will have many wives.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The native having the ascendant lord in the 2nd house will face obstacles in obtaining progeny and thus he will be left with a longing for issues. He will further become wealthy through his own efforts."},
    (1, 3): {"verse": 3, "effect": "If the lord of the ascendant is in the 3rd, the native will equal a lion in valour, be endowed with all kinds of wealth, be honourable, will have two wives, be intelligent and happy.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Should the 3rd house contain the ascendant lord, one will be equal to a king, respected by others and will indulge in unnatural methods of sexual gratification."},
    (1, 4): {"verse": 4, "effect": "If the ascendant lord is in the 4th, the native will be endowed with paternal and maternal happiness, will have many brothers, be lustful virtuous and charming.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: With the ascendant lord in the 4th house, the native is of a noble descent. He will prosper by his own efforts. He will be ambitious and beautiful. Prosperity will come to him easily. He will ever enjoy physical felicity."},
    (1, 5): {"verse": 5, "effect": "If the ascendant lord is in the 5th, the native will have mediocre progenic happiness, will lose his first child, be honourable, given to anger and be dear to king.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (1, 6): {"verse": 6, "effect": "If the ascendant lord is in the 6th and related to a malefic the native will be devoid of physical happiness, and will be troubled by enemies if there is no benefic aspect.",
        "lagna_exception": "For Scorpio and Taurus ascendant, it will be a felicitous augury for freedom from diseases.", "exception_source": "notes",
        "notes_caveat": "Notes: The ascendant lord going to the 6th house will mar the prospects of health. However, for Scorpio and Taurus ascendant, it will be a felicitous augury for freedom from diseases. The 6th house position of Lagna Lord in general will give abundant wealth and respect apart from royal status. There is, however, a possibility of more than one marriage or losing the spouse early."},
    (1, 7): {"verse": 7, "effect": "If the ascendant lord is a malefic and be in the 7th, the native's wife will not live (long). If the planet in question be a benefic, one will wander aimlessly, face penury and be dejected. He will alternatively become a king (if the said planet is strong).",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (1, 8): {"verse": 8, "effect": "If the ascendant lord is in the 8th, the native will be an accomplished scholar, be sickly, thievish, be given to much anger, be a gambler and will join others' wives.",
        "lagna_exception": "In case of Aries and Libra ascendant, this approach for evil results should be avoided and results declared after further scanning the radix.", "exception_source": "notes",
        "notes_caveat": "Notes: The only good effect of the ascendant lord being in the 8th house is one's academic accomplishment. This position will cause Balarishta or child mortality. The native's health will be poor. He will be a repository of misfortunes. He will see many deaths in the family to his grief. His married life will be a hell. He will be a profligate and will incur ill-fame and disrepute. Penury will ever be after him."},
    (1, 9): {"verse": 9, "effect": "If the ascendant lord is in the 9th, the native will be fortunate, dear to people, be a devotee of Sri Vishnu, be skilful, eloquent in speech and be endowed with wife, sons and wealth.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: One will gain abundantly from his father. Every undertaking of his will be fruitful. He will be well-disposed to his co-born. These are additional results of the ascendant lord occupying the 9th house."},
    (1, 10): {"verse": 10, "effect": "If the ascendant lord is in the 10th, the native will be endowed with paternal happiness, royal honour (or patronage), fame among men and will doubtlessly have self-earned wealth.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The 10th house occupied by the ascendant lord denotes obtainment of co-born. The native will possess ambitions and will prosper in his pursuits."},
    (1, 11): {"verse": 11, "effect": "If the ascendant lord is in the 11th, the native will always be endowed with gains, good qualities, fame and many wives.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (1, 12): {"verse": 12, "effect": "If the ascendant lord is in the 12th and be devoid of benefic aspect/conjunction, the native will be bereft of physical happiness, will spend unfruitfully and be given to much anger.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: If the ascendant lord is in the 12th, the native's life will not be prosperous. He will be addicted to gambling, thieving, debauchery and other vices. He will expend wastefully."},
    (2, 1): {"verse": 13, "effect": "If the 2nd lord is in the ascendant, the native will be endowed with sons and wealth, will be inimical to his family, lustful, hard-hearted and will do others' jobs.",
        "lagna_exception": "These evil effects will not wholly apply to Capricorn ascendant, but with some modifications.", "exception_source": "notes",
        "notes_caveat": "One will be fraudulent and will face financial upheavals with the lord of the 2nd occupying the ascendant."},
    (2, 2): {"verse": 14, "effect": "If the 2nd lord is in the 2nd, the native will be wealthy, proud, will have two or more wives and be bereft of progeny.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (2, 3): {"verse": 15, "effect": "If the 2nd lord is in the 3rd, the native will be valorous, wise, virtuous, lustful and miserly—all these when related to a benefic. If related to a malefic, the native will be a heterodox.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Should the 2nd lord be in the 3rd house, the native will be ill-related to females and will earn through prostitutes. If a malefic is related to the 2nd lord in the 3rd, the person concerned will not be God-fearing and will have dirty conduct."},
    (2, 4): {"verse": 16, "effect": "If the 2nd lord is in the 4th, the native will acquire all kinds of wealth. If the 2nd lord be exalted and be conjunct Jupiter, one will be equal to a king.",
        "lagna_exception": "The exaltation of the 2nd lord in the 4th applies only to Libra ascendant.", "exception_source": "notes",
        "notes_caveat": "The placement of the 2nd lord in the 4th will also produce a heterodox and one of questionable character. Obviously the sage suggests that the exaltation of Mars in the company of Jupiter (in debilitation) in the 4th house will prove extremely favourable for a Libra native conferring near-regalhood. It is also not unmeaningful to conclude that the 2nd lord exalted and joining Jupiter becoming a good omen for any ascendant."},
    (2, 5): {"verse": 17, "effect": "If the 2nd lord is in the 5th the native will be wealthy. Not only the native, but also his sons, will be intent on earning wealth.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The 2nd lord going to the 5th house will make one resort to trickery. His family life will not be happy. He will not be kind to others. He will be very lustful and will be prone to lose a child prematurely."},
    (2, 6): {"verse": 18, "effect": "If the 2nd lord is in the 6th along with a benefic the native will gain wealth through his enemies; if be with a malefic, there will be loss through enemies apart from mutilation of shanks.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "There will be severe loss of wealth through thefts and servants. He will have defects of privities. These are further effects of the 2nd lord occupying the 6th house."},
    (2, 7): {"verse": 19, "effect": "If the 2nd lord is in the 7th, the native will be addicted to others' wives and be a doctor. If a malefic is related to the said placement by conjunction or by aspect, the native's wife will (also) be of questionable character.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The 2nd lord in the 7th house and related to a dire malefic will render the mother of the native being of questionable character according to some hoary authors. However, the 4th house and its lord deserve a special attention in the context of mother's disposition."},
    (2, 8): {"verse": 20, "effect": "If the 2nd lord is in the 8th, the native will be endowed with abundant land and wealth. But he will have limited marital felicity and be bereft of happiness from his elder brother.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (2, 9): {"verse": 21, "effect": "If the 2nd lord is in the 9th, the native will be wealthy, diligent, skilful, sick during childhood and will later on be happy (i. e. healthy) and will visit shrines, observing religious code etc.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (2, 10): {"verse": 22, "effect": "If the 2nd lord is in the 10th, the native will be libidinous, honourable, learned, will have many wives and much wealth and will be bereft of filial happiness.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (2, 11): {"verse": 23, "effect": "If the 2nd lord is in the 11th, the native will have all kinds of wealth, be ever diligent, honourable and famous.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The native will undergo miseries due to ill-health during childhood and with the march of time he will be endowed with health throughout, if the 2nd lord is in the 11th house."},
    (2, 12): {"verse": 24, "effect": "If the 2nd lord is in the 12th, the native will be adventurous, will be devoid of wealth, and be interested in other's wealth while his eldest child will not keep him happy.",
        "lagna_exception": "The 2nd lord lonely in the 12th is bad for riches, except in the case of Aries ascendant with Venus in the 12th in high dignity.", "exception_source": "notes",
        "notes_caveat": "Per the cited saying: if the 2nd lord is in the 12th house with two or more (favourable) planets, the native will be extremely wealthy. This is found to be a sound clue in actual cases."},
    (3, 1): {"verse": 25, "effect": "If the 3rd lord is in the ascendant, the native will have self-made wealth, be disposed to worship, be valorous and be intelligent although devoid of learning.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: One will have a lean body with the ascendant having the 3rd lord in it. He will have such sexual lust that cannot be subdued. He will be short-tempered and ill-disposed to others."},
    (3, 2): {"verse": 26, "effect": "If the 3rd lord is in the 2nd, the native will be corpulent, devoid of valour, will not make much efforts, be not happy and will have an eye on others' wives and others' wealth.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Should the 3rd lord be in the 2nd house, one will resort to unnatural sexual means of gratification. He will not show enthusiasm in his undertakings."},
    (3, 3): {"verse": 27, "effect": "If the 3rd lord is in the 3rd, the native will be endowed with happiness through co-born and will have wealth and sons, be cheerful and extremely happy.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (3, 4): {"verse": 28, "effect": "If the 3rd lord is in the 4th, the native will be happy, wealthy and intelligent but will acquire a wicked spouse.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (3, 5): {"verse": 29, "effect": "If the 3rd lord is in the 5th, the native will have sons, and be virtuous. If in the process the 3rd lord be conjunct or aspected by a malefic, the native will have a formidable wife.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (3, 6): {"verse": 30, "effect": "If the 3rd lord is in the 6th, the native will be inimical to his co-born, be affluent, will not be well-disposed to his maternal uncle and be dear to his maternal aunt.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The student's attention is drawn to the statement of the text, viz. [Sanskrit phrase], which has been without any misconception, rendered to denote the native's being 'dear to his maternal aunt'. At the same time, Sanketa Nidhi while commenting on the 3rd lord's placement in the 6th house gives an overt clue to the native being fond of physical mutiny with his maternal aunt. One wonders whether sage Parasara covertly points out to one and the same thing. Possibly so, for the Sanskrit expression is so flexible."},
    (3, 7): {"verse": 31, "effect": "If the 3rd lord is in the 7th, the native will be interested in serving the king and be not happy during boyhood but at the end of his life.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: It is not a favourable indication to have an independent profession or business when the 3rd lord is in the 7th house. The 7th denotes one's public relationship, business prospects etc. and an evil lord is not welcome there. As a result, the native will be destined to be in the employ of others. Further, this position will give a tendency to steal. The native will incur a legal award like death."},
    (3, 8): {"verse": 32, "effect": "If the 3rd lord is in the 8th, the native will be a thief, will derive his livelihood serving others and will die at the gate of royal palace.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (3, 9): {"verse": 33, "effect": "If the 3rd lord is in the 9th, the native will lack paternal bliss, will make fortunes through wife and will enjoy progenic and other pleasures.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Although one may have fortunes and progenic happiness, one will unendingly feel miserable if the 3rd lord occupies the 9th house. His father will be a contemptible person."},
    (3, 10): {"verse": 34, "effect": "If the 3rd lord is in the 10th, the native will have all kinds of happiness and self-made wealth and be interested in nurturing wicked females.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (3, 11): {"verse": 35, "effect": "If the 3rd lord is in the 11th, the native will always gain in trading, be intelligent although not literate, be adventurous and will serve others.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: One will have an emaciated body with the 3rd lord's position in the 11th house. He will incur misunderstandings with others and will not be a worthy friend."},
    (3, 12): {"verse": 36, "effect": "If the 3rd lord is in the 12th, the native will spend on evil deeds, will have a wicked father and will be fortunate through a female (or wife).",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The 3rd lord going to the 12th will bestow every happiness in life. Yet the native will feel highly miserable. This view is held by Ramadayalu. This placement will further spoil the prospects of co-born. If Mars also joins the said 3rd lord, sustenance of co-born will be doubtful."},
    (4, 1): {"verse": 37, "effect": "If the 4th lord is in the ascendant, the native will be endowed with learning, virtues, ornaments, lands, conveyances and maternal happiness.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: As a result of the 4th lord coming to occupy the ascendant, the subject will acquire incomparable learning in various branches. However, there is an element of risk of being deprived of one's ancestral properties. After leading married life for some time, the native will give up worldly life and may turn into an ascetic."},
    (4, 2): {"verse": 38, "effect": "If the 4th lord is in the 2nd, the native will enjoy pleasures, all kinds of wealth, family life and honour and be adventurous. He will be cunning in disposition.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The 2nd house tenanted by the 4th lord will bring abundant gains from mother and maternal relatives. The mother of the native will be able to receive great help from her brothers and sisters. The subject will join evil company and face some risks. He will build up self-earned wealth and his lust for lucre will never be subdued. (OCR: 'Tho 2nd house')"},
    (4, 3): {"verse": 39, "effect": "If the 4th lord is in the 3rd, the native will be valorous. He will have servants, be liberal, virtuous and charitable and will possess self-earned wealth. He will be free from diseases.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (4, 4): {"verse": 40, "effect": "If the 4th lord is in the 4th, the native will be a minister and will possess all kinds of wealth. He will be skilful, virtuous, honourable, learned, happy and be welldisposed to his spouse.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (4, 5): {"verse": 41, "effect": "If the 4th lord is in the 5th, the native will be happy and be liked by all. He will be devoted to Sri Vishnu, be virtuous, honourable and will have self-earned wealth.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (4, 6): {"verse": 42, "effect": "If the 4th lord is in the 6th, the native will be devoid of maternal happiness, be given to anger, be a thief and a conjurer (or magician), be independent in action and be ill-disposed.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The native will be brought up by another female in the place of his mother. He will be careless about his own matters. He will have litigations on account of properties. His mother will be sickly in constitution and be a source of worry to the family members. He will not be welldisposed toward his mother. These are additional effects for the 6th house placement of the 4th lord in a nativity."},
    (4, 7): {"verse": 43, "effect": "If the 4th lord is in the 7th, the native will be endowed with a high degree of education, will sacrifice his patrimony and be akin to the dumb in an assembly.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: When the 4th lord occupies the 7th house, the person concerned will not enjoy paternal properties. He may either lose or sacrifice the same. He will not be a householder for a long time and will give up his family burdens sooner or later as a husband and as a father. Though he will achieve a great degree of education, he will be unable to express himself before a group of men."},
    (4, 8): {"verse": 44, "effect": "If the 4th lord is in the 8th the native will be devoid of domestic and other comforts, will not enjoy much parental happiness and be equal to a neuter.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The 4th lord's relegation to the 8th house will affect the progenic ability of the native and he will not be able to carnally satisfy his spouse. His happiness in household life will not be appreciable; some problem or the other will accost him. His education will face many an obstacle. His childhood will be with many difficulties."},
    (4, 9): {"verse": 45, "effect": "If the 4th lord is in the 9th, the native will be dear to one and all, be devoted to God, be virtuous, honourable and endowed with every kind of happiness.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (4, 10): {"verse": 46, "effect": "If the 4th lord is in the 10th, the native will enjoy royal honours, be an alchemist, be extremely pleased, will enjoy pleasures and will conquer his five senses.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: One will be professionally happy and prosperous with the 4th lord in the 10th house. He will have abundant self-made properties. He will, however, lack maternal happiness if the 4th lord in the said house is not happily placed."},
    (4, 11): {"verse": 47, "effect": "If the 4th lord is in the 11th, the native will have fear of secret disease, be liberal, virtuous, charitable and helpful to others.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Some say that the 11th house having the 4th lord will ensure freedom from diseases while our sage attributes secret diseases (like venereal affliction or any other diseases caused by physical union). Apparently the sage does not prefer the 4th lord (lord of happiness) getting relegated to the 11th (the 8th from the 4th)."},
    (4, 12): {"verse": 48, "effect": "If the 4th lord is in the 12th the native will be devoid of domestic and other comforts, will have vices and be foolish and indolent.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Complete absense of happiness, particularly paternal, will come to pass. One will be bereft of masculine vigour. His mother is of doubtful character. These are additional effects for the 4th lord being in the 12th house, according to classical works. (OCR: 'absense')"},
    (5, 1): {"verse": 49, "effect": "If the 5th lord is in the ascendant, the native will be scholarly, will be endowed with progenic happiness, be a miser, be crooked, and will steal others' wealth.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The native having the 5th lord in the ascendant will be of unsteady disposition. Though progenic happiness is denoted by our text, there are other exponents warning of an unpleasant situation in respect of one of the native's sons."},
    (5, 2): {"verse": 50, "effect": "If the 5th lord is in the 2nd, the native will have many sons and wealth, be a pater familias, be honourable, be attached to his spouse and be famous in the world.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Maharshi Parasara praises very highly the placement of the 5th lord in the 2nd house and attributes worldwide fame for the native (example: Smt. Indira Gandhi). The 2nd house position of the 5th lord gave her a world-wide position and honour for a very long number of years; the native will have ample opportunities of shining brilliantly with the 2nd house placement of the 5th lord in strength and dignity. The position of the 5th lord in the 2nd will further cause asthma and catarrh and the native will have infected lungs. He will become proud owing to his possessions."},
    (5, 3): {"verse": 51, "effect": "If the 5th lord is in the 3rd, the native will be attached to his co-born, be a talebearer and a miser, and be always interested in his own work.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The native will further be an imposter. He will not be helpful to anybody in any manner."},
    (5, 4): {"verse": 52, "effect": "If the 5th lord is in the 4th, the native will be happy, endowed with maternal happiness, wealth and intelligence, and be a king or a minister or a preceptor.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "A very long life will come to the native's mother. The native will start acquiring prosperity, right from his youth. He will also own a posh or beautiful house. These are additional effects that will come to pass with the 4th house having the 5th lord in it."},
    (5, 5): {"verse": 53, "effect": "If the 5th lord is in the 5th, the native will have progeny if related to a benefic; there will be no issues if malefic is related to the said 5th lord placed in 5th. The 5th lord in 5th will, however, make one virtuous and dear to friends.",
        "lagna_exception": "", "exception_source": "sloka",
        "notes_caveat": ""},
    (5, 6): {"verse": 54, "effect": "If the 5th lord is in the 6th, the native will obtain such sons who will be equal to his enemies or will lose them, or will acquire an adopted or purchased son.",
        "lagna_exception": "The situation of the 5th lord in the 6th house is not very desirable, of course excepting Saturn for Virgo ascendant.", "exception_source": "notes",
        "notes_caveat": "Maharshi Parasara enunciates four different possibilities if the 5th lord is in the 6th house: (1) obtaining sons that will be inimical to the native; (2) loss of children (the 6th is the maraka sthana for children as it is the 2nd from the 5th); (3) obtaining an adopted issue (normally when one is unable to have progeny of his own loins, or fails to have living children); (4) purchase of a child (also like adoption). Hence the situation of the 5th lord in the 6th house is not very desirable, of course excepting Saturn for Virgo ascendant. It is also not advisable for a female to have her 9th lord in the 10th house from the point of view of filial happiness."},
    (5, 7): {"verse": 55, "effect": "If the 5th lord is in the 7th, the native will be honourable, very religious, endowed with progenic happiness and be helpful to others.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "With the 5th lord going to the 7th house, the native will be tall in stature and will speak only truth. He will honestly serve his employer, and his dealings will be honest. He will be firm in disposition."},
    (5, 8): {"verse": 56, "effect": "If the 5th lord is in the 8th, the native will not have much progenic happiness, be troubled by cough and pulmonary disorders, be given to anger and be devoid of happiness.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (5, 9): {"verse": 57, "effect": "If the 5th lord is in the 9th, the native will be a prince or equal to him, will author treatises, be famous and will shine in his race.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The placement of the 5th lord in the 9th house is a good augury for writership, authorship, editorship and the like (example: horoscope of Jagadguru Adi Sankaracharya; also a horoscope from 'Doctrines of Suka Nadi-Retold', and Sri C. G. Rajan's chart). Apart from the 5th lord being in the 9th for fame via authorship, the 7th house having the 5th lord will equally contribute to such achievements."},
    (5, 10): {"verse": 58, "effect": "If the 5th lord is in the 10th, the native will enjoy a Rajayoga and various pleasures, and be very famous.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "For enjoying a superior degree of material benefits like wealth, position, fame etc. the 5th lord is the best placed in the 10th house than elsewhere. It is a prerequisite that in such a placement the 5th lord is very close to the meridian, if not exactly on the meridian, preferably with exaltation or such other dignities. If he is placed in an enemy's house or such other afflictions tormenting him, he will prove rather adverse than a Rajayoga maker."},
    (5, 11): {"verse": 59, "effect": "If the 5th lord is in the 11th, the native will be learned, dear to people, be an author of treatises, be very skilful and be endowed with many sons and wealth.",
        "lagna_exception": "If the 5th lord is inimically placed in the 11th house, for example the Sun in Aquarius in the 11th in the case of Aries ascendant, the progeny will be inimical to the native. However, obtainment of progeny will not be obstructed in that case even.", "exception_source": "notes",
        "notes_caveat": "The 5th lord's station in the 11th house will keep one free from misfortunes and unhappiness. He will be of helping nature. His academic achievements will be abundant. He will be happy in respect of his children, but the said 11th house should be a friendly sign for the 5th lord."},
    (5, 12): {"verse": 60, "effect": "If the 5th lord is in the 12th, the native will be bereft of happiness from his own sons, will have an adopted or purchased son.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The placement of the 5th lord in the 12th (terminal house) will cause various kinds of miseries in the matter of children. One may not obtain a child at all, or may incur inimical relations with his own child. Adoption will surely come to pass if Saturn or Mercury ruling the 5th is in the 12th. In other cases, the disposition of Saturn/Mercury/Jupiter will have to be seen while the 5th lord is in the 12th. Further grave defects with the 5th lord in the 12th are difficulties in digestion and abdominal disorders."},
    (6, 1): {"verse": 61, "effect": "If the 6th lord is in the ascendant, the native will be sickly, famous, inimical to his own men, rich, honourable, adventurous and virtuous.",
        "lagna_exception": "Venus in Taurus ascendant will particularly give benefic results in full measure as stated. He will also not stall obtainment of children. There will, however, be more daughters than sons, while the first child will be a male.", "exception_source": "notes",
        "notes_caveat": "The 6th lord in the ascending sign will bring various diseases to the native. He will incur adverse effects in the matter of acquisition of progeny."},
    (6, 2): {"verse": 62, "effect": "If the 6th lord is in the 2nd, the native will be adventurous, famous among his racemen, will live in alien countries (or places), be happy, be a skilful speaker and be always interested in his own work.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The native will further be skilful in dealing with hoary lore. His financial position will be somewhat shaky. He will enjoy good health."},
    (6, 3): {"verse": 63, "effect": "If the 6th lord is in the 3rd, the native will be given to anger, bereft of courage, inimical to all of his co-born and will have disobedient servants.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The 3rd house containing the 6th lord will not serve the native with intelligence at all times. To wit, he will be partly deprived of benefits due to his intelligence. He will also not be steady in disposition."},
    (6, 4): {"verse": 64, "effect": "If the 6th lord is in the 4th, the native will be devoid of maternal happiness, be intelligent, be a talebearer, be jealous, fickle-minded and very rich.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (6, 5): {"verse": 65, "effect": "If the 6th lord is in the 5th, the native will have fluctuating finances. He will incur enmity with his sons and friends. He will be happy, selfish and kind.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (6, 6): {"verse": 66, "effect": "If the 6th lord is in the 6th, the native will have enmity with the group of his kinsmen but be friendly to others and will enjoy mediocre happiness in matters like wealth.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The native will enjoy happiness of conveyances and be free from diseases. His life span will also be considerably lengthy. These are additional effects for the 6th lord in the 6th itself."},
    (6, 7): {"verse": 67, "effect": "If the 6th lord is in the 7th, the native will be deprived of happiness through wedlock. He will be famous, virtuous, honourable, adventurous and wealthy.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Apart from denying marital happiness, the 6th lord's occupancy of the 7th house will dissatisfy the native in the matter of progeny. His own spouse will be his sworn enemy."},
    (6, 8): {"verse": 68, "effect": "If the 6th lord is in the 8th, the native will be sickly, inimical, will desire others' wealth, be interested in others' wives and be impure (or degraded).",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "It is not good for one's purity of character if the 8th house is occupied by the 6th lord. The native will be ever incurring enmity with others and be not happy. He will have a green eye on others' learning and an eye on others' wealth."},
    (6, 9): {"verse": 69, "effect": "If the 6th lord is in the 9th, the native will trade in wood and stones (पाषाण also means poison), and will have fluctuating professional fortunes.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The Maharshi seems to suggest that one will deal in building construction material by saying that one will sell wood and stones with the 6th lord in the 9th. It will further cause ups and downs in one's livelihood."},
    (6, 10): {"verse": 70, "effect": "If the 6th lord is in the 10th, the native will be well-known among his men, will not be respectfully disposed to his father and will be happy in foreign countries. He will be a gifted speaker.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "One will be greatly valorous and learned in Sastras (or ancient lore). There will be litigations on account of ancestral properties. Dutifulness and living in foreign place will also come to pass. These are in furtherance of the sage's views for the placement of the 6th lord in the 10th house."},
    (6, 11): {"verse": 71, "effect": "If the 6th lord is in the 11th, the native will gain wealth through his enemies, be virtuous, adventurous and will be somewhat bereft of progenic happiness.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "One will, to some extent, be happy and to yet some extent be unhappy if the 6th lord occupies the 11th house. This is in regard to progeny. There is also a view that this position can wholly deny acquisition of a child."},
    (6, 12): {"verse": 72, "effect": "If the 6th lord is in the 12th the native will always spend on vices, be hostile to learned people and will torture living beings.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The native will be of questionable morality and will ever be intent on deriving sexual pleasures from other females as well."},
    (7, 1): {"verse": 73, "effect": "If the 7th lord is in the ascendant, the native will go to others' wives, be wicked, skilful, devoid of courage and afflicted with windy diseases.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The native will not be firm in his words and actions. He will impart courage in others although he himself will be bereft of courage. So say learned astrologers in the context of the ascendant being occupied by the 7th lord."},
    (7, 2): {"verse": 74, "effect": "If the 7th lord is in the 2nd, the native will have many wives, will gain wealth through his wife and be procrastinating in nature.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: This position will further give corrupt character making him addicted to many women. He will lose his wife early. His prosperity will ascend with his marriage."},
    (7, 3): {"verse": 75, "effect": "If the 7th lord is in the 3rd, the native will face loss of children and sometimes with great difficulty there will exist a living son. There is also the possibility of birth of a daughter (who will sustain).",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Three salient features in regard to progeny are denoted by sage Parasara for the 3rd house placement of the 7th lord. Firstly, loss of children in general. Secondly, possibility of (rarely) acquiring a daughter. Lastly, no possibility of having a living son. In fine, probably a female child will live long to keep the native happy, while male children will pass away as they are born."},
    (7, 4): {"verse": 76, "effect": "If the 7th lord is in the 4th, the wife of the native will not be under his control. He will be fond of truth, be intelligent and religious. He will suffer from dental diseases.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: A disobedient wife follows the 4th house position of the 7th lord. This is Maharshi's instruction. However, Ramadayalu states in this context that the native's wife will brilliantly shine with chastity or devotion to husband. Lord Rama's sacred horoscope is a classic example having Cancer ascendant with Saturn, the 7th lord, in the 4th (in exaltation). Santhanam cites a Saptarshi Nadi horoscope (Taurus ascendant, No.25) analysed by Parasara describing a virtuous chaste spouse, and reconciles that the 7th lord in the 4th (exalted/devout Venus context) gives a spouse devoted to the husband, so the sloka's version (wife not under control) is also rightly interpreted per the Chaukhamba edition which states the wife will not be chaste."},
    (7, 5): {"verse": 77, "effect": "If the 7th lord is in the 5th, native will be honourable, endowed with all (i.e. seven principal) virtues, always delighted and endowed with all kinds of wealth.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: I have observed two salient features in the 7th lord's getting into the 5th house. These are: (1) Delay and disappointments in married life. The conjugal life seldom proves happy. (2) Severe affliction to progenic indications. Either there will be unhappiness on account of children or loss of children. The effects mentioned by the sage (virtues, wealth, honour and general happiness) will also come to pass. The happiness about marriage and progeny will visibly be absent. This will further give rise to the native's association with great people. He will be endowed with boosted spirits."},
    (7, 6): {"verse": 78, "effect": "If the 7th lord is in the 6th, native will beget a sickly wife, be inimical to her, given to anger and devoid of happiness.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The 7th lord in the 6th will reduce the general happiness of the native apart from severely inflicting his conjugal bliss. His own health will be poor while his wife will be weak in constitution. She will equally have adverse health conditions. The native will coalesce with harlots."},
    (7, 7): {"verse": 79, "effect": "If the 7th lord is in the 7th, the native will be endowed with happiness through wife, be courageous, skilful and intelligent but only afflicted by windy diseases.",
        "lagna_exception": "This is an exception to Venus occupying the 7th house identical with Taurus or Libra (regarding the native's addiction to other females).", "exception_source": "notes",
        "notes_caveat": "Notes: By using the word 'kevalam' in the text meaning 'only', the sage hints that the only possible defect in the 7th lord's placement in the 7th itself will be troubles from windy diseases (rheumatism, arthritis etc.). One undesirable quality will, however, be found in the native, contrary to no adverse indication in the text, and that is his addiction to other females."},
    (7, 8): {"verse": 80, "effect": "If the 7th lord is in the 8th, the native will be deprived of marital happiness. His wife will be troubled by diseases, be devoid of good disposition and will not obey the native.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: As the 7th lord goes to the 8th house, the native's spouse will be liable to incur afflictions to her longevity. However, marriage may bring some pecuniary gains for the native."},
    (7, 9): {"verse": 81, "effect": "If the 7th lord is in the 9th, the native will have union with many women, be well-disposed to his own friends and will have many undertakings (or assignments).",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (7, 10): {"verse": 82, "effect": "If the 7th lord is in the 10th, the native will beget a disobedient wife, will be religious and endowed with wealth, sons etc.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (7, 11): {"verse": 83, "effect": "If the 7th lord is in the 11th, the native will gain wealth through his wife, endowed with less happiness from sons etc. and will have daughters.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: If the 7th lord is in the 11th house, there is a possibility of the native losing his children to his grief. He will obtain (more) daughters. His own sons will be hostile to him and will cause him no happiness. Living son also seems to be very remote a probability."},
    (7, 12): {"verse": 84, "effect": "If the 7th lord is in the 12th, the native will incur penury, be a miser and his livelihood will be related to clothes. His wife will be a spendthrift.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (8, 1): {"verse": 85, "effect": "If the 8th lord is in the ascendant, the native will be devoid of physical felicity and will suffer from wounds. He will be hostile to gods and brahmins (or religious people).",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (8, 2): {"verse": 86, "effect": "If the 8th lord is in the 2nd, the native will be devoid of bodily vigour, will enjoy a little wealth and will not regain lost wealth.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (8, 3): {"verse": 87, "effect": "If the 8th lord is in the 3rd, the native will be devoid of fraternal happiness, be indolent and devoid of servants and strength.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (8, 4): {"verse": 88, "effect": "If the 8th lord is in the 4th, the child will be deprived of its mother. He will be devoid of a house, lands and happiness and will doubtlessly betray his friends.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Maharshi Parasara uses the word \"sisu\" meaning child. Hence it is apparent that the native will lose his mother in the very childhood if the 8th lord is in the 4th house."},
    (8, 5): {"verse": 89, "effect": "If the 8th lord is in the 5th, the native will be dull-witted, will have limited number of children, be longlived and wealthy.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "One's financial acquisitions, though abundant, will not be steady and be subjected to fluctuations. Though his intentions and actions will be bona fide, they will go unrecognized. He will not be steady in disposition and will off and on change his line of thinking. He will not enjoy filial bliss. These are additional hints for the 8th lord's stationing in the 5th house at birth."},
    (8, 6): {"verse": 90, "effect": "If the 8th lord is in the 6th, the native will win over his enemies, be afflicted by diseases and during childhood will incur danger through snakes and water.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The position of the 8th lord in the 6th house is a sureshot of success over enemies and in litigations. The native will be reduced to danger through snakes, scorpions etc. during childhood. Afterwards he will be free from such calamities. However, this position is not very favourable for one's health. This also indicates a long span of life."},
    (8, 7): {"verse": 91, "effect": "If the 8th lord is in the 7th, the native will have two wives. If the 8th lord is conjunct a malefic in the 7th there will surely be downfall in his business (or livelihood).",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "The 7th house being occupied by the 8th lord is a forerunner of difficulties in married life. There will be want of understanding between the native and his spouse. The constitution of the spouse will be quite weak and she will always be subjected to uncertainties or dangers. Outwardly the native may pose to be God-fearing. But he will not be sincerely devoted to the Almighty. He will be an expert in stealing others' things."},
    (8, 8): {"verse": 92, "effect": "If the 8th lord is in the 8th the native will be long-lived. If the said planet be weak being in the 8th, the longevity will be medium, while the native will be a thief, be blameworthy and will blame others well.",
        "lagna_exception": "The evil effects cited above will not come to pass for an Aquarius native having Mercury in exaltation in the 8th in Virgo. He should be within the first half of Virgo to stall the said evils. In the later portion of Virgo his potence considerably decreases.", "exception_source": "notes",
        "notes_caveat": "In remaining in the 8th itself, the 8th lord should be quite strong in Shadbala, so the native will be long-lived. If he is bereft of strength, the native will not enjoy full span of life. The 8th house in occupation by its own lord will give a spouse with questionable character. However she will be a source of financial help to the native by her own earnings or properties. The native will inherit ancestral properties as well."},
    (8, 9): {"verse": 93, "effect": "If the 8th lord is in the 9th, the native will betray his religion, be a heterodox, will beget a wicked wife and will steal others' wealth.",
        "lagna_exception": "In the case of a Gemini native, Saturn occupying the 9th house (his Moolatrikona) will not produce these malefic effects. But his benefic tendencies will be quite meagre.", "exception_source": "notes",
        "notes_caveat": "The native will suffer frequent misfortunes and downfalls. His prosperity will be unobstructed and he will find it difficult to cope up with professional adversities. His father will suffer a cut in longevity. His understanding with his father will be deficient. Progenic happiness will not come to him in full measure. His wife will be of \"questionable birth\". She will go to other men and beget progeny. The native himself will be addicted to others' housewives."},
    (8, 10): {"verse": 94, "effect": "If the 8th lord is in the 10th the native will be devoid of paternal bliss, be a tale-bearer and be bereft of livelihood. If there is an aspect in the process from a benefic, then these evils will not mature.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "There is a school of thought to say that the 8th lord occupying the 9th house will cause the deaths of parents right in the native's boyhood. Apparently one will not enjoy parental happiness for a long duration. This placement of the 8th lord will produce all kinds of miseries in livelihood, fortunes, fame, properties and the like. According to Maharshi Parasara, if the 8th lord in the 10th house is (well) related to a benefic, no evils will come to pass."},
    (8, 11): {"verse": 95, "effect": "If the 8th lord along with a malefic is in the 11th, the native will be devoid of wealth and will be miserable in boyhood but happy later on. Should the 8th lord be in conjunction with a benefic and be in the 11th, the native will be long-lived.",
        "lagna_exception": "Moreover, for Taurus ascendant, Jupiter in the 11th house is not baneful. And for Scorpio ascendant, Mercury in the 11th will prove a highly favourable bargain in the matter of wealth, fame, knowledge etc.", "exception_source": "notes",
        "notes_caveat": "The 8th lord in the 11th house, unless related to a malefic, particularly by conjunction, will not deprive the native of financial benefits. If he is alone in the 11th, he will not prove that bad in this respect."},
    (8, 12): {"verse": 96, "effect": "If the 8th lord is in the 12th, the native will spend on evil deeds and will incur a short life. More so, if there is additionally a malefic in the said house.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (9, 1): {"verse": 97, "effect": "If the 9th lord is in the ascendant, the native will be fortunate (or prosperous), will be honoured by the king, be virtuous, charming, learned and honoured by the public.",
        "lagna_exception": "These effects will not be enjoyed by a Scorpio native.", "exception_source": "notes",
        "notes_caveat": "Notes: If the 9th lord is in the rising sign, the native will hold a very high position which will bring him wealth and fame. He will be free from enemies. A female having the said position will prove a worthy housewife and be rid of afflictions from other planetary sources."},
    (9, 2): {"verse": 98, "effect": "If the 9th lord is in the 2nd, the native will be a scholar, be dear to all, wealthy, sensuous and endowed with happiness from wife, sons etc.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (9, 3): {"verse": 99, "effect": "If the 9th lord is in the 3rd, the native will be endowed with fraternal blies [bliss], be wealthy, virtuous and charming.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "OCR: printed 'blies' is evidently 'bliss'."},
    (9, 4): {"verse": 100, "effect": "If the 9th lord is in the 4th, the native will enjoy houses, conveyances and happiness, will have all kinds of wealth and be devoted to his mother.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (9, 5): {"verse": 101, "effect": "If the 9th lord is in the 5th the native will be endowed with sons and prosperity, devoted to elders, bold, charitable and learned.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (9, 6): {"verse": 102, "effect": "If the 9th lord is in the 6th, the native will enjoy meagre prosperity, be devoid of happiness from maternal relatives and be always troubled by enemies.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (9, 7): {"verse": 103, "effect": "O Brahmin, If the 9th lord is in the 7th, the native will beget happiness after marriage, be virtuous, and famous.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: One will further be able to achieve success in all his undertakings. His prosperity will pick up after marriage. The native will be not well disposed to his father. These are additional effects due to the 7th house placement of the 9th lord."},
    (9, 8): {"verse": 104, "effect": "If the 9th lord is in the 8th, the native will not be prosperous and will not enjoy happiness from his elder brother.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Having got the 9th lord relegated to the 8th house, one will be devoid of fortunes. He will face failures in all his undertakings. He will not achieve professional and financial stability. His father will primarily incur a cut in longevity. The native will be a source of miseries to his elder brothers/sisters. A blessing in disguise with this position is a probable inheritance of patrimony by the native."},
    (9, 9): {"verse": 105, "effect": "If the 9th lord is in the 9th, the native will be endowed with abundant fortunes, virtues and beauty and will enjoy much happiness from co-born.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Should the 9th lord be in the 9th itself, one will obtain fraternal bliss. His co-born will amass fortune. The native himself will own properties in a large scale. He will achieve easy success in each and every undertaking. His father will play a significant role in his (i.e. the native's) progress. The native's mother will be free from diseases. The native will be nurtured by his maternal grand parents."},
    (9, 10): {"verse": 106, "effect": "If the 9th lord is in the 10th, the native will be a king or equal to him or a minister or an army chief, be virtuous and dear to all.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The sage suggests that with the 9th lord going to the 10th the native will be either a king or a minister or an army chief. Apparently, if the 9th lord is prepotent, one will enjoy royal status. The strength proportionately falling down will make the native enjoy comparatively lesser positions."},
    (9, 11): {"verse": 107, "effect": "If the 9th lord is in the 11th, the native will enjoy financial gains day by day, be devoted to elders, virtuous and meritorious in acts.",
        "lagna_exception": "This will, however, not apply to Gemini ascendant having Saturn, the 9th lord, in the 11th house. On the contrary it will prove highly detrimental for the prosperity of the native.", "exception_source": "notes",
        "notes_caveat": "Notes: The native who has the 9th lord in the 11th house will see increasing phases of fortunes and prosperity. The 9th lord indicates one's prosperity and the 11th house gains. Hence the said position is extremely favourable for material upliftment. Additional effects due to the 9th lord's placement in the 11th house (excepting of course Gemini ascending), high honours, spiritual success, metaphysical achievements and gains through father."},
    (9, 12): {"verse": 108, "effect": "If the 9th lord is in the 12th, the native will incur loss of fortunes, will always spend on auspicious acts and will become poor on account of entertaining guests.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The 9th lord in the 12th is said to cause loss of wealth on account of entertaining guests. In the modern context lavish parties will take this role. The native will land in financial difficulties on account of throwing parties and the like. This position is not also auspicious for the happiness of elder brothers and sisters."},
    (10, 1): {"verse": 109, "effect": "If the 10th lord is in the ascendant, the native will be scholarly, famous, be a poet, will incur diseases in boyhood and be happy later on. His wealth will increase day by day.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The 10th lord occupying the ascendant is very favourable for riches giving a royal status to the native. If there are no Balarishta combinations and if the 6th lord is sufficiently favourable, then the position of the 10th lord in the ascendant will not cause diseases in boyhood. (Illustrated by the chart of Sarabhoji Maharaja of Tanjore, whose 10th lord Mercury is in the ascendant in own sign.)"},
    (10, 2): {"verse": 110, "effect": "If the 10th lord is in the 2nd, the native will be wealthy, virtuous, honoured by the king, charitable and will enjoy happiness from father and others.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The placement of the 10th lord in the 2nd will give immeasurable financial success through one's own profession or calling, apart from a large scale patrimony. (This will be more effective for Gemini ascendant having the 10th lord Jupiter in the 2nd in exaltation). His fame will spread in all corners. Illustrated by the horoscope of Mr. Morarji Desai and referenced to Mrs Indira Gandhi (Mars ruling the 10th in the 2nd)."},
    (10, 3): {"verse": 111, "effect": "If the 10th lord is in the 3rd, the native will enjoy happiness from brothers and servants, be valorous, virtuous, eloquent and truthful.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (10, 4): {"verse": 112, "effect": "If the 10th lord is in the 4th, the native will be happy, be always interested in his mother's welfare, will lord over conveyances, lands and houses, be virtuous and wealthy.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (10, 5): {"verse": 113, "effect": "If the 10th lord is in the 5th, the native will be endowed with all kinds of learning, be always delighted and be wealthy and endowed with sons.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The lord of the 10th house occupying the 5th house will prove a great asset for the native bestowing abundant wealth which will never leave him. He will have a number of children. There will seldom be filial grief for him. He will always move among wealthy people. In the matter of learning and education, sky is the limit in his case. He will command all material comforts of life. Illustrated by Dr. Rabindranath Tagore's natus (10th lord Jupiter in exaltation in the 5th)."},
    (10, 6): {"verse": 114, "effect": "If the 10th lord is in the 6th, the native will be bereft of paternal bliss. Although he may be skilful he will be bereft of wealth and be troubled by enemies.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: The 10th lord going to the 6th house is a dire blemish for professional and monetary stability. One will undergo frequent changes in his calling and will suffer losses therein. His financial growth will be severely paralyzed. He will have a number of enemies contributing to his decline. He will incur lasting diseases. An advantage, however, will come to him in the form of extreme intelligence."},
    (10, 7): {"verse": 115, "effect": "If the 10th lord is in the 7th, the native will be endowed with happiness through wife, be intelligent, virtuous, eloquent, truthful and religious.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (10, 8): {"verse": 116, "effect": "If the 10th lord is in the 8th, the native will be devoid of (good) acts, longlived and intent on blaming others.",
        "lagna_exception": "The rule as per the present verse will not apply to a Gemini ascendant horoscope having Jupiter in the 8th (in fall), which will adversely affect longevity. And a Leo native will be a significant beneficiary with Venus in the 8th in exaltation and will enjoy a considerably long span of life.", "exception_source": "notes",
        "notes_caveat": "Notes: The 10th lord's placement in the 8th house denotes potence of longevity. The 10th lord is the indicator of one's Karmic credit and his strength or his position in the 8th house will contribute to great longevity. That the 10th lord should be considered akin to Saturn in the matter of life span is a fact taught to us by Maharshi Parasara, vide sloka 3 in ch. 19."},
    (10, 9): {"verse": 117, "effect": "If the 10th lord is in the 9th, one born of royal scion will become a king whereas an ordinary native will be equal to a king. This placement will confer wealth and progenic happiness etc.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (10, 10): {"verse": 118, "effect": "If the 10th lord is in the 10th, the native will be skilful in all jobs, be valorous, truthful and devoted to elders.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (10, 11): {"verse": 119, "effect": "If the 10th lord is in the 11th, the native will be endowed with wealth, happiness and sons. He will be virtuous, truthful and always delighted.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (10, 12): {"verse": 120, "effect": "If the 10th lord is in the 12th, the native will spend through royal abodes (i.e. kings), will have fear from enemies and will be worried in spite of being skilful.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Expenditure through royal abodes possibly indicates that the native will lose on taxes, fines etc. to the government as the 12th house is involved. Otherwise, this can mean luxurious political expenses. This placement will cause troubles in financial matters through the Government."},
    (11, 1): {"verse": 121, "effect": "If the 11th lord is in the ascendant, the native will be genuine in disposition, be rich, happy, even-sighted, be a poet, be eloquent in speech and be always endowed with gains.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: When the 11th lord is in the ascendant, the native will always befriend the virtuous and reject evil associations. He will be extremely prosperous after marriage."},
    (11, 2): {"verse": 122, "effect": "If the 11th lord is in the 2nd, the native will be endowed with all kinds of wealth and all kinds of accomplishments, be charitable, religious and always happy.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (11, 3): {"verse": 123, "effect": "If the 11th lord is in the 3rd, the native will be skilful in all jobs, wealthy, endowed with fraternal bliss and may sometimes incur gout pains.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (11, 4): {"verse": 124, "effect": "If the 11th lord is in the 4th, the native will gain from maternal relatives, will undertake visits to shrines and will possess happiness of house and lands.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (11, 5): {"verse": 125, "effect": "If the 11th lord is in the 5th, the native's children will be happy, educated and virtuous. He will be himself religious and happy.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (11, 6): {"verse": 126, "effect": "If the 11th lord is in the 6th, the native will be afflicted by diseases, be cruel, living in foreign places and troubled by enemies.",
        "lagna_exception": "(In Aquarius, the 11th lord will particularly afflict a Virgo native with dire deafness.) — from Santhanam's Notes, not the sloka.", "exception_source": "notes",
        "notes_caveat": "Notes: The placement of the 11th lord in the 6th house will augment the chances of 'acquisition' of diseases. The native will incur defects of hearing organ. ... The native will be so selfish that for his own happiness he will leave his family members and live away from his home or hometown. Servitude will befit him rather than an independent profession. He will often undergo financial reversals."},
    (11, 7): {"verse": 127, "effect": "If the 11th lord is in the 7th, the native will always gain through his wife's relatives, be liberal, virtuous, sensuous and will remain at the command of his spouse.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Should the 7th house be occupied by the 11th lord, the native will always look upto and receive help from his wife's relatives. He will be quite affluent as well. He will lack in wisdom. Judgement will lack in him in the matter of expenses and he cannot make out where to spend and where not. A strong urge to seek union with others' females will always be prevalent in him but none will bother for him. Even his own spouse will boss over him."},
    (11, 8): {"verse": 128, "effect": "If the 11th lord is in the 8th, the native will incur reversals in his undertakings and will live long while his wife will predecease him.",
        "lagna_exception": "This rule should not be applied to Leo ascendant having Mercury, the 11th lord, in the 8th house in debilitation. — from Santhanam's Notes, not the sloka.", "exception_source": "notes",
        "notes_caveat": "Notes: The 11th lord in the 8th house increases the native's longevity. The geniture given earlier of Sri Morarji Desai having Mars in the 8th being the 11th lord bears an ample testimony to this effect."},
    (11, 9): {"verse": 129, "effect": "If the 11th lord is in the 9th, the native will be fortunate, skilful, truthful, honoured by the king and be affluent.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (11, 10): {"verse": 130, "effect": "If the 11th lord is in the 10th, the native will be honoured by the king, be attached to his religion, intelligent, truthful and will subdue his senses.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: With the 11th lord occupying the 10th house, one will be primarily intent on public welfare and redemption... The sacred horoscope of Sri Bhakti Vedanta Swamiji (born September 1, 1896 AD, 1530 hrs at Calcutta) is given as a fitting example (11th lord Venus in the 10th in debilitation with 10th lord Mercury in exaltation = Neechabhanga). Santhanam's moral: if the 11th lord is well disposed in the 10th house, the native will dedicate his life for others and be devoid of desires to meeting personal ends."},
    (11, 11): {"verse": 131, "effect": "If the 11th lord is in the 11th, the native will gain in all his undertakings while his learning and happiness will be on the increase day by day.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (11, 12): {"verse": 132, "effect": "If the 11th lord is in the 12th, the native will always expend on good deeds, be sensuous, will have many wives and will befriend barbarians (or foreigners in general).",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (12, 1): {"verse": 133, "effect": "If the 12th lord is in the ascendant, the native will be a spendthrift, be weak in constitution, will suffer from phlegmatic disorders, and be devoid of wealth and learning.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: Phlegmatic disorders relate to breathing troubles, lung disorders, tuberculosis etc. With the 12th lord going to the rising sign, the native will always suffer from one disease or the other. He will ever be in the grip of fear of death. He will acquire many vices. His undertakings will not yield success."},
    (12, 2): {"verse": 134, "effect": "If the 12th lord is in the 2nd, the native will always spend on auspicious deeds, be religious, will speak sweetly and be endowed with virtues and happiness.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (12, 3): {"verse": 135, "effect": "If the 12th lord is in the 3rd, the native will be devoid of fraternal bliss, will hate others and will promote self-nourishment (i.e. be quite selfish).",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (12, 4): {"verse": 136, "effect": "If the 12th lord is in the 4th the native will be devoid of maternal happiness and will day by day accrue losses in respect of lands, conveyances and houses.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (12, 5): {"verse": 137, "effect": "If the 12th lord is in the 5th, the native will be bereft of sons and learning. He will spend as well as visit shrines in order to beget a son.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (12, 6): {"verse": 138, "effect": "If the 12th lord is in the 6th, the native will incur enmity with his own men, be given to anger, be sinful, miserable and will go to others' wives.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (12, 7): {"verse": 139, "effect": "If the 12th lord is in the 7th, the native will incur expenditure on account of his wife, will not enjoy conjugal bliss and will be bereft of learning and strength.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (12, 8): {"verse": 140, "effect": "If the 12th lord is in the 8th, the native will always gain, will speak affably, will enjoy a medium span of life and be endowed with all good qualities.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: By 'medium life' it is meant to denote a span of life of 60 years. So to say the 12th lord in the 8th will not be in a position to contribute to higher bracket of longevity."},
    (12, 9): {"verse": 141, "effect": "If the 12th lord is in the 9th, the native will dishonour his elders, be inimical even to his friends and be always intent on achieving his own ends.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (12, 10): {"verse": 142, "effect": "If the 12th lord is in the 10th, the native will incur expenditure through royal persons and will enjoy only moderate paternal bliss.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
    (12, 11): {"verse": 143, "effect": "If the 12th lord is in the 11th, the native will incur losses, be brought up by others and will sometimes gain through others.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": "Notes: One will face obstacles in begetting a child if the 12th lord occupies the 11th house. He will at last adopt a child."},
    (12, 12): {"verse": 144, "effect": "If the 12th lord is in the 12th, the native will only face heavy expenditure, will not have physical felicity, be irritable and spiteful.",
        "lagna_exception": "", "exception_source": "none",
        "notes_caveat": ""},
}

# house -> {verse, text}  (ch.11 vv.2-13)
HOUSE_SIGNIFICATIONS = {
    1: {"citation": "BPHS Vol I, Ch.11 v.2 (p.121)", "text": "INDICATIONS OF THE FIRST HOUSE: physique, appearance, intellect (or the organ of intelligence, i.e. brain), complexion of the body, vigour, weakness, happiness, grief and innate nature are all to be guessed through the ascending sign."},
    2: {"citation": "BPHS Vol I, Ch.11 v.3 (p.121)", "text": "SECOND HOUSE: Wealth, grains (food etc.), family, death, enemies, metals, precious stones etc. are to be understood through the 2nd house."},
    3: {"citation": "BPHS Vol I, Ch.11 v.4 (p.121)", "text": "THIRD HOUSE: From the 3rd house, know of the following: tilour, servants (attendants etc.), brothers, sisters etc. initiatory instrucitons (upadesa), journey, and parent's death."},
    4: {"citation": "BPHS Vol I, Ch.11 v.5 (p.121)", "text": "FOURTH HOUSE: Conveyances, relatives, mother, happiness, treasure, lands and houses are to be consulted through the 4th house."},
    5: {"citation": "BPHS Vol I, Ch.11 v.6 (p.122)", "text": "FIFTH HOUSE: The learned should deduce from the 5th house amulets, sacred spells, learning, knowledge, sons, royalty (or authority), fall of position etc."},
    6: {"citation": "BPHS Vol I, Ch.11 v.7 (p.122)", "text": "SIXTH HOUSE: Maternal uncle, doubts about death, enemies, ulcers, step mother etc. are to be estimated from the 6th house."},
    7: {"citation": "BPHS Vol I, Ch.11 v.8 (p.122)", "text": "SEVENTH HOUSE: Wife, travel, trade, loss of sight, death etc. be known from the 7th house."},
    8: {"citation": "BPHS Vol I, Ch.11 v.9 (p.122)", "text": "EIGHTH HOUSE: The 8th house indicates longevity, battle, enemies, forts, wealth of the dead, and things that have happened and are to happen (in the past and future births)."},
    9: {"citation": "BPHS Vol I, Ch.11 v.10 (p.122)", "text": "NINTH HOUSE: Fortunes, wife's brother, religion, brother's wife, visits to shrines etc. be known from the 9th house."},
    10: {"citation": "BPHS Vol I, Ch.11 v.11 (p.122)", "text": "TENTH HOUSE: Royalty (authority), place, profession (livelihood), honour, father, living in foreign lands and debts are to be understood from the 10th house."},
    11: {"citation": "BPHS Vol I, Ch.11 v.12 (p.123)", "text": "ELEVENTH HOUSE: All articles, son's wife, income, prosperity, quadrupeds etc. are to be understood from the 11th house."},
    12: {"citation": "BPHS Vol I, Ch.11 v.13 (p.123)", "text": "TWELFTH HOUSE: From the 12th house, one can know about expenses, history of enemies, one's own death etc."},
}

# house -> graha key  (ch.32 vv.31-34)
HOUSE_KARAKA = {
    1: "sun",   # Sun
    2: "jupiter",   # Jupiter
    3: "mars",   # Mars
    4: "moon",   # Moon
    5: "jupiter",   # Jupiter
    6: "mars",   # Mars
    7: "venus",   # Venus
    8: "saturn",   # Saturn
    9: "jupiter",   # Jupiter
    10: "mercury",   # Mercury
    11: "jupiter",   # Jupiter
    12: "saturn",   # Saturn
}

# ch.24 vv.145-148 — the only licensed combination rule (verbatim)
COMBINATION_RULE = "BPHS Vol I, Ch.24 vv.145-148 'MISCELLANEOUS' (pp.235-236), verbatim sloka effect: \"O Brahmin, those are the effects of house lords which are to be deduced considering their strengths and weaknesses. In the case of a planet owning two bhavas, the results are to be deducted based on its two lordships (for the same placement). If contrary results are thus indicated, the results will be nullified, while results of varied nature will come to pass. The planet will yield full, half or a quarter of the effects according to its strength being full, medium and negligible respectively. Thus I have told you about the effects due to bhava lords in various bhavas.\" [Translator's Notes (commentary, not sloka): Except the Sun and the Moon, the other 5 planets own two bhavas each. In the case of the Sun and the Moon, the results cited will come to pass. One should give due consideration to various other relative factors; simply applying the effects without checking other sources will lead to pitfalls. Worked example given: for a Pisces ascendant, Saturn in the 5th house acts as both 11th lord (children/happiness through them) and 12th lord (denies progeny, resort to visiting shrines); the contrary results should not be declared straightaway but alternative sources like Jupiter (significator of progeny) and the Moon (owner of the 5th house) looked up. For mutually different spheres, after sorting the controversy it is declared that Saturn in the 5th deprives the Pisces native of learning (12th lordship) and makes him religious and happy (11th lordship).]"

# ch.32 vv.18-21 (constant relative significators) + vv.35-37 (house classification)
RELATIVE_SIGNIFICATORS = "BPHS Vol I, Ch.32 vv.18-21 'CONSTANT SIGNIFICATORS' (p.320), verbatim: \"I narrate below the constant significators as related to the planets. The stronger among the Sun and Venus indicates the father while the stronger among the Moon and Mars indicates the mother. Mars denotes sister, brother-in-law, younger brother and mother. Mercury rules maternal relative while Jupiter indicates paternal grand-father. Husband and sons are respectively denoted by Venus and Saturn. From Ketu note wife, father, mother, parents-in-law and maternal grand father. These are constant significators.\" [Translator's tabulation (Notes, commentary not sloka): Sun/Venus = stronger indicates father; Moon/Mars = stronger indicates mother; Mars = sister, brother-in-law, younger brother and mother; Mercury = maternal relatives; Jupiter = paternal grand-father; Venus = husband; Saturn = sons; Ketu = wife, father, mother, parents-in-law, maternal grand father.] Cross-reference caveat from Ch.32 vv.22-24 Notes (p.321): the constant Karakas as normally discussed in standard literature are Sun=father, Moon=mother, Mars=brothers (and sisters), Mercury=maternal relatives, Jupiter=Sons (and daughters), Venus=wife (or husband), Saturn=death (or longevity)."
HOUSE_CLASSIFICATION = "BPHS Vol I, Ch.32 vv.35-37 'HOUSE SIGNIFICANCE' (p.326), verbatim: \"O excellent of the Brahmins, after knowing the merits of the 1st house etc. the good and bad effects be declared. 11th, 3rd, 8th, 6th, 2nd and 12th are malefic bhavas. Association with these houses will inflict evils. Angles and trines are auspicious bhavas, the association with which turns even evils into auspiciousness.\" [Translator's Notes (commentary, not sloka): The 6 malefic bhavas are 11th, 3rd, 8th, 6th, 2nd and 12th; a planet owning or occupying one of these becomes a functional malefic/adversary. The other 6 good houses are ascendant, 4th, 5th, 7th, 9th and 10th; planets associated with these prove favourable although by nature evil or adverse. Also see ch.34 for more information.]"
