"""
Bṛhat Jātaka of Varāhamihira (~550 CE), B. Suryanarain Row tr. (1919) — CLASSICAL tier.

Planet-in-sign for all seven grahas: the Moon (ch.17, Rāśiśīlādhyāya) and the Sun,
Mars, Mercury, Jupiter, Venus, Saturn (ch.18). The 1919 translation is public domain.
Each entry is a concise, cited, adaptation-classified GIST per docs/classical-sources-
policy.md, verified against the edition and independently checked for faithfulness,
policy (§5) and non-fatalism. Varāhamihira is terse (esp. ch.18); gists stay terse.
"""
SOURCE = {
    "id": "brihat_jataka", "text": "Bṛhat Jātaka", "author": "Varāhamihira",
    "date": "~550 CE", "translator": "B. Suryanarain Row, 1919 (public domain)",
    "tier": "classical",
}

# graha key -> sign index (0=Meṣa … 11=Mīna) -> entry. All seven grahas, 12 signs each.
IN_SIGN = {
    'sun': {
        0: {  # Aries
            "citation": 'Bṛhat Jātaka 18.1',
            "gist": 'Bṛhat Jātaka reads a native with the Sun in Aries as renowned, clever, much-travelled, and a "bearer of arms" (glossed: a soldierly / martial vocation) — and, as the dated text states, of little wealth. In the Sun\'s deep exaltation the text raises the same signature: very famous, clever, wealthy, and a "commander of men bearing arms" (glossed: a martial leadership role).',
            "adaptation": {"classes": ['archaic', 'health'], "action": 'historicise',
                            "note": "Two martial referents are GLOSSED, not dropped: 'bearer of arms' = a soldierly/martial vocation; 'commander of men bearing arms' = a martial leadership role (§5 archaic-referent → gloss). The 'little wealth' clause is HISTORICISED — carried as the text's dated stated-effect, cited and dated, never as fate or a financial claim; it triggers the historical-context badge. Single `action` recorded as 'historicise' because that is the badge-driving, more-protective operation of the two; the gloss is spelled out here. Whole verse ships; framing attributed and non-fatalistic ('the text reads the native as…'); pronoun neutralised to 'the native'. No caste, gender/marriage, servitude, occupation-ranking, or remedy content present, so nothing omitted, refused, or neutralised."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Bṛhat Jātaka 18.1',
            "gist": "Bṛhat Jātaka (18.1) reads the Sun-in-Taurus native as earning a livelihood through trade in scents and clothing, and as gifted in drumming and music. One clause — a blanket dislike of women — is refused as a value-laden gendered judgement with no structural principle to preserve. Presented as the text's ~550 CE stated reading, not as fate.",
            "adaptation": {"classes": ['occupation', 'gender'], "action": 'refuse',
                            "note": "Terse one-liner, mixed handling. Occupation clause ('sell scents and clothes') KEPT as the livelihood theme (trade in perfumes/clothing) — §5 Occupation-status says keep the theme, drop any high/low rank; the verse states no rank, so nothing to drop. Gender clause ('hate females') REFUSED under §5 Gender & marriage: a pure value-laden gendered judgement with no surviving structural principle to neutralise; shown as an explicit refusal-with-reason (cite-or-refuse). Music clause ('clever in drumming and music') is CLEAN and kept as a talent for percussion/music. No caste, servitude, death-timing, poverty, archaic-referent, or remedy content present. Framed by attribution + ~550 CE date, non-fatalistic."},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Bṛhat Jātaka 18.2',
            "gist": "Bṛhat Jātaka states that the Sun in Gemini makes the native educated and learned, earning a livelihood through astrology, and wealthy — given as the text's stated effect, not as the reader's fate.",
            "adaptation": {"classes": ['occupation'], "action": 'clean',
                            "note": "No caste, gender/marriage, servitude, remedy, or death-timing content. The astrologer theme is kept as a plain livelihood (livelihood via astrology); it carries no high/low ranking, so the occupation-STATUS class is not triggered and nothing is dropped, and it needs no archaic gloss (astrologer is still a recognizable calling). 'Wealthy' is a positive effect — not the negative poverty class — and ships with the standard cited, dated, non-fatalistic framing (the text's stated effect, never the reader's destiny). Nets to clean."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Bṛhat Jātaka 18.2',
            "gist": "Bṛhat Jātaka reads the Sun-in-Cancer native as quick to anger and worn by fatigue from travel and other cares, labouring at others' behest — and, as the text's dated view (not fate), of poor means.",
            "adaptation": {"classes": ['health', 'slavery'], "action": 'historicise',
                            "note": "Poverty ('poor') kept as the text's dated stated-effect, not fate and not financial advice (§5 poverty → historicise; refuse is reserved for death-timing, absent here). 'Doing others' work' historicised/neutralised to status-neutral 'labouring at others' behest' — the dependent-labour theme survives, no servile rank imported (the verse names no servant/slave term). Anger and fatigue-through-travel are clean and kept plainly (no §5 class). No caste, gender, marriage, remedy, or death-timing content in this verse; nothing refused. Carry the historical-context badge for the dated poverty/dependent-labour framing."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Bṛhat Jātaka 18.2',
            "gist": 'Bṛhat Jātaka assigns the Sun in Leo a love of forests, mountains and cattle, and reads the native as courageous and dull-witted.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "The one-liner triggers none of the protected classes. No caste, gender/marriage, slavery/rank, death/disease/poverty, remedy, or archaic referent. The 'cattle' reference is an affinity, not a ranked or low livelihood, so it is not an occupation-status flag. 'Courageous' and 'dull(-witted)' are gender-neutral character traits kept faithfully under 'else -> clean'. The source's fatalistic 'causes' is reframed as the text's stated reading ('Bṛhat Jātaka assigns...', 'reads the native as...'). Kept terse to match the terse source. Public-domain text, so no §4 reproduction concern either."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Bṛhat Jātaka 18.2',
            "gist": 'Bṛhat Jātaka reads the Sun-in-Virgo native as skilled in writing, painting, poetry, philosophy and mathematics, and of a delicate physical form.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "The skill list (writing, painting, poetry, philosophy, mathematics) is neutral, non-dated content and is kept verbatim. 'Possesses a feminine body' is the only §5-flagged element (Gender & marriage). A structural principle survives — Virgo is a feminine, Mercurial, earthy sign whose classical physical signature is a soft, delicate build — so per §5 it is neutralised: the gendered wrapper 'feminine' is dropped and the surviving structural descriptor ('a delicate physical form') is kept, rather than refused. No caste, occupation-status, slavery/rank, death/disease/poverty, remedy, or archaic-referent content is present."},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Bṛhat Jātaka 18.3',
            "gist": 'Bṛhat Jātaka 18.3 reads the Sun in Libra as assigning the native a livelihood tied to the drink trade and to goldsmithing (metal-craft), an inclination to drink, and a traveller\'s life. Shown as the text\'s dated (~550 CE) reading, not as fate. Its "mean" moral ranking is dropped.',
            "adaptation": {"classes": ['occupation', 'archaic'], "action": 'drop-status + gloss (remainder clean)',
                            "note": "Two §5 classes apply. OCCUPATION-STATUS (drop-status): 'toddy-seller' and 'goldsmith' are kept as livelihood themes (the drink trade; goldsmithing/metal-craft) with their low/mean status ranking DROPPED, and the standalone value-word 'mean' is dropped as a moral/status verdict — the §5 occupation-status action is drop-status (keep the livelihood, drop the ranking), NOT historicise, since no death/disease/poverty content is present to keep-cited-not-fated. ARCHAIC-REFERENT (gloss): the era-specific trades are glossed in context — 'toddy' as the drink/alcohol trade, 'goldsmith' as metal-craft — kept legible without inventing modern specifics. Remainder CLEAN: 'drunkard' ships plainly as an inclination to drink (a character trait, no protected class), and 'traveller' as a traveller's/wandering life. No caste, gender/marriage, slavery/servitude/rank, death/disease/poverty, or remedy content is present, so nothing is omitted, refused, or neutralised. Framed by attribution ('the text reads…') and dated to ~550 CE, never as the reader's fate."},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Bṛhat Jātaka 18.3',
            "gist": "Bṛhat Jātaka reads the Sun-in-Scorpio native as cruel, adventurous, rash, and a destroyer — skilled with weapons (martial skill in its ~6th-century context), earning a livelihood by trade in poisonous substances, and (in the text's dated view) prone to losing wealth to thieves. Presented as the text's reading of the placement, not a prediction about you.",
            "adaptation": {"classes": ['archaic', 'occupation', 'health'], "action": 'gloss (archaic weapons) + drop-status/keep-livelihood (occupation) + keep-cited-not-fated (poverty); remaining character traits clean',
                            "note": "§5 classes present: archaic-referent, occupation-status (precautionary), and the poverty sub-element of death/disease/poverty; the rest is clean. ARCHAIC (gloss): 'skilled in military weapons' kept and glossed as martial skill / weapon-handling in its ~6th-c. context, not modernised. OCCUPATION-STATUS (drop-status): 'profits by sale of poisonous substances' kept as the livelihood theme (trade in poisonous substances); the verse states no explicit high/low rank, so the status flag is precautionary and no moral ranking is implied. DEATH/DISEASE/POVERTY (keep-cited-not-fated): 'losing wealth by robbers' kept as the text's dated stated-effect, framed as the ~6th-c. reading, not as fate and not as financial advice. CLEAN, shipped plainly as the text's dated, unendorsed character (else→clean, NOT softened): 'cruel', 'adventurous', 'rash' and 'a destroyer' — none carry a policy class, so per §5 and consistent with the sister Sārāvalī-Scorpio entry (which ships 'cruel' plainly), they are retained in sense as the text's character reading rather than bowdlerised. No caste, gender/marriage, slavery/servitude, or remedy content is present in this verse, so nothing was omitted or refused; framed throughout by attribution ('the text reads…'), dated, never as the reader's fate."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Bṛhat Jātaka 18.3',
            "gist": 'Bṛhat Jātaka reads the Sun-in-Sagittarius native as respected and wealthy, with an angry temperament, and assigns a livelihood in healing (physician) and skilled craft (artisan).',
            "adaptation": {"classes": ['archaic', 'occupation'], "action": 'gloss',
                            "note": '"Doctor" and "artisan" are archaic occupation referents, glossed in context as physician/healer and skilled craftsman; the livelihood theme is kept and no high/low status ranking is present, so nothing is dropped. "Rich" ships as the text\'s dated, attributed stated-effect (non-fatalistic), and "respected"/"angry" are neutral traits that ship clean. No caste, gender/marriage, slavery/servitude, remedy, or death-timing content is present, so nothing is omitted, neutralised, or refused.'},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Bṛhat Jātaka 18.3',
            "gist": "Bṛhat Jātaka (18.3) reads the Sun-in-Capricorn native as earning a livelihood through trade, of a covetous bent inclined to enjoy at others' expense — and assigns them little wealth of their own.",
            "adaptation": {"classes": ['occupation', 'health'], "action": 'neutralise',
                            "note": "Occupation-status: dropped the status/moral ranking ('mean', 'ignorant', 'low articles') and kept the surviving structural theme, livelihood-via-trade (keep theme, drop ranking). Death/disease/poverty: 'of little wealth' retained as the text's dated stated-effect, framed as the text's reading ('reads as'/'assigns them') rather than fate, not financial advice. 'Covetous' and 'enjoying at others' cost' are character-disposition terms with no social-order claim, kept clean. No caste/gender/remedy content present. (Single action label 'neutralise' names the operative adaptation; the poverty theme is retained-as-stated rather than transformed.)"},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Bṛhat Jātaka 18.4',
            "gist": 'Bṛhat Jātaka assigns the Sun in Aquarius a hard material lot: the text reads the native as separated from children and from wealth, and as poor.',
            "adaptation": {"classes": ['occupation', 'health'], "action": 'omit',
                            "note": 'The character-verdict "mean" is a bare moral/status ranking (occupation-status/rank class) with no livelihood theme underneath to retain, so it is OMITTED per §5 ("keep the theme, drop the status judgement" — here there is no theme to keep). The surviving substance — "separated from children and wealth, and poor" — is death/disease/poverty content: it is NOT omitted but retained and framed as Bṛhat Jātaka\'s DATED STATED-EFFECT via "the text reads the native as…" / "assigns…", cited and dated (~550 CE per the always-visible-date principle), never as fate, prediction, or financial advice; no death-timing is present. No caste, gender/marriage value-judgement (generic-masculine "makes a man" neutralised to "the native"), servitude, remedy, or archaic-referent content present.'},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Bṛhat Jātaka 18.4',
            "gist": 'Bṛhat Jātaka 18.4 assigns the Sun in Pisces wealth through articles found in water, and reads the native as cherished and fondly indulged by a partner.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Fondled by women' neutralised to the partner-neutral 'cherished and fondly indulged by a partner' — the structural affection/indulgence principle survives, so neutralise not refuse; the gendered value-framing is dropped. 'Wealth through articles found in water' is kept as the text's dated stated-effect (water-sourced livelihood), phrased non-fatalistically ('assigns'/'reads'). The source carries no high/low status ranking, so nothing is dropped and no occupation-status adaptation applies. No caste, remedy, health, or death content."},
            "confidence": "corroborated",
        },
    },
    'moon': {
        0: {  # Aries
            "citation": 'Bṛhat Jātaka 17.1',
            "gist": 'Bṛhat Jātaka reads the native as having round red eyes, a taste for hot light food and grains; easily calmed yet passionate and capricious; a traveller, courageous and proud; chief among brothers; changeable wealth; socially likeable; capable in service; fleshless knees, bad nails, a scar on the head; dreads water.',
            "adaptation": {"classes": ['gender', 'slavery'], "action": 'neutralise; historicise',
                            "note": "'Liked by women' neutralised to socially likeable (partner-neutral). 'A good servant' historicised to service-capable, servile framing dropped. Fleshless knees / bad nails / scar on head kept as the text's dated stated description, not fate or medical advice."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Bṛhat Jātaka 17.2',
            "gist": 'Bṛhat Jātaka reads the native as handsome, with a playful walk, long thighs and face and some marks on back and face; liberal, patient, phlegmatic and firm in friendship; bears fatigue; possessing belongings; strong digestion; socially well-liked; separated from elders, kin, wealth and children; the text notes children; happy in the middle and end of life.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Begets daughters' neutralised to the progeny theme (few/some children); 'loved by women' (and 'popular') neutralised to socially well-liked. 'Possessing paraphernalia' kept as a neutral belongings theme. Separation from kin and wealth kept as the text's stated life-circumstance."},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Bṛhat Jātaka 17.3',
            "gist": 'Bṛhat Jātaka reads the native as red-eyed with curly hair, handsome limbs and a high nose; sweet-spoken and a good eater; clever in wit, human nature and gambling; a scientist versed in the classical sciences (including the erotic science); an envoy; fond of music and skilled in dancing.',
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'refuse; gloss',
                            "note": "Blanket 'fond of women' refused as a value-laden judgement on a whole sex, and 'associates with impotents' omitted as a marginalising reference to a third-gender category with no surviving neutral principle. 'Ambassador' glossed to envoy/diplomat. 'Skilled in the sexual sciences' kept as a classical domain of learning (kāma-śāstra), not a gendered verdict."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Bṛhat Jātaka 17.4',
            "gist": "Bṛhat Jātaka reads the native as walking quickly in curves, with high buttocks and a short stout neck; accommodating and amenable to kind words; good friends; drawn to the astrologer's calling; many houses; wealth waxing and waning like the Moon; fond of friends, water and gardens.",
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise; gloss',
                            "note": "'Submissive to women' neutralised to accommodating in close ties (partner-neutral). 'Astrologer' glossed as a livelihood of its time."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Bṛhat Jātaka 17.5',
            "gist": 'Bṛhat Jātaka reads the native as angry, courageous, fixed and proud, with long-lasting displeasure; high broad cheeks and coloured eyes; liberal; obedient to the mother; few children; fond of flesh, wilderness and mountains; the text notes complaints of hunger, thirst, stomach, teeth and mind.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'refuse',
                            "note": "Blanket 'hater of women' refused as a value-laden gendered judgement. 'Few children' kept as neutral progeny theme. Hunger/thirst/stomach/teeth/mind complaints kept as the text's dated stated-effect, not medical advice. Angry/proud kept verbatim (no policy class)."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Bṛhat Jātaka 17.6',
            "gist": "Bṛhat Jātaka reads the native as modest in walk and gaze, with bent shoulders and hands; happy; a sweet, truthful, calm speaker; charitable; skilled in the arts and learned in the śāstras; intelligent and passionate; possessing others' wealth and houses; a foreign residence; few children.",
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Daughters and few issue' neutralised to few children (progeny theme). 'Possessing others' wealth and houses' kept as the text's stated effect."},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Bṛhat Jātaka 17.7',
            "gist": 'Bṛhat Jātaka reads the native as devout (worshipping gods and holy persons), intelligent and clean; tall, with a long nose and weak, ill-developed organs; accommodating in close ties; a traveller; rich and skilled in commerce; bearing a divine second name; the text notes a sickly constitution; helps relations yet is coerced and rejected by them.',
            "adaptation": {"classes": ['caste', 'gender', 'archaic', 'health'], "action": 'gloss; neutralise',
                            "note": "'Worshipping gods, brahmins and the pious' glossed as piety, not a caste verdict about the native. 'Submissive to women' neutralised to accommodating in close ties. 'Clever in merchandise' glossed as skill in commerce (status ranking dropped). Weak organs / sickly kept as the text's dated stated-effect."},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Bṛhat Jātaka 17.8',
            "gist": 'Bṛhat Jātaka reads the native as broad-eyed and broad-chested, honey-coloured, with round knees, buttocks and thighs; marks of a fish, weapon and bird; cruel; a secret sinner; separated from parents and teacher; respected by those in power; the text notes sickliness in infancy.',
            "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss',
                            "note": "'Respected by royalty' glossed to respected by those in power. 'Sickly in infancy' kept as the text's dated stated-effect. 'Cruel' and 'secret sinner' kept verbatim (no policy class)."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Bṛhat Jātaka 17.9',
            "gist": 'Bṛhat Jātaka reads the native as long-faced and long-necked, with thick teeth, ears, lips and nose, bent shoulders, strong arms and bad nails; strong and highly intelligent; a clever speaker and poet; an active worker skilled in fine arts and righteous knowledge; liberal; paternal wealth; a hater of relations; won over by fair means and kind words.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "No caste, gender, or servitude clauses to adapt. Livelihood term (poet) and plain character words kept faithfully; 'bad nails' kept as the text's stated physical description."},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Bṛhat Jātaka 17.10',
            "gist": 'Bṛhat Jātaka reads the native as lean in the lower half, with good eyes and lean buttocks; grasping intelligence; popular yet idle; cannot bear cold; a traveller; strong, or a liberal, learned poet; miserly, shameless and merciless; feigns charity; pleases spouse and children.',
            "adaptation": {"classes": ['occupation', 'gender'], "action": 'omit',
                            "note": "The value-laden 'low intercourse' dropped (the low/base ranking removed). 'Pleases spouse and children' kept as a partner-neutral domestic theme. Miserly/shameless/merciless kept verbatim (no policy class)."},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Bṛhat Jātaka 17.11',
            "gist": 'Bṛhat Jātaka reads the native as having a long, camel-like neck, bulging veins and a rough, closely-haired, long body with big legs, thighs, buttocks, back, waist and face; stubborn and sinful; covetous of what belongs to others; changeable fortune; surrounded by fine flowers, scents and friends; bears fatigue on the road.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Fond of others' wealth and women' neutralised to covetousness toward what belongs to others (partner-neutral). 'Sinful' and 'stubborn' kept verbatim (no policy class)."},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Bṛhat Jātaka 17.12',
            "gist": "Bṛhat Jātaka reads the native as well-proportioned and handsome, with a prominent nose, big head and charming eyes; conquers enemies; accommodating in close ties; fond of spouse and clothes; enjoys others' wealth and aquatic articles; finds treasure-trove and lustrous articles; wealthy and learned.",
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Submissive to women' neutralised to accommodating in close ties (partner-neutral). 'Fond of spouse and clothes' kept as a partner-neutral domestic theme."},
            "confidence": "corroborated",
        },
    },
    'mars': {
        0: {  # Aries
            "citation": 'Bṛhat Jātaka 18.5',
            "gist": "Bṛhat Jātaka assigns the native honour from those in authority, a wandering life, a commander's or merchant's calling, wealth, a scarred body, and a pursuit of varied sense-pleasures.",
            "adaptation": {"classes": ['archaic', 'health', 'occupation'], "action": 'gloss; historicise; omit',
                            "note": "'kings / commander / merchant' glossed as authority, leadership and trade of their era; 'cut or scarred body' kept as the text's dated stated physical effect, not fate or medical claim; the 'thief' moral ranking omitted (no honest livelihood theme survives)."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Bṛhat Jātaka 18.5',
            "gist": 'The text reads the native as deferential in close partnership, ungrateful in friendship, drawn to attachments outside his own, deceitful, foppish, timid and unsocial.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'submissive to women' and 'fond of others' wives' neutralised to partner-neutral relational themes (deference in partnership; roving attachments); plain character words (cheat, fop, timid, unsocial) kept verbatim."},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Bṛhat Jātaka 18.6',
            "gist": "Bṛhat Jātaka assigns jealousy, offspring, friendlessness yet gratitude, skill in music and martial arts, miserliness, fearlessness, and a mendicant's life.",
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'has sons' neutralised to offspring/children; character and skill words (jealous, grateful, miserly, undaunted, clever in music/martial work) kept plainly; 'mendicant' kept as its own dated livelihood."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Bṛhat Jātaka 18.6',
            "gist": 'The text reads the native as rich through ships or travel, intelligent, deficient in some organ (its dated stated effect), and cruel.',
            "adaptation": {"classes": ['health'], "action": 'historicise',
                            "note": "'wanting in organs' kept as the text's dated stated physical effect, not medical fact or advice; 'cruel' kept unsoftened (no policy class); wealth-via-ships and intelligence kept plainly."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Bṛhat Jātaka 18.7',
            "gist": 'Bṛhat Jātaka assigns poverty (its dated stated effect), endurance, wandering in wild places, and few children and little family.',
            "adaptation": {"classes": ['health', 'gender'], "action": 'historicise; neutralise',
                            "note": "'poor' kept as the text's dated stated effect, not fate; 'few children and spouse' neutralised to a few-children / small-family theme (structural principle survives)."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Bṛhat Jātaka 18.6',
            "gist": "Bṛhat Jātaka assigns jealousy, offspring, friendlessness yet gratitude, skill in music and martial arts, miserliness, fearlessness, and a mendicant's life.",
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'has sons' neutralised to offspring/children; character and skill words (jealous, grateful, miserly, undaunted, clever in music/martial work) kept plainly; 'mendicant' kept as its own dated livelihood."},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Bṛhat Jātaka 18.5',
            "gist": 'The text reads the native as deferential in close partnership, ungrateful in friendship, drawn to attachments outside his own, deceitful, foppish, timid and unsocial.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'submissive to women' and 'fond of others' wives' neutralised to partner-neutral relational themes (deference in partnership; roving attachments); plain character words (cheat, fop, timid, unsocial) kept verbatim."},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Bṛhat Jātaka 18.5',
            "gist": "Bṛhat Jātaka assigns the native honour from those in authority, a wandering life, a commander's or merchant's calling, wealth, a scarred body, and a pursuit of varied sense-pleasures.",
            "adaptation": {"classes": ['archaic', 'health', 'occupation'], "action": 'gloss; historicise; omit',
                            "note": "'kings / commander / merchant' glossed as authority, leadership and trade of their era; 'cut or scarred body' kept as the text's dated stated physical effect, not fate or medical claim; the 'thief' moral ranking omitted (no honest livelihood theme survives)."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Bṛhat Jātaka 18.7',
            "gist": 'The text reads the native as beset by many enemies, holding high office, renowned, courageous, with few children.',
            "adaptation": {"classes": ['archaic', 'gender'], "action": 'gloss; neutralise',
                            "note": "'minister' glossed as high office / leadership of its era; 'few children' kept as a structural family theme; enemies, renown and courage kept plainly."},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Bṛhat Jātaka 18.7',
            "gist": 'Bṛhat Jātaka assigns much wealth, many children, and the standing of a ruler or his equal.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'a king or his equal' glossed as eminent authority / leadership of its era; wealth and many children kept plainly."},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Bṛhat Jātaka 18.7',
            "gist": 'The text reads the native as sorrowful, poor (its dated stated effect), a wanderer, untruthful and irritable.',
            "adaptation": {"classes": ['health'], "action": 'historicise',
                            "note": "'poor' kept as the text's dated stated effect, not fate; sorrowful, untruthful and irritable kept as plain character words carrying no policy class."},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Bṛhat Jātaka 18.7',
            "gist": 'The text reads the native as beset by many enemies, holding high office, renowned, courageous, with few children.',
            "adaptation": {"classes": ['archaic', 'gender'], "action": 'gloss; neutralise',
                            "note": "'minister' glossed as high office / leadership of its era; 'few children' kept as a structural family theme; enemies, renown and courage kept plainly."},
            "confidence": "corroborated",
        },
    },
    'mercury': {
        0: {  # Aries
            "citation": 'Bṛhat Jātaka 18.8',
            "gist": 'The text reads the native as fond of gambling, borrowing and drinking, irreligious, and given to cheating and untruth; it also states, as a dated effect not fate, poor means.',
            "adaptation": {"classes": ['occupation', 'health', 'gender'], "action": 'omit; historicise; refuse',
                            "note": "'thief' moral verdict omitted (no neutral livelihood survives); 'poor' kept as the text's dated stated-effect, cited, not fate; 'bad spouse' value-laden verdict refused; gambling/borrowing/drinking, atheism, cheating and untruth kept as plain character words."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Bṛhat Jātaka 18.8',
            "gist": 'Bṛhat Jātaka assigns a native drawn to teachers, children, household and wealth — liberal and respectful to elders.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'spouse' kept as neutral family/household acquisition alongside teachers, children and wealth; 'respectful to elders' kept as piety/character; rest clean."},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Bṛhat Jātaka 18.9',
            "gist": 'The text reads the native as prone to falsehood yet skilled in the arts and sciences, polite in speech, and fond of happiness.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "No policy clauses; 'liar' kept as a plain character word carrying no policy class."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Bṛhat Jātaka 18.9',
            "gist": 'Bṛhat Jātaka assigns wealth gained through water, and reads the native as hostile toward relations.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "No policy clauses; 'wealth through water' is a neutral livelihood theme; 'hateful to relations' kept as a plain character word."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Bṛhat Jātaka 18.10',
            "gist": 'The text states, as dated effects not fate, lack of wealth, happiness and children; it reads the native as dull-witted, a wanderer, and out of favour with his own community.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'refuse; historicise',
                            "note": "'hateful to women' and 'fond of women' — blanket gendered verdicts on a whole sex — both refused; 'without wealth, happiness and children' kept together as the text's dated stated-effects, cited, not fate; 'stupid', 'traveller', 'disgraced by community' kept as plain terms."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Bṛhat Jātaka 18.10',
            "gist": 'Bṛhat Jātaka assigns a liberal, learned native of many noble qualities — happy, patient, resourceful and intrepid.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'Wholly favourable character terms; no policy clauses.'},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Bṛhat Jātaka 18.8',
            "gist": 'Bṛhat Jātaka assigns a native drawn to teachers, children, household and wealth — liberal and respectful to elders.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "Shares 18.8 with Taurus; 'spouse' kept as neutral family/household acquisition; 'respectful to elders' kept as piety/character; rest clean."},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Bṛhat Jātaka 18.8',
            "gist": 'The text reads the native as fond of gambling, borrowing and drinking, irreligious, and given to cheating and untruth; it also states, as a dated effect not fate, poor means.',
            "adaptation": {"classes": ['occupation', 'health', 'gender'], "action": 'omit; historicise; refuse',
                            "note": "Shares 18.8 with Aries; 'thief' moral verdict omitted; 'poor' kept as the text's dated stated-effect, not fate; 'bad spouse' value-laden verdict refused; gambling/borrowing/drinking, atheism, cheating and untruth kept as plain words."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Bṛhat Jātaka 18.11',
            "gist": 'The text reads the native as respected by authority, learned, and apt in timely speech.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'respected by the king' glossed to esteem from authority/those in power of its time; 'learned' and 'timely speech' clean."},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Bṛhat Jātaka 18.11',
            "gist": "Bṛhat Jātaka reads the native as working under others' direction, indebted, and not drawn to the arts; it states poor means as a dated effect.",
            "adaptation": {"classes": ['slavery/servitude/rank', 'health'], "action": 'historicise',
                            "note": "'engaged in others' work' and 'carrying out others' orders' historicised to working under others' direction, servile framing dropped; 'poor' kept as the text's dated stated-effect, not fate; 'debtor' and 'not fond of the arts' clean."},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Bṛhat Jātaka 18.11',
            "gist": "Bṛhat Jātaka reads the native as working under others' direction, indebted, and not drawn to the arts; it states poor means as a dated effect.",
            "adaptation": {"classes": ['slavery/servitude/rank', 'health'], "action": 'historicise',
                            "note": "Shares 18.11 with Capricorn; servile 'others' work'/'others' orders' historicised to working under others' direction; 'poor' kept as the text's dated stated-effect; 'debtor' and 'not fond of the arts' clean."},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Bṛhat Jātaka 18.11',
            "gist": 'The text reads the native as able to win subordinates to his side, and as an artist by craft.',
            "adaptation": {"classes": ['slavery/servitude/rank', 'occupation'], "action": 'historicise; neutralise',
                            "note": "'winning servants over' historicised to winning subordinates/helpers to one's side, servile framing dropped; 'mean artist' — status/moral ranking dropped, the artist/craftsman livelihood kept."},
            "confidence": "corroborated",
        },
    },
    'jupiter': {
        0: {  # Aries
            "citation": 'Bṛhat Jātaka 18.12',
            "gist": 'Bṛhat Jātaka assigns the native leadership (an authority-figure of its era), a large family, children and wealth, generosity, a well-run household, a forgiving nature, a handsome form, a favourable marriage, and fame.',
            "adaptation": {"classes": ['archaic', 'slavery', 'gender'], "action": 'gloss; historicise; neutralise',
                            "note": "'Commander' glossed as leadership/authority of its era; 'good servants' historicised to a well-run household, dropping the servile framing; 'a good spouse' neutralised to a favourable marriage (the value verdict on the partner dropped, marriage indication kept). Remaining clauses (family, children, wealth, liberal, forgiving, handsome, famous) clean."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Bṛhat Jātaka 18.12',
            "gist": 'Bṛhat Jātaka assigns the native health, happiness, friends, wealth and children, generosity, and popularity.',
            "adaptation": {"classes": ['else'], "action": 'clean',
                            "note": 'No caste/gender/servitude/status clauses; kept faithful and terse.'},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Bṛhat Jātaka 18.12',
            "gist": "Bṛhat Jātaka assigns the native worldly means or titles, children and friends, high office (minister/consul, in its era's terms), and happiness.",
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'Minister' and 'consul' glossed as high office/leadership of its time; paraphernalia/titles, children, friends and happiness clean."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Bṛhat Jātaka 18.13',
            "gist": 'Bṛhat Jātaka assigns the native great wealth and gems, children, marriage, enjoyment, intelligence, and happiness.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Spouse' kept as a neutral marriage indication (no value verdict to refuse). Wealth, gems, children, enjoyment, intelligence, happiness clean."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Bṛhat Jātaka 18.13',
            "gist": 'Bṛhat Jātaka assigns the native leadership (of its era) and, as in Cancer, great wealth, gems, children, marriage, enjoyment, intelligence, and happiness.',
            "adaptation": {"classes": ['archaic', 'gender'], "action": 'gloss; neutralise',
                            "note": "'Commander' glossed as leadership/authority of its era; 'spouse' kept as a neutral marriage indication. The repeated Cancer results (wealth, gems, children, enjoyment, intelligence, happiness) clean; the source's own cross-reference to Cancer preserved."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Bṛhat Jātaka 18.12',
            "gist": "Bṛhat Jātaka assigns the native worldly means or titles, children and friends, high office (minister/consul, in its era's terms), and happiness.",
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "Same reading as Gemini: 'minister' and 'consul' glossed as high office/leadership of its time; paraphernalia/titles, children, friends and happiness clean."},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Bṛhat Jātaka 18.12',
            "gist": 'Bṛhat Jātaka assigns the native health, happiness, friends, wealth and children, generosity, and popularity.',
            "adaptation": {"classes": ['else'], "action": 'clean',
                            "note": 'Same reading as Taurus; no caste/gender/servitude/status clauses; kept faithful and terse.'},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Bṛhat Jātaka 18.12',
            "gist": 'Bṛhat Jātaka assigns the native leadership (an authority-figure of its era), a large family, children and wealth, generosity, a well-run household, a forgiving nature, a handsome form, a favourable marriage, and fame.',
            "adaptation": {"classes": ['archaic', 'slavery', 'gender'], "action": 'gloss; historicise; neutralise',
                            "note": "Same reading as Aries: 'commander' glossed as leadership of its era; 'good servants' historicised to a well-run household; 'a good spouse' neutralised to a favourable marriage. Rest clean."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Bṛhat Jātaka 18.13',
            "gist": "Bṛhat Jātaka assigns the native high authority or office (king/minister/commander, in its era's terms) or wealth.",
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'King/minister/commander' glossed as high authority or office of its time; 'wealthy' clean."},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Bṛhat Jātaka 18.13',
            "gist": "Bṛhat Jātaka reads the native as mean, poor, and unhappy — the text's dated stated effect (Jupiter debilitated), cited, not a fate.",
            "adaptation": {"classes": ['health', 'else'], "action": 'historicise; clean',
                            "note": "'Poor' kept as the text's dated stated effect for Jupiter's debilitation (fall in Capricorn), cited, not fate and not medical/financial advice. 'Mean' and 'unhappy' kept as plain character words, not softened — and not amplified into an occupation/status ranking, since no trade is named."},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Bṛhat Jātaka 18.13',
            "gist": 'Bṛhat Jātaka assigns the native great wealth and gems, children, marriage, enjoyment, intelligence, and happiness.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "Same reading as Cancer: 'spouse' kept as a neutral marriage indication; wealth, gems, children, enjoyment, intelligence, happiness clean."},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Bṛhat Jātaka 18.13',
            "gist": "Bṛhat Jātaka assigns the native high authority or office (king/minister/commander, in its era's terms) or wealth.",
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "Same reading as Sagittarius: 'king/minister/commander' glossed as high authority or office of its time; 'wealthy' clean."},
            "confidence": "corroborated",
        },
    },
    'venus': {
        0: {  # Aries
            "citation": 'Bṛhat Jātaka 18.14',
            "gist": 'Bṛhat Jātaka reads the native as drawn to attachments outside the home that drain money through flattery, and a hater of his own kin.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "BJ 18.14. 'Fond of other women' neutralised to attachments outside the home; the surviving structural principle (money lost through flattery) kept. In 'hater of his own race' the plain trait 'hater' is kept unsoftened (no policy class), and the ambiguous 'race' is glossed to his own kin/people — not a caste verdict."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Bṛhat Jātaka 18.14',
            "gist": 'The text reads the native as holding self-earned property, esteemed by those in authority, a leader of his people, renowned and courageous.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "BJ 18.14. 'Respected by rulers' glossed to those in authority; 'leader of his men' kept as leadership. Wealth/renown/courage clean."},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Bṛhat Jātaka 18.15',
            "gist": 'Bṛhat Jātaka assigns the native the work or service of those in authority, wealthy and learned.',
            "adaptation": {"classes": ['archaic', 'slavery-servitude'], "action": 'gloss',
                            "note": "BJ 18.15. 'Rulers' work or service' glossed: rulers → those in authority, service kept as neutral employment/livelihood. Wealthy and learned clean."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Bṛhat Jātaka 18.16',
            "gist": 'The text reads the native as marrying more than once, living as a mendicant, timid, and stirred by passion that brings sorrow.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "BJ 18.16. 'Two spouses' neutralised to more than one marriage. Mendicant, timidity, and passion-bringing-sorrow kept as plain terse traits."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Bṛhat Jātaka 18.16',
            "gist": 'Bṛhat Jātaka assigns the native wealth gained through a partner, with few children.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "BJ 18.16. 'Wealth through a woman' neutralised to wealth through a partner (structural principle survives); 'few children' kept. The spouse's-looks verdict ('handsome spouse') refused as a value-laden gendered judgement."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Bṛhat Jātaka 18.15',
            "gist": 'The text reads the native as given to humble or menial undertakings.',
            "adaptation": {"classes": ['occupation'], "action": 'neutralise',
                            "note": "BJ 18.15. 'Doing very mean acts' — the base-activity theme kept, the moral/status ranking ('very mean') dropped/softened to humble or menial undertakings."},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Bṛhat Jātaka 18.14',
            "gist": 'The text reads the native as holding self-earned property, esteemed by those in authority, a leader of his people, renowned and courageous.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "BJ 18.14 (same reading as Taurus). 'Respected by rulers' glossed to those in authority; leadership kept; wealth/renown/courage clean."},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Bṛhat Jātaka 18.14',
            "gist": 'Bṛhat Jātaka reads the native as drawn to attachments outside the home that drain money through flattery, and a hater of his own kin.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "BJ 18.14 (same reading as Aries). 'Fond of other women' neutralised to attachments outside the home; money-lost-through-flattery kept. In 'hater of his own race' the plain trait 'hater' is kept unsoftened, and 'race' is glossed to his own kin/people, not a caste verdict."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Bṛhat Jātaka 18.16',
            "gist": 'The text reads the native as adorned with many good qualities and rich.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'BJ 18.16. No policy class engaged; character and wealth themes kept faithfully.'},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Bṛhat Jātaka 18.15',
            "gist": 'Bṛhat Jātaka reads the native as popular, ruled by passion, and keeping disreputable company.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "BJ 18.15. 'Popular' clean. 'Enslaved to women' neutralised to ruled by passion/attachment; 'intercourse with bad women' neutralised to disreputable company, refusing the value-laden gendered verdict on the women's character."},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Bṛhat Jātaka 18.15',
            "gist": 'Bṛhat Jātaka reads the native as popular, ruled by passion, and keeping disreputable company.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "BJ 18.15 (same reading as Capricorn). 'Enslaved to women' neutralised to ruled by passion; 'intercourse with bad women' neutralised to disreputable company, refusing the value-laden gendered judgement."},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Bṛhat Jātaka 18.16',
            "gist": 'The text reads the native as learned, wealthy, esteemed by those in authority, and very popular.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "BJ 18.16. 'Respected by rulers' glossed to those in authority; learned/wealthy/popular clean."},
            "confidence": "corroborated",
        },
    },
    'saturn': {
        0: {  # Aries
            "citation": 'Bṛhat Jātaka 18.17',
            "gist": 'Bṛhat Jātaka assigns an ignorant, wandering, deceitful and friendless nature.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "All plain character/travel words ('ignorant', 'itinerant', 'a cheat', 'friendless'); nothing triggers a policy class — kept faithfully and terse."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Bṛhat Jātaka 18.17',
            "gist": 'Bṛhat Jātaka assigns ordinary wealth and multiple marriages.',
            "adaptation": {"classes": ['caste', 'gender'], "action": 'omit+neutralise',
                            "note": "Caste verdict ('prohibited and low-caste women') omitted and its value-laden gendered framing refused; 'many spouses' neutralised to multiple partnerships (structural plurality survives); 'ordinary wealth' kept clean."},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Bṛhat Jātaka 18.17',
            "gist": "Bṛhat Jātaka assigns childlessness, poverty (the text's dated stated effect), a shameless and unhappy nature, and no skill in painting, yet a protective official and community chief (variant readings: skilled in painting; or of a 'Rākṣasa' path).",
            "adaptation": {"classes": ['gender', 'health', 'archaic', 'occupation'], "action": 'gloss+keep-cited',
                            "note": "'Poor' kept as the text's dated stated-effect, not fate; 'protective officer and chief man' glossed as authority/leadership of its time; childlessness rendered neutral; painting-skill kept as livelihood theme; variant readings preserved."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Bṛhat Jātaka 18.18',
            "gist": "Bṛhat Jātaka assigns poverty and loose teeth (the text's dated stated effects), loss of the mother, childlessness and an unlearned nature.",
            "adaptation": {"classes": ['health', 'gender'], "action": 'keep-cited',
                            "note": "'Poor' and 'loose teeth' kept as the text's dated stated-effects — cited, not fate, not medical advice; 'motherless' rendered as loss of/separation from the mother, not a death-timing claim; childlessness neutral."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Bṛhat Jātaka 18.18',
            "gist": 'Bṛhat Jātaka assigns an ill-natured, unhappy and childless native given to burdensome labour.',
            "adaptation": {"classes": ['slavery-servitude', 'gender'], "action": 'historicise',
                            "note": "'Carrying loads' historicised to burdensome/laboring work, servile framing dropped; childlessness neutral; 'bad' and 'unhappy' kept as plain words."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Bṛhat Jātaka 18.17',
            "gist": "Bṛhat Jātaka assigns childlessness, poverty (the text's dated stated effect), a shameless and unhappy nature, and no skill in painting, yet a protective official and community chief (variant readings: skilled in painting; or of a 'Rākṣasa' path).",
            "adaptation": {"classes": ['gender', 'health', 'archaic', 'occupation'], "action": 'gloss+keep-cited',
                            "note": "Same clause-set as Gemini: 'poor' kept as dated stated-effect not fate; 'protective officer and chief man' glossed as authority of its time; childlessness neutral; painting-skill kept as livelihood; variants preserved."},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Bṛhat Jātaka 18.18',
            "gist": 'Bṛhat Jātaka assigns fame, wealth and respect across community, town, army and village.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'Army and villages' glossed as respect across the community and institutions of its time; 'famous' and 'wealthy' kept clean."},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Bṛhat Jātaka 18.17',
            "gist": "Bṛhat Jātaka assigns risk of imprisonment and corporal punishment (the text's dated stated effects) and a capricious, merciless nature.",
            "adaptation": {"classes": ['archaic', 'health'], "action": 'historicise+keep-cited',
                            "note": "'Imprisonment' and 'whipping' historicised and kept as the text's dated adverse stated-effects, not fate; 'capricious' and 'merciless' kept as plain character words."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Bṛhat Jātaka 18.19',
            "gist": 'Bṛhat Jātaka assigns a dignified end, trusted standing with rulers, family and wealth, and leadership over town, army and village.',
            "adaptation": {"classes": ['health', 'archaic', 'gender'], "action": 'historicise+gloss+neutralise',
                            "note": "'A good death' historicised to a dignified end / happy conclusion (general statement, not death-timing); 'confidant of princes/rulers' and 'commander of towns, armies and villages' glossed as authority/leadership of its time; value-laden 'good spouse' verdict neutralised into family-and-wealth."},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Bṛhat Jātaka 18.19',
            "gist": "Bṛhat Jātaka assigns gain of others' wealth and houses, leadership over town, village and army, weak eyesight (the text's dated stated effect), an unclean habit, and lasting wealth, prosperity and enjoyment.",
            "adaptation": {"classes": ['gender', 'archaic', 'health'], "action": 'neutralise+gloss+keep-cited',
                            "note": "Gendered 'others' women' dropped, the acquisition-of-others'-property theme (wealth and houses) kept; 'chief of towns, villages and army' glossed as leadership; 'short-sighted' kept as the text's dated physical effect, not medical advice; 'dirty' kept as a plain descriptor."},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Bṛhat Jātaka 18.19',
            "gist": "Bṛhat Jātaka assigns gain of others' wealth and houses, leadership over town, village and army, weak eyesight (the text's dated stated effect), an unclean habit, and lasting wealth, prosperity and enjoyment.",
            "adaptation": {"classes": ['gender', 'archaic', 'health'], "action": 'neutralise+gloss+keep-cited',
                            "note": "Same clause-set as Capricorn: 'others' women' dropped, property-acquisition theme kept; 'chief of...army' glossed as leadership; 'short-sighted' kept as dated stated-effect; 'dirty' plain."},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Bṛhat Jātaka 18.19',
            "gist": 'Bṛhat Jātaka assigns a dignified end, trusted standing with rulers, family and wealth, and leadership over town, army and village.',
            "adaptation": {"classes": ['health', 'archaic', 'gender'], "action": 'historicise+gloss+neutralise',
                            "note": "Same clause-set as Sagittarius: 'a good death' historicised to a dignified end (not death-timing); 'confidant of princes'/'commander' glossed as authority of its time; 'good spouse' verdict neutralised into family-and-wealth."},
            "confidence": "corroborated",
        },
    },
}


# graha key -> bhāva (1-12) -> entry (planet-in-house, Ch.30/20/Adh.8 etc.).
IN_HOUSE = {
    'sun': {
        1: {  # 1st
            "citation": 'Bṛhat Jātaka 20.1',
            "gist": "Brihat reads a native with the Sun in the 1st bhava as valiant, obstinate and cruel-hearted, and as having defective or diseased eyes - the last kept as the text's own dated bodily reading, cited and framed as the classical view, not fate or medical advice. Its sign-conditional variants sharpen the same eye theme (self-earning yet eye-disease under an Aries ascendant, night-blindness under Leo, inflamed eyes under Cancer, and under Libra blindness together with poverty).",
            "adaptation": {"classes": ['health'], "action": 'keep-as-dated-effect; keep-clean',
                            "note": "'Defective eyes' kept as the text's dated bodily stated-effect, cited, framed as the classical view and not a prediction or medical advice; the sign variants (eye-disease, night-blindness, inflamed eyes, and the Libra 'blind and poor' reading) kept faithfully as dated stated-effects with the plainly-named blindness and poverty NOT softened; clean character words valiant, obstinate and cruel-hearted shipped plainly and unsoftened."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Bṛhat Jātaka 20.1',
            "gist": "The text reads a native with the Sun in the 2nd bhava as immensely rich yet stripped of that wealth by a king - read in context as a ruling authority of its day - and as afflicted by diseases of the face, the affliction kept as the source's own dated bodily view, cited, not fate or medical advice.",
            "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss; keep-as-dated-effect',
                            "note": "'A king' GLOSSED in context as the ruling/sovereign authority of its time rather than left as a bare archaic referent; 'diseases in the face' KEPT as the text's dated bodily stated-effect, cited and framed as the classical view, with a not-medical-advice sense; the wealth-then-loss theme shipped plainly."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Bṛhat Jātaka 20.2',
            "gist": 'Brihat reads a native with the Sun in the 3rd bhava as possessed of good intellect and great strength.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content in the source; the clean traits good intellect and great strength shipped plainly and faithfully.'},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Bṛhat Jātaka 20.2',
            "gist": 'The text reads a native with the Sun in the 4th bhava as without happiness and troubled in mind.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social class content; the plain traits of unhappiness and a troubled mind shipped faithfully and unsoftened.'},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Bṛhat Jātaka 20.2',
            "gist": "Brihat reads a native with the Sun in the 5th bhava as without wealth and as strained in the sphere of progeny - the source's 'childless' clause kept progeny-neutrally, as difficulty in that sphere rather than a prediction of childlessness.",
            "adaptation": {"classes": ['gender'], "action": 'neutralise; keep-clean',
                            "note": "'Childless' NEUTRALISED to a progeny-neutral strain in the sphere of children, not reproduced as a bare fated verdict of childlessness; the clean 'without wealth' clause shipped plainly."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Bṛhat Jātaka 20.2',
            "gist": 'The text reads a native with the Sun in the 6th bhava as powerful yet overpowered by his enemies.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social class content; the plain traits of power and of being overpowered by enemies shipped faithfully.'},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Bṛhat Jātaka 20.3',
            "gist": "The text reads a native with the Sun in the 7th bhava as suffering humiliation in dealings with a partner - the source's gendered framing neutralised to partner-neutral humiliation, not a verdict on women as a category.",
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Humiliation at the hands of women' NEUTRALISED to partner-neutral humiliation in relationship dealings, the gendered category dropped rather than reproduced as a judgement about women; the surviving humiliation theme kept plainly."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Bṛhat Jātaka 20.3',
            "gist": "Brihat reads a native with the Sun in the 8th bhava as strained in the sphere of progeny and as having defective eyesight - the 'limited issue' clause kept progeny-neutrally, and the eyesight clause kept as the text's own dated bodily stated-effect, cited, not fate or medical advice.",
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise; keep-as-dated-effect',
                            "note": "'A limited number of issues' NEUTRALISED to a progeny-neutral strain in the sphere of children rather than a counted-sons verdict; 'defective eyesight' KEPT as the text's dated bodily stated-effect, cited and framed as the classical view, not a prediction or medical advice."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Bṛhat Jātaka 20.3',
            "gist": "The text reads a native with the Sun in the 9th bhava as blessed with wealth and happiness and as favoured in the sphere of progeny - the source's 'children' clause kept progeny-neutrally as a favourable sphere rather than a counted-offspring promise.",
            "adaptation": {"classes": ['gender'], "action": 'neutralise; keep-clean',
                            "note": "'Endowed with children' NEUTRALISED to a progeny-neutral favourable sphere, not reproduced as a counted-offspring verdict; the clean traits wealth and happiness shipped plainly."},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Bṛhat Jātaka 20.3',
            "gist": 'The text reads a native with the Sun in the 10th bhava as happy and powerful.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social class content; the plain traits happy and powerful shipped faithfully.'},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Bṛhat Jātaka 20.3',
            "gist": 'Brihat reads a native with the Sun in the 11th bhava as wealthy.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social class content; the plain trait of wealth shipped faithfully.'},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Bṛhat Jātaka 20.3',
            "gist": 'The text reads a native with the Sun in the 12th bhava as suffering degradation and downfall.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social class content; the plain theme of degradation/downfall shipped faithfully and unsoftened.'},
            "confidence": "corroborated",
        },
    },
    'moon': {
        1: {  # 1st
            "citation": 'Bṛhat Jātaka 20.4',
            "gist": "Brihat reads a native with the Moon in the 1st bhava as mute, deaf, blind, insane, stupid, base and mean — the sensory and mental afflictions kept as the text's dated bodily readings, cited, not fate or medical advice; the alternative 'servile' rendering it treats as a life of service rather than a servile rank. Where the Ascendant is Aries, Taurus or Cancer, or the Moon holds its own sign there, the verse turns the result to wealth instead.",
            "adaptation": {"classes": ['health', 'slavery'], "action": 'keep-as-dated-effect; historicise; keep-clean',
                            "note": "'Mute / deaf / blind / insane' kept as the text's dated bodily-and-mental stated-effects, cited, framed as the classical view and not fate or medical advice; 'servile' (offered as the alternative to 'deaf') HISTORICISED to a life of service, the servile ranking dropped; clean words stupid, base, mean shipped plainly and unsoftened; the sign-conditional wealth variant is noted from the source itself, not invented."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Bṛhat Jātaka 20.4',
            "gist": 'The text reads a native with the Moon in the 2nd bhava simply as a man of a large family.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "A plain, dated reading with no social-status, gender or bodily content requiring adaptation; 'a man of large family' shipped plainly. 'Large family' is a household-size reading, not a son-count or fertility verdict, so no progeny neutralisation applies and classes are empty."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Bṛhat Jātaka 20.4',
            "gist": 'Brihat reads a native with the Moon in the 3rd bhava as cruel.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'Cruel' is a clean character word carrying no policy class; kept plainly and faithfully, unsoftened."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Bṛhat Jātaka 20.4',
            "gist": 'The text reads a native with the Moon in the 4th bhava as happy.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "A plain positive trait with no dated social content; 'happy' shipped plainly, classes empty."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Bṛhat Jātaka 20.4',
            "gist": 'Brihat reads a native with the Moon in the 5th bhava as blessed with children.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'Has children' kept plainly as an offspring/progeny theme; it is already progeny-neutral — no son-count, 'many sons' or 'barren' judgement — so no neutralisation is required and no gender class attaches."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Bṛhat Jātaka 20.4',
            "gist": "The text reads a native with the Moon in the 6th bhava as beset by many enemies, of a delicate constitution and weak digestion, of feeble sexual vigour, harsh in temperament and indolent in his work — the bodily frailties kept as the text's dated stated-effects, cited, framed as the classical view and not medical advice.",
            "adaptation": {"classes": ['health'], "action": 'keep-as-dated-effect; keep-clean',
                            "note": "'Delicate constitution / weak digestion / feeble sexual vigour' all kept as the text's dated bodily/constitutional stated-effects, cited, framed as the classical view and not medical advice — 'feeble sexual vigour' is a plainly-phrased constitutional frailty parallel to 'weak digestion', NOT an impotence/eunuch identity verdict, so it is not refused and carries no gender class; clean words many enemies, harsh temperament and indolent shipped plainly and unsoftened."},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Bṛhat Jātaka 20.5',
            "gist": 'Brihat reads a native with the Moon in the 7th bhava as envious and exceedingly amorous, given greatly to love.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'Envious' is a clean character word, kept plainly; 'exceedingly in love' names no gendered category and is already partner-neutral, kept as an amorous disposition, so no gender neutralisation or class is required."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Bṛhat Jātaka 20.5',
            "gist": "The text reads a native with the Moon in the 8th bhava as of a fickle mind and subject to diseases — the affliction kept as the text's dated stated-effect, cited, not medical advice.",
            "adaptation": {"classes": ['health'], "action": 'keep-as-dated-effect; keep-clean',
                            "note": "'Suffers from diseases' kept as the text's dated stated-effect, cited, framed as the classical view and not medical advice; the clean trait 'fickle mind' shipped plainly."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Bṛhat Jātaka 20.5',
            "gist": 'Brihat reads a native with the Moon in the 9th bhava as possessed of progeny, friends, kin and wealth.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise; keep-clean',
                            "note": "'Possesses sons' NEUTRALISED to progeny-neutral 'progeny/children', the son-specific gendering dropped; friends, relations and wealth kept plainly."},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Bṛhat Jātaka 20.5',
            "gist": 'The text reads a native with the Moon in the 10th bhava as one who completes to perfection whatever he undertakes, endowed with virtue, wealth, intellect and valour.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'A wholly positive, dated reading with no social-status, gender or bodily content; all traits shipped plainly, classes empty.'},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Bṛhat Jātaka 20.5',
            "gist": 'Brihat reads a native with the Moon in the 11th bhava as famous and a gainer of wealth.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "Plain positive traits with no dated social content; 'famous' and 'acquires wealth' shipped plainly, classes empty."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Bṛhat Jātaka 20.5',
            "gist": "The text reads a native with the Moon in the 12th bhava as wickedly disposed and defective in some limb — the bodily defect kept as the text's dated stated-effect, cited, not fate or medical advice.",
            "adaptation": {"classes": ['health'], "action": 'keep-as-dated-effect; keep-clean',
                            "note": "'Defective in some limb' kept as the text's dated bodily stated-effect, cited, framed as the classical view and not fate or medical advice; the clean phrase 'wickedly disposed' shipped plainly and unsoftened."},
            "confidence": "corroborated",
        },
    },
    'mars': {
        1: {  # 1st
            "citation": 'Bṛhat Jātaka 20.6',
            "gist": "Brihat reads a native with Mars in the 1st bhava as one who will have an injured limb - a hurt or injury to a limb. This is kept as the text's own dated bodily stated-effect, cited and framed as the classical view, not as the native's fate and not as medical advice.",
            "adaptation": {"classes": ['health'], "action": 'keep-as-dated-effect',
                            "note": "'Will have an injured limb' KEPT as the text's dated bodily stated-effect, cited, framed as the classical reading and explicitly not fate or medical advice; it names a plain bodily condition (an injury to a limb), so it is retained rather than refused, with the not-a-prediction / not-medical framing. The rendering stays faithful to 'injured' and does not escalate it to 'maimed'. No caste, gender, servile, occupational or archaic content is present."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Bṛhat Jātaka 20.6',
            "gist": "Brihat reads a native with Mars in the 2nd bhava as one who eats bad food. The plain reading is shipped faithfully as the text's own stated effect, cited and attributed as the classical view rather than the native's fate.",
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'Eats bad food' is a plain descriptive reading carrying no caste, gender, servile, occupational, health-disease or archaic social ranking, so it is shipped plainly and faithfully; classes = [] and action = clean. Nothing is neutralised, glossed, historicised or refused."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Bṛhat Jātaka 20.6',
            "gist": "Brihat reads a native with Mars in the 9th bhava as one who commits sinful actions. The clean moral word is kept plainly and faithfully as the text's own dated stated-effect, cited and attributed as the classical view, not asserted as the native's fate.",
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'Commits sinful actions' uses the clean moral word 'sinful', which carries no policy class and is not softened; it is shipped plainly and faithfully as the text's stated effect. No caste, gender, servile, occupational, health or archaic content is present, so classes = [] and action = clean."},
            "confidence": "corroborated",
        },
    },
    'jupiter': {
        1: {  # 1st
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 1st bhava as learned.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "Single clean trait 'learned' shipped plainly; no caste, gender, slavery, occupation-status, health, or archaic content to adapt."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 2nd bhava as eloquent and sweet-tongued.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "Clean traits 'eloquent' and 'sweet-tongued' shipped plainly; no dated social content requiring refuse/neutralise/gloss/historicise."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 3rd bhava as stingy.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'Stingy' is a clean character word (miser-class) carrying no policy class; kept plainly and unsoftened per the clean-word rule."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 4th bhava as happy.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "Single clean trait 'happy' shipped plainly; no caste, gender, slavery, occupation, health, or archaic content present."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 5th bhava as intelligent.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "Clean trait 'intelligent' shipped plainly; nothing dated to adapt."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 6th bhava as without enemies.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'Without enemies' is a plain benefic reading with no dated social content; shipped faithfully."},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 7th bhava as one who excels his father in good qualities.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'Excels his father in good qualities' is a plain comparative merit reading, not a caste verdict on the native nor an archaic referent; kept faithfully."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 8th bhava as base.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'Base' is an enumerated clean character word carrying no policy class (it is a character judgement, not an occupation-status ranking on a livelihood); kept plainly and unsoftened."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": "Brihat reads a native with Jupiter in the 9th bhava as devout and philosophical -- a devotional, god-revering disposition, shown as the text's dated view with a historical-context gloss, never as the reader's own fate.",
            "adaptation": {"classes": ['caste'], "action": 'gloss',
                            "note": "'Devout' denotes reverence toward the divine, which Section 5 handles under the caste bullet's reverence-toward-gods clause: gloss and keep with the historical-context badge (this reflects the devotional social world of its time, ~550 CE), tag caste. It is NOT shipped as a plain clean word. 'Philosophical' is retained as the accompanying disposition; the whole is framed as Brihat's dated reading, not the user's fate."},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 10th bhava as wealthy.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "Single clean trait 'wealthy' shipped plainly; no dated social content to adapt."},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 11th bhava as prosperous, a gainer making large profits.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "Clean gain traits 'prosperous', 'a gainer', 'making large profits' shipped plainly; no caste, gender, slavery, occupation-status, health, or archaic content present."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Bṛhat Jātaka 20.7',
            "gist": 'Brihat reads a native with Jupiter in the 12th bhava as a villain.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'A villain' is a plain clean character judgement (wicked-class) carrying no policy class; kept plainly and unsoftened per the clean-word rule."},
            "confidence": "corroborated",
        },
    },
    'venus': {
        1: {  # 1st
            "citation": 'Bṛhat Jātaka 20.8',
            "gist": "Brihat reads a native with Venus in the 1st bhava as skilled and practised in amorous pleasures and happy. That amorous inclination is rendered partner-neutrally as the native's own disposition, and the plain trait happy is shipped as the text states it.",
            "adaptation": {"classes": ['gender'], "action": 'neutralise; keep-clean',
                            "note": "'Skilled in amorous sports' is the native's OWN amorous conduct, so it is kept partner-neutral (no category of partner is judged or introduced) per section-5(b); 'happy' is a clean trait carrying no policy class and is shipped plainly and faithfully."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Bṛhat Jātaka 20.8',
            "gist": 'Brihat reads a native with Venus in the 5th bhava simply as happy.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "The single stated effect 'happy' is a clean word with no dated social content, so classes = [] and the reading is shipped plainly and faithfully as the text's own dated view."},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Bṛhat Jātaka 20.8',
            "gist": "Brihat reads a native with Venus in the 7th bhava as one who promotes quarrels and is strongly drawn to sexual union - the quarrelsome trait kept plainly, and the amorous inclination rendered partner-neutrally as the native's own disposition.",
            "adaptation": {"classes": ['gender'], "action": 'neutralise; keep-clean',
                            "note": "'Fond of sexual union' is the native's OWN gendered/amorous conduct and is NEUTRALISED to a partner-neutral inclination per section-5(b), naming or judging no partner; 'promotes quarrels' is a clean trait with no policy class and is kept plainly and faithfully."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Bṛhat Jātaka 20.8',
            "gist": 'Brihat reads a native with Venus in the 12th bhava simply as rich.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "The single stated effect 'rich' carries no dated social content and no policy class, so classes = [] and it is shipped plainly and faithfully as the text's own dated view."},
            "confidence": "corroborated",
        },
    },
    'saturn': {
        1: {  # 1st
            "citation": 'Bṛhat Jātaka 20.9',
            "gist": 'Brihat reads a native with Saturn in the 1st bhava as poor and sickly (a dated poverty-and-disease reading, not medical advice), love-stricken, very unclean, afflicted by diseases in childhood, and indistinct in speech. The text adds a sign-conditional turn: with Sagittarius, Pisces, Aquarius, Capricorn or Libra rising it reverses course, likening the native instead to a king, a village headman or a city mayor (figures of authority and civic leadership), a great scholar, and handsome.',
            "adaptation": {"classes": ['health', 'archaic'], "action": 'keep-as-dated-effect; gloss; keep-clean',
                            "note": "'Poor', 'sickly' and 'suffering from diseases during childhood' KEPT as the text's own dated stated-effect on poverty and disease, cited and framed as the classical view, not fate and not medical advice (tag health). The sign-variant referents 'equal to a king', 'headman of a village' and 'mayor of a city' GLOSSED in context as figures of authority and civic leadership and kept (tag archaic); the variant is noted, not invented beyond the source. Clean words 'very unclean', 'love-stricken', 'indistinct in speech', 'great scholar' and 'handsome' shipped plainly and faithfully. No caste, gender, slavery or occupation-status content required refusal or neutralisation here."},
            "confidence": "corroborated",
        },
    },
}
