"""
Chamatkāra Cintāmaṇi of Bhaṭṭa Nārāyaṇa — CLASSICAL tier, PLANET-IN-HOUSE only.

A text devoted to the bhāva-phala: each graha (including Rāhu and Ketu) in the 12
bhāvas. Site-authored, cited, §5-adapted GISTs rendered from the 1886 edition's
English, extracted from the raw text and adversarially verified against it. The
OCR is partial, so coverage is uneven (present cells only; no cell is invented).
"""
SOURCE = {
    "id": "chamatkara", "text": "Chamatkāra Cintāmaṇi", "author": "Bhaṭṭa Nārāyaṇa",
    "date": "medieval", "translator": "from the 1886 edition (site-rendered)",
    "tier": "classical",
}


# graha key -> bhāva (1-12) -> entry (planet-in-house; partial where OCR is).
IN_HOUSE = {
    'sun': {
        1: {  # 1st
            "citation": 'Chamatkāra Cintāmaṇi §1',
            "gist": 'Chamatkara reads a native with the sun in the first bhava (Tanu, the rising sign) as tall, bold, modest, studious and diligent, with striking eyes and a well-placed standing, and drawn to performance as an actor; the text also states strain in family and marital ties, a cruel streak, poor appetite, weak eyesight, biliousness, no progeny, and financial ups and downs while abroad.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "Spouse/family-distress and 'issueless' rendered partner- and progeny-neutral per section 5(b)/(c). Biliousness, poor appetite and defective sight kept as the text's own dated stated-effects, cited as the classical view, not a prediction and not medical advice. 'Cruel' is a clean character word, kept plainly."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Chamatkāra Cintāmaṇi §2',
            "gist": 'Chamatkara reads a native with the sun in the second bhava (Dhana) as fortunate, gaining the comfort of livestock and conveyance, spending profitably, charitable and wealthy, one who overcomes rivals through conduct and speaks sweetly and logically; the same text also states domestic disputes touching the marriage, setbacks in investment, and a countervailing side that is unlearned, discourteous, haughty, vain, not truly rich, and troubled by a stammer.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "Family dispute framed around the wife rendered spouse-neutral per section 5(b). Stammering kept as the text's dated stated speech-condition, cited as the classical view, not medical advice. 'Haughty' and 'vain' are clean words, kept plainly."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Chamatkāra Cintāmaṇi §3',
            "gist": 'Chamatkara reads a native with the sun in the third bhava (Tritiya) as very strong and glorious, healthy, wealthy and wise, famous, kind and modest, one who rises to authority and is recognised by the state, who travels abroad and later goes on pilgrimage, and who prevails over rivals; the text also states discord with his own brothers, and states this placement to be harmful (maraka) for the elder brother.',
            "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss',
                            "note": "'Recognised by the state' and 'a king' glossed as authority/leadership of that era per section-5 archaic handling, and kept. The maraka clause toward the elder brother kept only as the text's own dated view, cited as the classical reading, explicitly not a prediction."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Chamatkāra Cintāmaṇi §4',
            "gist": 'Chamatkara reads a native with the sun in the fourth bhava as holding a respected line of work yet beset by strife with family and friends, mostly living abroad, feeling slighted by adversaries and inwardly at war, and so remaining tense; the text further states heart trouble, poverty and want, calls the native foolish and cruel, and judges the placement inauspicious.',
            "adaptation": {"classes": ['occupation', 'health'], "action": 'keep',
                            "note": "The 'honourable occupation' ranking is glossed to keep the livelihood theme without the moral rank per section-5 occupation handling. Heart trouble, poverty and starvation kept as the text's own dated stated-effects, cited as the classical view, not a prediction and not medical advice. 'Foolish' and 'cruel' are clean words, kept plainly."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Chamatkāra Cintāmaṇi §5',
            "gist": 'Chamatkara reads a native with the sun in the fifth bhava as sharp and intelligent, learned in mantra-lore, and inclined to hoard wealth, yet careless and negligent and given to cheating others; the text also states hardship through the eldest child, want and wandering over hills and forests, and names chest pain as the stated cause of death.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "Suffering 'at the hands of the first son' and 'childless' rendered progeny-neutral per section 5(c). Poverty and the chest-pain death-cause kept as the text's own dated stated-effects, cited as the classical view, explicitly not a prediction and not medical advice. 'Cheating', 'careless' and 'negligent' are clean words, kept plainly."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Chamatkāra Cintāmaṇi §6',
            "gist": "Chamatkara reads a native with the sun in the sixth bhava (Shatru) as a powerful vanquisher of enemies and a loyal friend, strong, happy, rich and respected, rising to positions of command; the text also states loss through cattle, danger from a sharp-horned animal, and being set upon by robbers or hostile groups while travelling, and calls the maternal uncle's side of the family ill-favoured by this placement.",
            "adaptation": {"classes": ['archaic', 'gender'], "action": 'gloss',
                            "note": "'King, general or judge' glossed as authority/leadership roles of that era per section-5 archaic handling, and kept. Native's 'passionate/lustful' conduct rendered neutral per section 5(b); the commentary clause making the maternal aunt a widow or issueless (a verdict on a woman) is refused per section 5(a). Harm to the uncle's household kept as the text's own dated stated view, not a prediction."},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Chamatkāra Cintāmaṇi §7',
            "gist": 'Chamatkara reads a native with the sun in the seventh bhava as facing strain in the marriage, tension of mind and sleeplessness, thin profit in business and rivalry with others; the text also states ill health including named ailments, wariness of authority, delayed marriage, marital discord, and more than one marriage.',
            "adaptation": {"classes": ['gender', 'health', 'archaic'], "action": 'neutralise',
                            "note": "Marital strain and discord rendered spouse-neutral, and 'two wives' rendered as more than one marriage, per section 5(b); denial of children's happiness rendered progeny-neutral per section 5(c). 'Afraid of the king' glossed to wariness of authority per section-5 archaic handling. Disease, syphilis, diabetes and insomnia kept as the text's own dated stated-effects, cited as the classical view, not a prediction and not medical advice."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Chamatkāra Cintāmaṇi §8',
            "gist": 'Chamatkara reads a native with the sun in the eighth bhava as crafty and hard to pin down, leading a difficult, wandering life, careless in habits, wasteful of wealth, and prone to thieving; handsome but indolent, quarrelsome and self-indulgent; the text also states secret ailments and poor health, piles, weak sight, and a sudden end.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "'Lewd', 'adulterous' and squandering wealth 'on women' rendered as partner-neutral self-indulgence per section 5(b); the 'low women' clause (a verdict on a category of women) is refused per section 5(a); loss of offspring rendered progeny-neutral per section 5(c). Infectious disease, piles, weak sight and the sudden-death timing kept as the text's own dated stated-effects, cited as the classical view, explicitly not a prediction and not medical advice. 'Crafty', 'impostor', 'spendthrift' and 'quarrelsome' are clean words, kept plainly."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Chamatkāra Cintāmaṇi §9',
            "gist": 'Chamatkara reads a native with the sun in the ninth bhava as a wicked man whose good deeds are not the outcome of [his own virtue — the surviving source text breaks off here].',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "'Wicked' is a clean character word and is kept plainly. The reading is present but truncated in this source; only the opening clause survives, so the rendering is confined to what the raw text actually states."},
            "confidence": "corroborated",
        },
    },
    'moon': {
        1: {  # 1st
            "citation": 'Chamatkāra Cintāmaṇi §13',
            "gist": "Chamatkara reads a native with the Moon in the first bhava as handsome yet fickle-minded: when the Moon is well placed he is wealthy and enjoys life's pleasures, but otherwise he lives in want, lean, foolish and hard of hearing, and is troubled by fear of water and sickness. (The poverty and bodily afflictions are given as the text's own dated stated-effect, not as medical fact or a prediction about anyone.)",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "Poverty, leanness and deafness kept as the source's own dated stated-effect with not-medical framing; the clean character words 'fickle' and 'foolish' carry no class and are kept plainly."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Chamatkāra Cintāmaṇi §14',
            "gist": 'Chamatkara reads a native with the Moon in the second bhava as prosperous, with rich harvests, a sound body and a charming personality; romantic by temperament, the native is drawn to pleasures outside the home and may neglect the household.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "The native's own gendered conduct ('pleasure in other women's company, ignoring his wife') neutralised to partner-neutral pursuit of pleasure outside the home."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Chamatkāra Cintāmaṇi §15',
            "gist": 'Chamatkara reads a native with the Moon in the third bhava as one who gathers wealth by his own hard effort and stays austere, unmoved by temptation; his faith brings him honour and fame, and his brothers are his chief source of happiness.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "The 'charming and beautiful ladies fail to attract him' clause neutralised to partner-neutral restraint / being unmoved by temptation; the austerity and fame themes kept."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Chamatkāra Cintāmaṇi §16',
            "gist": 'Chamatkara reads a native with the Moon in the fourth bhava as one who rises to high authority in the seat of power of his day, aided by his brethren; early life is not smooth, but he enjoys the full support and encouragement of his family, spouse and children.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'Great authority to the Royal Court' glossed as high authority/leadership within the ruling institutions of its time and kept."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Chamatkāra Cintāmaṇi §17',
            "gist": 'Chamatkara reads a native with the Moon in the fifth bhava as blessed with promising offspring and a clear mind, gaining wealth from diamonds, land, trade, moneylending and many other sources.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "The progeny reference ('promising children') rendered progeny-neutral; the clear mind and sources-of-gain themes kept."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Chamatkāra Cintāmaṇi §18',
            "gist": 'Chamatkara reads a native with the Moon in the sixth bhava as one who overpowers even the mightiest enemies, who ultimately surrender while their repeated attacks misfire; yet he is not devoted to his mother and remains indifferent to her.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content; the plain indifference-to-mother clause kept as stated.'},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Chamatkāra Cintāmaṇi §19',
            "gist": 'Chamatkara reads a native with the Moon in the seventh bhava as one who marries a devoted partner and gains from buying and selling, from travel and foreign trade; the native enjoys good food, is sensual, thin and lean, and may be worsted by an enemy.',
            "adaptation": {"classes": ['gender'], "action": 'refuse',
                            "note": "Verdicts on the spouse's health/character and on the spouse being the source of 'full sexual pleasure', and the category-verdict that 'women are more passionate in the dark half', are refused; a partner-neutral marriage rendering is kept, along with the trade, food and enemy themes. The clean word 'sensual' kept plainly."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Chamatkāra Cintāmaṇi §20',
            "gist": "Chamatkara reads a native with the Moon in the eighth bhava as one who suffers acute and chronic ailments, attended by many doctors who prescribe strange remedies, and living under constant fear of disease. (This is given as the text's own dated stated-effect, not as medical fact or a prediction about anyone.)",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "Disease and ill-health kept as the source's own dated stated-effect with explicit not-medical framing."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Chamatkāra Cintāmaṇi §21',
            "gist": "Chamatkara reads a native with the Moon in the ninth bhava as one praised and celebrated by the people, the wise and the bards, favoured by fortune from early youth, of sound body, though the native's courage waxes and wanes like the changing Moon.",
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content; praise, good fortune and the fluctuating-courage image kept as stated.'},
            "confidence": "corroborated",
        },
    },
    'mars': {
        1: {  # 1st
            "citation": 'Chamatkāra Cintāmaṇi §25',
            "gist": 'Chamatkara reads a native with mars in the 1st bhava (the rising sign) as exposed to danger from cudgel, weapon and fire and to mental grief, with ailments of the head and eyes; the text says loss of dear ones may reach even into the marriage, and that although the native shows lion-like courage, success is said to come hard despite his best efforts.',
            "adaptation": {"classes": ['health', 'gender'], "action": 'adapt',
                            "note": "Health effects (weapon/fire injury, head and eye ailments) kept as the text's own dated stated-effect, not a medical or predictive claim. The clause on a wife's death is neutralised to loss or strain in marriage, never rendered as a fatal prediction about a spouse."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Chamatkāra Cintāmaṇi §26',
            "gist": 'Chamatkara reads a native with mars in the 2nd bhava as one who cannot make use of the wealth he inherits from kin -- the text likens him to a monkey guarding a necklace without knowing its worth -- so that stinginess and hostility stand between him and his family, and he clings to his money rather than let it go.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'Plain character terms (stingy, hostile) kept as the text states them; there is no dated social content in the primary reading to adapt.'},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Chamatkāra Cintāmaṇi §27',
            "gist": 'Chamatkara reads a native with mars in the 3rd bhava as strong-armed and able to win wealth by hard labour, brave and industrious, devoted to his brothers and to religious practice and asceticism, and favoured by the authority of his day; the text also states hardship, even death, befalling younger brothers.',
            "adaptation": {"classes": ['archaic', 'health'], "action": 'adapt',
                            "note": "'Royal favour' glossed as the standing or authority of its time and kept. The affliction and death said to touch younger brothers is kept as the text's own dated stated-effect, not a medical or predictive claim."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Chamatkāra Cintāmaṇi §28',
            "gist": 'Chamatkara reads a native with mars in the 4th bhava as denied the comforts of home -- little help or pleasure from friends and family, quarrels with parents and domestic strife, and want of land, conveyance and prosperity -- and the text states early loss of the mother, with recognition of authority and land arriving, if at all, only through the rich.',
            "adaptation": {"classes": ['archaic', 'health'], "action": 'adapt',
                            "note": "The land-and-clothes recognition ('royal favour') glossed as the authority of its time and kept. The clause on the mother's early death kept as the text's dated stated-effect, framed as the classical view rather than a prediction."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Chamatkāra Cintāmaṇi §29',
            "gist": 'Chamatkara reads a native with mars in the 5th bhava as having a fierce, unsatisfiable appetite and a restless mind pulled toward wrongdoing, sharp in intellect yet distressed at heart; the text also states difficulty and loss around progeny, with children hard to raise.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "The passages on children not surviving and on abortions are rendered progeny-neutral as the text's stated difficulty around offspring, kept as a dated stated-effect and not a medical or predictive claim; clean terms (wicked, mean) kept plainly."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Chamatkāra Cintāmaṇi §30',
            "gist": 'Chamatkara reads a native with mars in the 6th bhava as one whose enemies, however powerful, are put to flight by his strength and fierce bearing; brainy and prosperous, he loses wealth only to build it up again, though the text says the placement does not favour the maternal uncles.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'The primary reading carries no dated social content to adapt; the stated affliction to maternal uncles is kept as the text gives it.'},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Chamatkāra Cintāmaṇi §31',
            "gist": 'Chamatkara reads a native with mars in the 7th bhava as slow to return from abroad even when marriage or business is settled, repeatedly thwarted and often dwelling in a foreign land, giving up his enterprise; the text speaks of strain and loss touching the marriage and of suffering in partnership.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "The clause on a partner's or wife's death is neutralised to loss and strain in marriage, never rendered as a fatal prediction about a spouse."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Chamatkāra Cintāmaṇi §32',
            "gist": 'Chamatkara reads a native with mars in the 8th bhava as one whose fortune is overridden -- even benefics lose their good, friends turn hostile though they are honoured, and honest effort is defeated by obstacles; the text further states chronic ailments, named disease, and a sudden or violent end.',
            "adaptation": {"classes": ['health', 'gender'], "action": 'adapt',
                            "note": "Named disease (leprosy), chronic ailments and the bare death-timing (short life, sudden or violent death) kept as the text's own dated stated-effect, framed as the classical view and explicitly not a medical or predictive claim. The 'few sons' clause rendered progeny-neutral."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Chamatkāra Cintāmaṇi §33',
            "gist": 'Chamatkara reads a native with mars in the 9th bhava as keen, rational and brilliant, whose fortune nonetheless turns on luck rather than effort -- the text says even lion-like labour goes unrewarded -- with no elder brother or brother-in-law, gain from agriculture, and trouble reaching the father.',
            "adaptation": {"classes": ['health', 'gender'], "action": 'adapt',
                            "note": "The clause naming the native impotent is refused and omitted per policy. Ill-health and trouble to the father kept as the text's dated stated-effect, not a medical or predictive claim; clean terms (cruel, vicious) kept plainly."},
            "confidence": "corroborated",
        },
    },
    'mercury': {
        1: {  # 1st
            "citation": 'Chamatkāra Cintāmaṇi §37',
            "gist": "Chamatkara reads a native with mercury in the first bhava (lagna) as one in whom Mercury cancels the harmful pull of the other planets: the native lives by speech and writing, shines like burnished gold, and is known to all as a scholar who shuns evil — handsome, wise, learned in the fine arts, poetry and arithmetic, courteous, generous, pious and of settled family life, honoured by those in authority (the text's 'royal honour'). The same passage adds, as its own dated view and not as medical fact, a leaning to skin discolouration, biliousness, boils, moles and stomach complaints.",
            "adaptation": {"classes": ['archaic', 'health', 'gender'], "action": 'neutralise',
                            "note": "'Royal honour/reputation' glossed as standing and authority of its time (archaic). Bodily complaints kept as the text's own dated stated-effect with a not-medical framing (health). 'Blessed with wife and children' rendered partner- and progeny-neutral as settled family life (gender)."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Chamatkāra Cintāmaṇi §38',
            "gist": 'Chamatkara reads a native with mercury in the second bhava as exceptionally sharp and self-made — among the learned like Veda Vyasa, in an assembly arguing like Brihaspati, dignified and well-versed in music, wealthy and large-hearted. The text calls the native prosperous, noble, renowned, gentle, skilled and righteous, a poet of pleasing speech who accumulates wealth by his own principles, devoted to father and teacher, rational, God-fearing and truth-loving, whose lost wealth returns; it also notes, as its own dated view and not as medical fact, a tendency to skin troubles.',
            "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss',
                            "note": "Reverence toward Veda Vyasa, Brihaspati and the Guru glossed as regard for the learned class of its time (archaic). Skin troubles kept as the text's own dated stated-effect with a not-medical framing (health)."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Chamatkāra Cintāmaṇi §39',
            "gist": 'Chamatkara reads a native with mercury in the third bhava as one who, after winning the friendship of merchants and learning the secrets of their trade, launches his own business and earns greatly by his own expertise and mastermind, courteously drawing to himself those who help his enterprise spread far and wide. The text describes a temperament swinging between intense sensuality and outright renunciation born of detachment; money-minded, gaining through and greatly benefiting brothers and sisters, surrounded by relatives whom he supports; wicked, glorious, dear to friends and devoted to God and teacher.',
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise',
                            "note": "'Very sensual and lustful' rendered partner-neutral as intense sensuality set against renunciation (gender). Devotion to God and Guru glossed as regard of its time for the learned/sacred (archaic). Clean word 'wicked' kept plainly."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Chamatkāra Cintāmaṇi §40',
            "gist": 'Chamatkara reads a native with mercury in the fourth bhava as one who enjoys the friendship of superiors and rises to leadership — a leader of the people or an officer on special charge, one who writes or dictates to others. The text says the native receives no inheritance and earns through hard labour, keeps the best company, and holds a position of authority whose word is honoured even at home; famous, eloquent, fortunate, truthful, musical, a scholar and mathematician, courteous and prosperous in land, food and wealth.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'Prince', 'officer', 'administrator in the court' glossed as leadership and authority of its time (archaic). No caste/gender/health content beyond this."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Chamatkāra Cintāmaṇi §41',
            "gist": 'Chamatkara reads a native with mercury in the fifth bhava as one who amasses wealth through his own wisdom and adroitness, and whose reading turns on the matter of children — the text ties this placement to an early child or pregnancy that does not come to term, with children of later life surviving, and eventually offspring and grandchildren. The passage frames the native as an adviser, balanced, brave and happy, with many friends and logical discourse, gentle yet strange in his acts, and winning name and fame through his learning; it also calls his acts wicked and crooked, and his temper crafty from keeping vicious company.',
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise',
                            "note": "The daughter-not-son, abortion and sons/grandsons clauses rendered progeny-neutral as matters of children (gender). Devotion to 'noble and learned people' glossed as regard of its time for the learned (archaic). Clean words 'wicked', 'crooked', 'crafty' kept plainly."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Chamatkāra Cintāmaṇi §42',
            "gist": 'Chamatkara reads a native with mercury in the sixth bhava as one perpetually set against opponents yet checking and vanquishing his enemies, who seeks knowledge in the company of saints and holy men and spends his means on sacred pursuits, saving wisely and building wealth by his own effort even as he stirs friction with relatives. The text also states, as its own dated view and not as medical fact, a proneness to indigestion, heartburn, dyspepsia, dysentery and biliousness; and it calls the native logical, skilled, sharp-tongued, lazy, learned and quarrelsome.',
            "adaptation": {"classes": ['health', 'archaic'], "action": 'keep',
                            "note": "Named ailments (indigestion, dyspepsia, dysentery, biliousness, generative-system disease) kept as the text's own dated stated-effect with a not-medical framing (health). Company of saints/sannyasis and 'divine knowledge from holy men' glossed as devotional idiom of its time (archaic). Clean words 'sharp-tongued', 'lazy', 'quarrelsome' kept plainly."},
            "confidence": "corroborated",
        },
    },
    'jupiter': {
        1: {  # 1st
            "citation": 'Chamatkāra Cintāmaṇi §49',
            "gist": 'Chamatkara reads a native with jupiter in the 1st bhava (lagna) as one known and recognised by people for his fine qualities — well-dressed, graceful, prosperous, of charming personality, learned, handsome, fearless and long-lived — who spends his wealth freely on devotional and charitable acts (jap-tap-yajan-dan) and inclines toward salvation. A scholar, honoured and favoured by the authority of his day, large-hearted, gentle, patient, mature and pious, a poet and singer fond of fine clothes and delicacies. The text also blesses him with children.',
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'refuse+neutralise+gloss',
                            "note": "The 'less manly' clause is refused per policy (a virility verdict). 'Royal favour' is glossed as honour/favour from the authority of its time and kept. 'Blessed with sons' is rendered progeny-neutral as children. Clean qualities (charming, pious, etc.) kept plainly."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Chamatkāra Cintāmaṇi §50',
            "gist": 'Chamatkara reads a native with jupiter in the 2nd bhava as one whose heart and mind are given to poetry, both composing and reciting it, eloquent and skilled in alluring verse; a figure of judicial or directorial authority of his day who dispenses reward and punishment. Rich, grateful, handsome, blessed with kin and cattle-wealth, generous, learned and popular, with sweet and measured speech — though financial gain comes only after much effort and is sooner lost than earned.',
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'refuse+gloss',
                            "note": "'Infirm and impotent' is refused per policy (a virility verdict). Judge/magistrate/collector/director glossed as judicial authority of its time and kept. Clean traits (grateful, generous) kept plainly."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Chamatkāra Cintāmaṇi §51',
            "gist": 'Chamatkara reads a native with jupiter in the 3rd bhava as petty, ungrateful and untrustworthy — a thankless, base friend who nonetheless extends every help to his brothers and holds strong fraternal feeling, yet reaps little financial gain despite good luck and the favour of authority. Miserly, stingy, crafty and wicked, prone to dyspepsia and loss of appetite, melancholy, and strained in his marriage and family attachments, though much given to voyaging and travel.',
            "adaptation": {"classes": ['gender', 'health', 'archaic'], "action": 'neutralise+keep+gloss',
                            "note": "'Unsuccessful with wife', 'no attachment with wife and children' and 'debauchee' are neutralised to partner-neutral marriage/family strain. Dyspepsia and loss of appetite kept as the text's own dated stated ailments (not medical advice). 'Royal favour' glossed as the favour of authority of its time. Clean character words (petty, ungrateful, untrustworthy, base, miser, stingy, crafty, wicked) kept plainly."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Chamatkāra Cintāmaṇi §52',
            "gist": 'Chamatkara reads a native with jupiter in the 4th bhava as one at whose door horses neigh and learned brahmins chant the Vedas — prosperous, handsome, renowned, a victor and head of his family, honoured by the authority of his day and rich in conveyances, land and the comforts of home. He commands a large household and its service, is devoted to the learned priestly class of his time, and is blessed with mother, friends, spouse and family, though his inner self may remain unsettled.',
            "adaptation": {"classes": ['slavery', 'archaic', 'gender'], "action": 'historicise+gloss+neutralise',
                            "note": "'Captives/slaves serve him' is historicised — the service livelihood/household is kept, the servile ranking dropped. Brahmins-as-class glossed as the learned priestly class of its time and 'royal favour'/'wealth through the state' as authority of its time. 'Blessed with son, wife' rendered spouse-and-family neutral."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Chamatkāra Cintāmaṇi §53',
            "gist": "Chamatkara reads a native with jupiter in the 5th bhava as sensual and fond of pleasure and ease, an eloquent speaker, most imaginative, a logician and impressive writer-author. Wealthy, accomplished, scholarly, prudent and steady, adored by elders and given to yogic practice, and holding a position of standing in the counsel of his day — though possessions may be ordinary and accomplishment hard-won. The text's remarks on offspring run both ways, helpful in some placements and scarce in others.",
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise+gloss+keep',
                            "note": "Progeny statements (blessed with sons / absence of progeny) rendered offspring-neutral and left as the text's own two-way remark. 'Minister' glossed as a position of counsel/standing of its time. The clean word 'sensual' kept plainly per policy."},
            "confidence": "corroborated",
        },
    },
    'venus': {
        1: {  # 1st
            "citation": 'Chamatkāra Cintāmaṇi §61',
            "gist": "Chamatkara reads a native with Venus in the first bhava as comely and shapely of body, long-living and prosperous, keeping company with virtuous and saintly people and devoting himself to charity, worship and noble religious rites while spending freely for good causes. The native is amorous and drawn to companionship (the source's gendered phrasing rendered partner-neutrally), learned and impressive, and — in the idiom of its time — favoured by those in authority. The text adds that this placement is said to ward off many an evil yoga of other planets.",
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise',
                            "note": "Source's gendered conduct ('enjoys imposing pretty women', 'copulation with charming women', 'sexy') neutralised to partner-neutral amorousness per policy 5(b); 'royal favour' glossed as authority/patronage of its time per archaic policy. Framed as the text's dated view, not the native's fate."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Chamatkāra Cintāmaṇi §62',
            "gist": 'Chamatkara reads a native with Venus in the second bhava as sweet and pleasing in speech, sharp and religious-minded, handsome and dressed in fine, colourful garments, and wealthy from many sources including his own knowledge. The text describes the native as learned, a poet and an artist who enjoys rich food and drink, amorous by disposition (rendered partner-neutrally), respected by relatives and — in the idiom of its time — by the ruler, and devoted to his preceptor.',
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise',
                            "note": "Source's gendered phrasing ('desire and passion for sexy women', 'lustful', 'language for passionate women') neutralised to partner-neutral amorousness per policy 5(b); 'respected by the ruler' glossed as esteem from authority of its time per archaic policy. Dated view, not fate."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Chamatkāra Cintāmaṇi §63',
            "gist": "Chamatkara reads a native with Venus in the third bhava as attached to relatives and friends and supportive of his dependents, with little settled affection in companionship (the source's gendered phrasing rendered partner-neutrally). The text calls the native miserly and sparing with alms, neither a warrior nor — in the idiom of its time — a leader on the battlefield, content with simple living, surrounded by several siblings, and desirous of more children (rendered progeny-neutrally).",
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise',
                            "note": "Gendered phrasing ('no affection for women folk', 'weakness for comely women') neutralised to partner-neutral, and 'wants more sons' rendered progeny-neutral per policy 5(b)/(c); 'army chief / chief in the battle field' glossed as leadership of its time per archaic policy. Clean words 'miser'/'stingy' kept plainly."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Chamatkāra Cintāmaṇi §64',
            "gist": "Chamatkara reads a native with Venus in the fourth bhava as one who wins great honour and respect and remains unaffected by others' pleasure or displeasure. The native is devoted to his mother from childhood and gains through her, prospers with land, home, cattle, conveyance and fine garments, and is elegant, liberal and pious. In the idiom of its time the text makes him a headman of standing who honours learned men, and its charge of self-indulgence is rendered partner-neutrally.",
            "adaptation": {"classes": ['archaic', 'gender'], "action": 'neutralise',
                            "note": "'Chief of the village' glossed as local leadership/standing of its time per archaic policy; 'debauchee' (self-indulgence) neutralised to partner-neutral per policy 5(b). Dated view, not fate."},
            "confidence": "corroborated",
        },
    },
    'saturn': {
        1: {  # 1st
            "citation": 'Chamatkāra Cintāmaṇi §73',
            "gist": "Chamatkara reads a native with Saturn in the first bhava (the lagna) as wealthy yet gripped by an unabated greed and a settled discontent — quarrelsome, unhappy, crude and blunt in manner, mentally agonised, jealous of others' prosperity, with a cold, forbidding, Saturn-like gaze, who nonetheless overpowers even the strongest of his enemies and yet is never satisfied. The text also states, as its own dated view of its time and not as a medical judgement or a prediction, that such a native tends to bilious complaints and is prone to various recurring ailments.",
            "adaptation": {"classes": ['health'], "action": 'keep-dated',
                            "note": "Clean character words (greedy, discontented, quarrelsome, unhappy, crude, jealous) kept plainly, unsoftened. Bilious tendency and 'various ailments' kept as the text's own dated stated-effect, framed as the classical view, not medical advice or a prediction. Sign-by-sign sub-cases and modern/Western commentary ignored."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Chamatkāra Cintāmaṇi §74',
            "gist": 'Chamatkara reads a native with Saturn in the second bhava as one who leaves his family behind and travels far, even settling in a foreign land, to seek every kind of pleasure and success — harsh, bitter and blunt in speech, discordant with friends, restless, a teller of untruths and an imposter, base, and single-minded in pursuing his own ends. It states he gains wealth and success through all the eight metals, especially iron, and through the luxuries of life, yet is poor in his own country and prosperous abroad. As its own dated view of its time, rather than a medical or literal prediction, the text adds that he may suffer loss of wealth through the displeasure of the ruling authority of its day, and be troubled by bilious, phlegmatic and rheumatic complaints and a defect of speech.',
            "adaptation": {"classes": ['health', 'archaic'], "action": 'keep-dated',
                            "note": "Clean character words (liar, restless, imposter, base, harsh, bitter, selfish) kept plainly, unsoftened. Bilious/phlegmatic/rheumatic tendency and speech defect kept as the text's own dated stated-effect, not medical advice. 'Wrath of the highest authority' glossed as the ruling authority of its time (archaic authority). Livelihood themes (travel/foreign settlement, trade in the eight metals/iron) kept without moral ranking; sign-by-sign sub-cases and modern commentary ignored."},
            "confidence": "corroborated",
        },
    },
    'rahu': {
        1: {  # 1st
            "citation": 'Chamatkāra Cintāmaṇi §85',
            "gist": 'Chamatkara reads a native with rahu in the first bhava as one who overcomes his rivals and turns the standing and influence of others into instruments of his own success, harnessing their powers for himself and those around him; the text also reads a strongly sensual temperament and a restless romantic appetite that strains fidelity in partnership.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "The source's clause on lewdness/adultery and dissatisfaction with the wife is the native's own gendered conduct; per policy it is neutralised to a partner-neutral note of a restless romantic temperament straining fidelity, not a verdict on any woman."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Chamatkāra Cintāmaṇi §86',
            "gist": 'Chamatkara reads a native with rahu in the second bhava as fearless and placed as a keeper of wealth (a treasurer), yet marked by untruthfulness and the company of the wicked; the text states, as its own dated view, the undoing of his family and kin and danger from weapons — set down as the classical reading, not as a prediction.',
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "'Liar', 'fearless' and 'wicked' are clean words kept plainly. The destruction-of-family and danger-from-weapon clauses are kept as the text's own dated stated harm, framed as the classical view rather than fate, and are not medical or predictive. 'Treasurer' is a livelihood theme with no status ranking."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Chamatkāra Cintāmaṇi §87',
            "gist": 'Chamatkara reads a native with rahu in the third bhava as matchless in prowess — stronger, the text says, than the mightiest of beasts, the lion or the elephant — who treats everyone as kin and is fortunate.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content in the primary reading; rendered plainly.'},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Chamatkāra Cintāmaṇi §88',
            "gist": "Chamatkara reads a native with rahu in the fourth bhava as one whose mother is persistently unwell and who is himself troubled in mind — recorded as the text's own dated view of affliction to the mother and to mental ease, not as medical fact or prediction.",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "The mother's chronic ailing and the native's psychic/mental trouble are kept as the source's dated stated effects, framed as the classical view; not medical advice and not a prediction."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Chamatkāra Cintāmaṇi §89',
            "gist": 'Chamatkara reads a native with rahu in the fifth bhava as bearing on children — a significator of offspring — with delay or difficulty around the first child and worry in the domestic sphere; the text also states, as its own dated view, hard-to-cure chest complaints, noting that where the placement lacks good fortune, effort avails little.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "Progeny/first-born-son content is neutralised to progeny-neutral (children/first child). The 'short-tempered partner' character clause is a verdict on the spouse and is dropped per policy, kept only as worry in the domestic/partner sphere. The incurable chest ailment is kept as the text's dated stated effect, not medical or predictive."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Chamatkāra Cintāmaṇi §90',
            "gist": 'Chamatkara reads a native with rahu in the sixth bhava as one who overcomes all his enemies, steady in strength, wisdom, valour and conscience, and matchless in himself.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content in the primary reading; rendered plainly.'},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Chamatkāra Cintāmaṇi §91',
            "gist": 'Chamatkara reads a native with rahu in the seventh bhava as marked by grave strain and loss in marriage, and by separation from kin and public slander — a placement the text frames as heavily afflicting the partnership.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "The source's clause has the wife dying of disease; per policy the fatal spousal clause is neutralised to marriage loss/strain and never rendered as the death of a woman. Separation from relatives and public slander are kept as the text's stated effects."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Chamatkāra Cintāmaṇi §92',
            "gist": 'Chamatkara reads a native with rahu in the eighth bhava as troubled by gastric complaints and recurring losses, deserted by his own family and cut off from inheritance, yet honoured by those in authority and by the learned of his day; fortune, the text says, favours him once but loss returns again and again.',
            "adaptation": {"classes": ['health', 'archaic'], "action": 'keep',
                            "note": "Gastric ailments, desertion by family, denied patrimony and recurring losses are kept as the source's dated stated effects (health/loss), framed as the classical view and not medical or predictive. 'Rulers and pandits' is glossed as those in authority and the learned class of its time, and kept."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Chamatkāra Cintāmaṇi §93',
            "gist": 'Chamatkara reads a native with rahu in the ninth bhava as a scholar honoured for his virtues, compelling in speech before an assembly, cultured and humane, devout and reverent toward the sacred, grateful, and a support to his own family.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content in the primary reading; devotion and scholarship rendered plainly.'},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Chamatkāra Cintāmaṇi §94',
            "gist": 'Chamatkara reads a native with rahu in the tenth bhava as prone to spending on intoxicants and to wrongdoing, troubled by others, restless and vain, and living among foreigners; the text also reads a strongly pleasure-seeking romantic temperament.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "The clause on sex with young, beautiful women mixes the native's own conduct with an objectifying description of women; it is neutralised to a partner-neutral note of a pleasure-seeking romantic temperament, dropping the description of the women. 'Intoxicants', 'wrong-doer' and 'vain' are clean and kept plainly."},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Chamatkāra Cintāmaṇi §95',
            "gist": 'Chamatkara reads a native with rahu in the eleventh bhava as one who gains his wealth through foreigners and people outside his own community, living proudly and wanting for nothing at home; the text also reads him as keeping the company of knaves and cheating others of their money, and as blessed with children.',
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise',
                            "note": "'Blessed with sons' is neutralised to progeny-neutral (children). 'Aliens/non-Aryans' is a dated ethnic framing, glossed to foreigners/people outside his community and kept. 'Knave', 'wrong-doer' and 'cheats' are clean and kept plainly; 'attendants' is a status marker, not the native's own servitude."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Chamatkāra Cintāmaṇi §96',
            "gist": 'Chamatkara reads a native with rahu in the twelfth bhava as beset by hardship — sharp pain in the ribs and, however hard he labours, loss rather than gain — a friend to the wicked and no friend to the good, who nonetheless in the end attains his desires and ambition.',
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "The rib pain and the frustrated-labour/loss clauses are kept as the source's dated stated effects (health/poverty), framed as the classical view and not medical or predictive. 'Miserable', 'friend of the wicked' and 'enemy of the good' are clean and kept plainly."},
            "confidence": "corroborated",
        },
    },
    'ketu': {
        1: {  # 1st
            "citation": 'Chamatkāra Cintāmaṇi §97',
            "gist": "Chamatkara reads a native with ketu in the first bhava (lagna) as beset by constant distress through relatives and dread of vicious people, perturbed and sad, inert, selfish, foolish, unattractive, a liar, ungrateful, wicked and spiritless; loss of employment, arm trouble, strain and possible loss in marriage and household health, a fearful attitude to intimacy, trouble for the maternal uncle, a spinner's livelihood, scandals and losses, danger to the face and eyes — the text even states a short life. This is the classical author's dated view of the placement, not a prediction of your fate and not a medical judgement.",
            "adaptation": {"classes": ['gender', 'health', 'occupation', 'slavery'], "action": 'neutralise',
                            "note": "'Death of wife' (violent spousal clause) neutralised to marriage loss/strain, never fatal; the spouse's stomach/restlessness verdict folded into partner-neutral household strain; 'afraid of sex' rendered neutrally; 'dismissed from service' historicised as loss of employment; 'spinner' kept as a livelihood with no status ranking; arm/eye/face trouble and 'short life' kept as the text's own dated stated-effect with explicit not-a-prediction, not-medical framing. Clean words (selfish, foolish, liar, wicked, spiritless, ugly) kept plainly."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Chamatkāra Cintāmaṇi §98',
            "gist": "Chamatkara reads a native with ketu in the second (wealth) bhava as mentally agitated over wealth, fearing the ruling power will seize it as a penalty, worried over food and support, quarrelling with friends and family, harsh and ineffective in speech in the assembly and offering neither respect nor hospitality; the text notes want of education, wickedness, unhappiness and misfortune, and trouble in the mouth. This is the classical author's dated stated view of the placement, not a forecast and not a medical judgement.",
            "adaptation": {"classes": ['health', 'caste'], "action": 'keep',
                            "note": "'Trouble in the mouth' kept as the text's own dated stated-effect with a not-medical note. 'Association of the low' had its moral/class ranking dropped (caste tag). Clean words (wicked, harsh, critical) kept plainly; 'want of education' kept as stated."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Chamatkāra Cintāmaṇi §99',
            "gist": "Chamatkara reads a native with ketu in the third bhava as one who overcomes and even destroys his enemies on the battlefield; affluent, sharp and sensual, prosperous and smart, yet given to useless and fruitless quarrels and discussions, suffering loss of friends and brothers, pain in the arms, and anxiety born of fear, misunderstanding and worry; the text also marks a strong appetite for intimacy, rendered partner-neutral. This is the classical author's dated view, not a prediction and not a medical judgement.",
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "'Has sexual affairs in great measure' (the native's own gendered conduct) neutralised to a partner-neutral appetite. 'Sensual' is a clean word and kept plainly. Pain in the arms kept as the text's dated stated-effect with a not-medical note. Overcoming/destroying enemies kept as a martial theme with no class handling."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Chamatkāra Cintāmaṇi §100',
            "gist": "Chamatkara reads a native with ketu in the fourth bhava as denied gain or favour from mother and friends, losing his patrimony and inherited wealth, seldom at home and nervous when he is, quarrelling and out of harmony with his parents, given to criticising and ill-speaking of others, dependent, losing agricultural land and suffering loss through the father, and proving unfit in assembly; the text even states the death of the mother. This is the classical author's dated view of the placement, not a prediction and not a medical judgement.",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "'Death of mother' (death of a relative, not the spouse) kept as the text's own dated stated-effect with explicit not-a-prediction framing. Clean content (criticises, ill-speaks, dependent) kept plainly; property/parental losses kept as stated."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Chamatkāra Cintāmaṇi §101',
            "gist": "Chamatkara reads a native with ketu in the fifth bhava as one whose brothers face repeated danger and injury from weapons and bile and from falls, while the native suffers physical pain born of his own misunderstandings and wrong notions; crafty, jealous, weak, timid and impatient, with stomach complaints and gain through fraud; progeny is indicated (rendered progeny-neutral); and though of great valour he nonetheless works in service. This is the classical author's dated view, not a prediction and not a medical judgement.",
            "adaptation": {"classes": ['gender', 'health', 'slavery'], "action": 'neutralise',
                            "note": "Son/daughter counts ('one or two sons', 'more daughters than sons') neutralised to progeny-neutral. 'Remains in service' historicised — the service livelihood kept, the servile status-ranking dropped. Weapon/bile injury, falls and stomach complaints kept as the text's dated stated-effect with a not-medical note. Clean words (crafty, jealous, weak, timid, impatient, fraud) kept plainly."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Chamatkāra Cintāmaṇi §102',
            "gist": "Chamatkara reads a native with ketu in the sixth bhava as disillusioned through the maternal uncle yet destroying his enemies, holding cattle wealth though otherwise poor, of sound health and quick to recover from any ailment, and successful in heated debate; dear to relatives, large-hearted, skilled and famed through knowledge, and set in a position of authority; the text notes trouble in the teeth and lips, unfaithful attendants, and danger from small animals and insects. This is the classical author's dated view, not a prediction and not a medical judgement.",
            "adaptation": {"classes": ['archaic', 'health', 'slavery'], "action": 'gloss',
                            "note": "'High officer' glossed as one holding authority/leadership of its time. 'Unfaithful servants' historicised to trouble with attendants/subordinates, servile ranking dropped. Trouble in teeth/lips and danger from animals/insects kept as the text's dated stated-effect with a not-medical note. Positive traits and 'destruction of enemies' kept plainly."},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Chamatkāra Cintāmaṇi §103',
            "gist": "Chamatkara reads a native with ketu in the seventh bhava as facing much trouble and danger from travel though he returns safely, with fear of drowning, loss of wealth, trouble through partner and children, extravagance and nervousness; the text marks a want of happiness in partnership and the native's own roving, immodest conduct (rendered partner-neutral), humble speech and foolishness, insults, desertion by the partner, intestinal ailments, and the anger of the ruling authority. This is the classical author's dated view, not a prediction and not a medical judgement.",
            "adaptation": {"classes": ['gender', 'health', 'archaic'], "action": 'neutralise',
                            "note": "The clause disparaging the spouse's character ('she is wicked') refused; the native's own immodest/adulterous conduct neutralised to partner-neutral. 'Wrath of the ruler' glossed as the ruling authority of its time. Intestinal ailment kept as the text's dated stated-effect with a not-medical note; the 'seminal troubles' clause dropped rather than kept. 'Trouble through partner and children' kept partner-/progeny-neutral. Clean words (foolish, immodest) kept plainly."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Chamatkāra Cintāmaṇi §104',
            "gist": "Chamatkara reads a native with ketu in the eighth bhava as suffering piles, fistula and secret diseases of the face and teeth, in fear of a fall from horseback or conveyance and unable easily to recover money he has lent; brave and industrious yet beset by separation from friends, strife, arm-wounds and much opposition; coveting the wealth and companionship of another (rendered partner-neutral); ailing, vicious and greedy — the text even states a short life. This is the classical author's dated view, not a prediction and not a medical judgement.",
            "adaptation": {"classes": ['health', 'gender'], "action": 'neutralise',
                            "note": "'An eye on the wealth and woman of another' (the native's own coveting conduct) neutralised to a partner-neutral coveting of another's wealth and companionship. Piles, fistula, secret/facial/dental diseases and arm-wounds kept as the text's dated stated-effect with a not-medical note; 'short-lived' kept only as the text's dated view with explicit not-a-prediction framing. Clean words (vicious, greedy, brave, industrious) kept plainly."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Chamatkāra Cintāmaṇi §105',
            "gist": "Chamatkara reads a native with ketu in the ninth bhava as having his afflictions modified, longing for children (rendered progeny-neutral) and drawing fortune and favour through foreigners, while suffering loss and trouble through brothers and pain in the arms and being mocked for his penances and donations; short-tempered, critical, brave, jealous of the father, vain, spiritless and arrogant, with trouble for the father — yet capable of rising to high office with fame, wisdom and generosity. This is the classical author's dated view, not a prediction and not a medical judgement.",
            "adaptation": {"classes": ['gender', 'health', 'archaic'], "action": 'neutralise',
                            "note": "'Desirous of sons' / 'absence of sons' / 'blessed with son' neutralised to progeny-neutral longing for children. 'May be a king or a minister' glossed as high authority/leadership of its time. Pain in the arms kept as the text's dated stated-effect with a not-medical note. Clean words (short-tempered, critical, vain, spiritless, arrogant, jealous) kept plainly."},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Chamatkāra Cintāmaṇi §106',
            "gist": "Chamatkara reads a native with ketu in the tenth bhava as unfortunate and miserable with trouble through the father, in danger of a fall from horse or conveyance, though his enemies are destroyed; intelligent, strong, a craftsman, self-realised, social and among the bravest; the text notes disease of the rectum, injury to the thigh through a conveyance, base habits, roving conduct (rendered partner-neutral), no support from parents, opposition to good works, and trouble through thieves. This is the classical author's dated view, not a prediction and not a medical judgement.",
            "adaptation": {"classes": ['health', 'gender', 'occupation'], "action": 'neutralise',
                            "note": "'Adulterous' (the native's own gendered conduct) neutralised to partner-neutral roving conduct. 'Craftsman' kept as a livelihood theme with no status ranking. Rectal disease and thigh injury kept as the text's dated stated-effect with a not-medical note. Clean words (vicious, base habits, miserable) kept plainly; 'enemies destroyed' kept as a martial theme."},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Chamatkāra Cintāmaṇi §107',
            "gist": "Chamatkara reads a native with ketu in the eleventh bhava as gaining success from every source — very fortunate, learned, handsome, well-built, well-dressed and glorious; charming, affluent, generous, skilled in aesthetics and archery, sweet, humorous, prosperous and popular, honoured by the ruling authority, a poet and writer with flourishing wealth; the text notes an ailment of the rectum, and says the native's progeny fare unfortunately (rendered progeny-neutral). This is the classical author's dated view, not a prediction and not a medical judgement.",
            "adaptation": {"classes": ['gender', 'health', 'archaic'], "action": 'neutralise',
                            "note": "'His offsprings are unfortunate' / 'unfortunate in respect of progeny' neutralised to progeny-neutral. 'Respected by the king' / 'state honour' glossed as honour from the ruling authority of its time. Rectal ailment kept as the text's dated stated-effect with a not-medical note. Positive traits and archery skill kept plainly."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Chamatkāra Cintāmaṇi §108',
            "gist": "Chamatkara reads a native with ketu in the twelfth bhava as granted high glory and prosperity, spending his wealth for the social good and defeating his enemies, yet suffering pain below the navel, in the private parts, feet and eyes, and gaining nothing through the maternal uncle; in another vein one who wastes wealth on misdeeds, a laggard in war, vicious, poor and miserly, much-travelling, restless, extravagant and indebted, eloquent in debate and highly educated, beset by secret enemies, imprisonment and self-undoing. This is the classical author's dated view, not a prediction and not a medical judgement.",
            "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss',
                            "note": "'Princely glory' glossed as high station/authority of its time. Pain below the navel, in the private parts, feet and eyes kept as the text's dated stated-effect with a not-medical note. Clean words (vicious, miser, laggard, restless, extravagant) kept plainly; 'immodest' kept as stated without amplification."},
            "confidence": "corroborated",
        },
    },
}
