"""Verified Hindu festival / observance table (amanta coordinates).

AUTO-GENERATED from the `panchang-festivals-verify` workflow: 37 rows, every one
adversarially confirmed (the amanta/purnimanta krishna-paksha shift checked cell
by cell). Do not hand-edit; re-run the workflow and regenerate. Consumed by
festivals.py, which does the day-matching. `masa` is the amanta month index
(0=Caitra..11=Phalguna); `masa_purnimanta` is the popular North-Indian name kept
for display only. See festivals.py for the sunrise-tithi matching convention.
"""

FESTIVALS = [
    {'key': "gudi-padwa", 'name': "Gudi Padwa / Ugadi", 'name_hi': "गुड़ी पड़वा / उगादि", 'basis': "lunar", 'recurring': False, 'masa': 0, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 1, 'solar_sign': None, 'importance': "major", 'significance': "Lunar New Year of the Deccan; first day of Caitra and the Hindu Vikrama Samvat year.", 'significance_hi': "चैत्र शुक्ल प्रतिपदा; दक्कन का चांद्र नववर्ष एवं विक्रम संवत का आरंभ।"},
    {'key': "rama-navami", 'name': "Rama Navami", 'name_hi': "राम नवमी", 'basis': "lunar", 'recurring': False, 'masa': 0, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 9, 'solar_sign': None, 'importance': "major", 'significance': "Birth of Lord Rama, seventh avatar of Vishnu.", 'significance_hi': "भगवान श्रीराम का जन्मोत्सव।"},
    {'key': "hanuman-jayanti", 'name': "Hanuman Jayanti", 'name_hi': "हनुमान जयंती", 'basis': "lunar", 'recurring': False, 'masa': 0, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 15, 'solar_sign': None, 'importance': "notable", 'significance': "Birth of Hanuman, celebrated on the Caitra full moon.", 'significance_hi': "चैत्र पूर्णिमा को हनुमान जी का जन्मोत्सव।"},
    {'key': "akshaya-tritiya", 'name': "Akshaya Tritiya", 'name_hi': "अक्षय तृतीया", 'basis': "lunar", 'recurring': False, 'masa': 1, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 3, 'solar_sign': None, 'importance': "major", 'significance': "Auspicious 'imperishable' day for new ventures, gold buying and charity; needs no muhurta.", 'significance_hi': "अक्षय (अनश्वर) तिथि; नए कार्य, स्वर्ण-क्रय व दान का शुभ दिन, मुहूर्त की आवश्यकता नहीं।"},
    {'key': "vat-savitri", 'name': "Vat Savitri", 'name_hi': "वट सावित्री", 'basis': "lunar", 'recurring': False, 'masa': 1, 'masa_purnimanta': "Jyeshtha", 'paksha': "krishna", 'tithi': 15, 'solar_sign': None, 'importance': "notable", 'significance': "Married women fast by the banyan tree for their husband's long life (Savitri-Satyavan).", 'significance_hi': "सुहागिनें पति की दीर्घायु हेतु वट वृक्ष के नीचे व्रत करती हैं (सावित्री-सत्यवान)।"},
    {'key': "guru-purnima", 'name': "Guru Purnima", 'name_hi': "गुरु पूर्णिमा", 'basis': "lunar", 'recurring': False, 'masa': 3, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 15, 'solar_sign': None, 'importance': "major", 'significance': "Reverence to the guru and sage Vyasa on the Ashadha full moon.", 'significance_hi': "आषाढ़ पूर्णिमा; गुरु एवं वेदव्यास के प्रति श्रद्धा का पर्व।"},
    {'key': "nag-panchami", 'name': "Nag Panchami", 'name_hi': "नाग पंचमी", 'basis': "lunar", 'recurring': False, 'masa': 4, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 5, 'solar_sign': None, 'importance': "notable", 'significance': "Worship of serpent deities (Nagas).", 'significance_hi': "नाग देवताओं की पूजा।"},
    {'key': "raksha-bandhan", 'name': "Raksha Bandhan", 'name_hi': "रक्षा बंधन", 'basis': "lunar", 'recurring': False, 'masa': 4, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 15, 'solar_sign': None, 'importance': "major", 'significance': "Sisters tie the rakhi; bond of sibling protection, on the Shravana full moon.", 'significance_hi': "श्रावण पूर्णिमा; बहनें भाइयों को राखी बाँधती हैं, रक्षा का बंधन।"},
    {'key': "krishna-janmashtami", 'name': "Krishna Janmashtami", 'name_hi': "कृष्ण जन्माष्टमी", 'basis': "lunar", 'recurring': False, 'masa': 4, 'masa_purnimanta': "Bhadrapada", 'paksha': "krishna", 'tithi': 8, 'solar_sign': None, 'importance': "major", 'significance': "Midnight birth of Lord Krishna, eighth avatar of Vishnu.", 'significance_hi': "अर्धरात्रि में भगवान श्रीकृष्ण का जन्मोत्सव।"},
    {'key': "ganesh-chaturthi", 'name': "Ganesh Chaturthi", 'name_hi': "गणेश चतुर्थी", 'basis': "lunar", 'recurring': False, 'masa': 5, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 4, 'solar_sign': None, 'importance': "major", 'significance': "Birth and installation of Ganesha; ten-day festival.", 'significance_hi': "गणेश जी का जन्म व स्थापना; दस दिवसीय उत्सव।"},
    {'key': "navaratri", 'name': "Navaratri (start)", 'name_hi': "नवरात्रि (आरंभ)", 'basis': "lunar", 'recurring': False, 'masa': 6, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 1, 'solar_sign': None, 'importance': "major", 'significance': "Start of Sharada Navaratri, nine nights of Durga worship.", 'significance_hi': "शारदीय नवरात्रि का आरंभ; नौ रातें देवी दुर्गा की आराधना।"},
    {'key': "durga-ashtami", 'name': "Durga Ashtami", 'name_hi': "दुर्गा अष्टमी", 'basis': "lunar", 'recurring': False, 'masa': 6, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 8, 'solar_sign': None, 'importance': "notable", 'significance': "Mahashtami; eighth-day worship of Durga and Kanya Puja.", 'significance_hi': "महाष्टमी; दुर्गा की अष्टमी पूजा एवं कन्या पूजन।"},
    {'key': "maha-navami", 'name': "Maha Navami", 'name_hi': "महानवमी", 'basis': "lunar", 'recurring': False, 'masa': 6, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 9, 'solar_sign': None, 'importance': "notable", 'significance': "Ninth day of Navaratri; culmination of Durga worship.", 'significance_hi': "नवरात्रि का नवम दिन; दुर्गा आराधना की पूर्णाहुति।"},
    {'key': "vijayadashami", 'name': "Vijayadashami / Dussehra", 'name_hi': "विजयादशमी / दशहरा", 'basis': "lunar", 'recurring': False, 'masa': 6, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 10, 'solar_sign': None, 'importance': "major", 'significance': "Dussehra; Rama's victory over Ravana and Durga's over Mahishasura.", 'significance_hi': "दशहरा; राम की रावण पर तथा दुर्गा की महिषासुर पर विजय।"},
    {'key': "sharad-purnima", 'name': "Sharad Purnima", 'name_hi': "शरद पूर्णिमा", 'basis': "lunar", 'recurring': False, 'masa': 6, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 15, 'solar_sign': None, 'importance': "notable", 'significance': "Autumn full moon; Kojagari Lakshmi vigil and moon-nectar.", 'significance_hi': "शरद पूर्णिमा; कोजागरी लक्ष्मी जागरण व अमृत-वर्षा।"},
    {'key': "karva-chauth", 'name': "Karva Chauth", 'name_hi': "करवा चौथ", 'basis': "lunar", 'recurring': False, 'masa': 6, 'masa_purnimanta': "Kartika", 'paksha': "krishna", 'tithi': 4, 'solar_sign': None, 'importance': "notable", 'significance': "Wives fast from dawn until moonrise for their husband's longevity.", 'significance_hi': "सुहागिनें पति की दीर्घायु हेतु चंद्रोदय तक निर्जल व्रत रखती हैं।"},
    {'key': "dhanteras", 'name': "Dhanteras", 'name_hi': "धनतेरस", 'basis': "lunar", 'recurring': False, 'masa': 6, 'masa_purnimanta': "Kartika", 'paksha': "krishna", 'tithi': 13, 'solar_sign': None, 'importance': "notable", 'significance': "First day of Diwali; worship of Dhanvantari and Lakshmi, buying of metals.", 'significance_hi': "दीपावली का प्रथम दिन; धन्वंतरि व लक्ष्मी पूजन, धातु-क्रय।"},
    {'key': "naraka-chaturdashi", 'name': "Naraka Chaturdashi", 'name_hi': "नरक चतुर्दशी", 'basis': "lunar", 'recurring': False, 'masa': 6, 'masa_purnimanta': "Kartika", 'paksha': "krishna", 'tithi': 14, 'solar_sign': None, 'importance': "notable", 'significance': "Choti Diwali; Krishna's slaying of Narakasura, ritual pre-dawn bath (abhyanga snan).", 'significance_hi': "छोटी दीपावली; कृष्ण द्वारा नरकासुर वध, अभ्यंग स्नान।"},
    {'key': "diwali", 'name': "Diwali (Lakshmi Puja)", 'name_hi': "दीपावली (लक्ष्मी पूजा)", 'basis': "lunar", 'recurring': False, 'masa': 6, 'masa_purnimanta': "Kartika", 'paksha': "krishna", 'tithi': 15, 'solar_sign': None, 'importance': "major", 'significance': "Festival of lights; worship of Lakshmi and Ganesha on the new moon.", 'significance_hi': "दीपों का पर्व; अमावस्या को लक्ष्मी-गणेश पूजन।"},
    {'key': "govardhan-puja", 'name': "Govardhan Puja / Bali Pratipada", 'name_hi': "गोवर्धन पूजा / बलि प्रतिपदा", 'basis': "lunar", 'recurring': False, 'masa': 7, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 1, 'solar_sign': None, 'importance': "notable", 'significance': "Govardhan lifting by Krishna and Annakut; Bali Pratipada, the day after Diwali.", 'significance_hi': "कृष्ण द्वारा गोवर्धन-धारण व अन्नकूट; बलि प्रतिपदा, दीपावली के अगले दिन।"},
    {'key': "bhai-dooj", 'name': "Bhai Dooj", 'name_hi': "भाई दूज", 'basis': "lunar", 'recurring': False, 'masa': 7, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 2, 'solar_sign': None, 'importance': "notable", 'significance': "Sisters honor brothers with tilak; Yama and Yamuna legend.", 'significance_hi': "बहनें भाइयों को तिलक कर आशीर्वाद देती हैं; यम-यमुना कथा।"},
    {'key': "chhath", 'name': "Chhath", 'name_hi': "छठ", 'basis': "lunar", 'recurring': False, 'masa': 7, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 6, 'solar_sign': None, 'importance': "major", 'significance': "Worship of the Sun god and Chhathi Maiya with river offerings at sunset and sunrise.", 'significance_hi': "सूर्य देव व छठी मैया की उपासना; नदी-तट पर संध्या व प्रातः अर्घ्य।"},
    {'key': "vasant-panchami", 'name': "Vasant Panchami", 'name_hi': "वसंत पंचमी", 'basis': "lunar", 'recurring': False, 'masa': 10, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 5, 'solar_sign': None, 'importance': "notable", 'significance': "Saraswati Puja marking the onset of spring.", 'significance_hi': "सरस्वती पूजा; वसंत ऋतु का आगमन।"},
    {'key': "maha-shivaratri", 'name': "Maha Shivaratri", 'name_hi': "महाशिवरात्रि", 'basis': "lunar", 'recurring': False, 'masa': 10, 'masa_purnimanta': "Phalguna", 'paksha': "krishna", 'tithi': 14, 'solar_sign': None, 'importance': "major", 'significance': "Great night of Shiva; fasting and night-long vigil.", 'significance_hi': "शिव की महान रात्रि; उपवास एवं रात्रि-जागरण।"},
    {'key': "holika-dahan", 'name': "Holika Dahan", 'name_hi': "होलिका दहन", 'basis': "lunar", 'recurring': False, 'masa': 11, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 15, 'solar_sign': None, 'importance': "notable", 'significance': "Bonfire on the Phalguna full moon marking Holika's burning and triumph over evil.", 'significance_hi': "फाल्गुन पूर्णिमा को होलिका दहन; बुराई पर विजय।"},
    {'key': "holi", 'name': "Holi / Dhulandi", 'name_hi': "होली / धुलंडी", 'basis': "lunar", 'recurring': False, 'masa': 11, 'masa_purnimanta': "Chaitra", 'paksha': "krishna", 'tithi': 1, 'solar_sign': None, 'importance': "major", 'significance': "Festival of colours, the day after Holika Dahan.", 'significance_hi': "रंगों का पर्व (धुलंडी); होलिका दहन के अगले दिन।"},
    {'key': "makara-sankranti", 'name': "Makara Sankranti", 'name_hi': "मकर संक्रांति", 'basis': "solar", 'recurring': False, 'masa': None, 'masa_purnimanta': None, 'paksha': None, 'tithi': None, 'solar_sign': 9, 'importance': "major", 'significance': "Sun enters sidereal Capricorn; start of uttarayana and the harvest season.", 'significance_hi': "सूर्य का मकर राशि में प्रवेश; उत्तरायण व फसल पर्व का आरंभ।"},
    {'key': "mesha-sankranti", 'name': "Mesha Sankranti (Solar New Year)", 'name_hi': "मेष संक्रांति (सौर नववर्ष)", 'basis': "solar", 'recurring': False, 'masa': None, 'masa_purnimanta': None, 'paksha': None, 'tithi': None, 'solar_sign': 0, 'importance': "notable", 'significance': "Sun enters sidereal Aries; solar New Year (Baisakhi, Vishu, Puthandu, Poila Boishakh).", 'significance_hi': "सूर्य का मेष राशि में प्रवेश; सौर नववर्ष (बैसाखी, विशु, पुथांडु)।"},
    {'key': "ekadashi-shukla", 'name': "Ekadashi (Shukla)", 'name_hi': "एकादशी (शुक्ल)", 'basis': "lunar", 'recurring': True, 'masa': None, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 11, 'solar_sign': None, 'importance': "observance", 'significance': "Eleventh-tithi fast dedicated to Vishnu, waxing fortnight.", 'significance_hi': "शुक्ल पक्ष की एकादशी; विष्णु को समर्पित व्रत।"},
    {'key': "ekadashi-krishna", 'name': "Ekadashi (Krishna)", 'name_hi': "एकादशी (कृष्ण)", 'basis': "lunar", 'recurring': True, 'masa': None, 'masa_purnimanta': None, 'paksha': "krishna", 'tithi': 11, 'solar_sign': None, 'importance': "observance", 'significance': "Eleventh-tithi fast dedicated to Vishnu, waning fortnight.", 'significance_hi': "कृष्ण पक्ष की एकादशी; विष्णु को समर्पित व्रत।"},
    {'key': "pradosha-shukla", 'name': "Pradosha (Shukla)", 'name_hi': "प्रदोष व्रत (शुक्ल)", 'basis': "lunar", 'recurring': True, 'masa': None, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 13, 'solar_sign': None, 'importance': "observance", 'significance': "Trayodashi twilight worship of Shiva, waxing fortnight.", 'significance_hi': "शुक्ल त्रयोदशी; प्रदोष काल में शिव पूजा।"},
    {'key': "pradosha-krishna", 'name': "Pradosha (Krishna)", 'name_hi': "प्रदोष व्रत (कृष्ण)", 'basis': "lunar", 'recurring': True, 'masa': None, 'masa_purnimanta': None, 'paksha': "krishna", 'tithi': 13, 'solar_sign': None, 'importance': "observance", 'significance': "Trayodashi twilight worship of Shiva, waning fortnight.", 'significance_hi': "कृष्ण त्रयोदशी; प्रदोष काल में शिव पूजा।"},
    {'key': "sankashti-chaturthi", 'name': "Sankashti Chaturthi", 'name_hi': "संकष्टी चतुर्थी", 'basis': "lunar", 'recurring': True, 'masa': None, 'masa_purnimanta': None, 'paksha': "krishna", 'tithi': 4, 'solar_sign': None, 'importance': "observance", 'significance': "Waning fourth-tithi fast to Ganesha, broken at moonrise.", 'significance_hi': "कृष्ण चतुर्थी; गणेश व्रत, चंद्रोदय पर पारण।"},
    {'key': "vinayaka-chaturthi", 'name': "Vinayaka Chaturthi", 'name_hi': "विनायक चतुर्थी", 'basis': "lunar", 'recurring': True, 'masa': None, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 4, 'solar_sign': None, 'importance': "observance", 'significance': "Waxing fourth-tithi worship of Ganesha.", 'significance_hi': "शुक्ल चतुर्थी; गणेश की मासिक पूजा।"},
    {'key': "masik-shivaratri", 'name': "Masik Shivaratri", 'name_hi': "मासिक शिवरात्रि", 'basis': "lunar", 'recurring': True, 'masa': None, 'masa_purnimanta': None, 'paksha': "krishna", 'tithi': 14, 'solar_sign': None, 'importance': "observance", 'significance': "Monthly night of Shiva on the waning fourteenth tithi.", 'significance_hi': "प्रति मास कृष्ण चतुर्दशी; मासिक शिवरात्रि।"},
    {'key': "purnima", 'name': "Purnima", 'name_hi': "पूर्णिमा", 'basis': "lunar", 'recurring': True, 'masa': None, 'masa_purnimanta': None, 'paksha': "shukla", 'tithi': 15, 'solar_sign': None, 'importance': "observance", 'significance': "Full-moon day; fasting, charity and Satyanarayana puja.", 'significance_hi': "पूर्णिमा; व्रत, दान व सत्यनारायण पूजा।"},
    {'key': "amavasya", 'name': "Amavasya", 'name_hi': "अमावस्या", 'basis': "lunar", 'recurring': True, 'masa': None, 'masa_purnimanta': None, 'paksha': "krishna", 'tithi': 15, 'solar_sign': None, 'importance': "observance", 'significance': "New-moon day; ancestral rites (tarpana and shraddha).", 'significance_hi': "अमावस्या; पितरों हेतु तर्पण व श्राद्ध।"},
]
