"""
Phaladīpikā of Mantreśvara (~13th c. CE), V. Subrahmanya Sastri tr. — CLASSICAL
tier, PLANET-IN-HOUSE only (Adhyāya 8, "the Sun and other planets in the 12
bhāvas from the lagna onwards"). Site-authored, cited, §5-adapted GISTs rendered
from the translation, extracted from the raw text and adversarially verified.
"""
SOURCE = {
    "id": "phaladipika", "text": "Phaladīpikā", "author": "Mantreśvara",
    "date": "~13th c. CE", "translator": "V. Subrahmanya Sastri",
    "tier": "classical",
}


# graha key -> bhāva (1-12) -> entry (planet-in-house; partial where OCR is).
IN_HOUSE = {
    'sun': {
        7: {  # 7th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Sun in the 7th bhava as a wanderer who meets humiliation and remains without a spouse.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "Only the tail of this reading survives the OCR, but it clearly closes the Sun-in-7th sutra just before the 8th-house line. The source's 'without a wife' clause is rendered partner-neutral ('without a spouse') per gender policy (b); 'wandering' and 'humiliation' kept plainly."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with the Sun in the 8th bhava as losing wealth and friends, short of long life, and troubled with weak or failing eyesight — offered as the text's dated view, not a medical or predictive claim.",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "Loss of wealth (poverty), the short life-span clause, and the eyesight/blindness clause are all kept as the text's own dated stated-effects with explicit not-medical, not-a-prediction framing per the death/disease/poverty policy."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Sun in the 9th bhava as one who suffers the loss of the father yet is surrounded by children and kin and shows reverence to the gods and to the learned priestly class of its day.',
            "adaptation": {"classes": ['health', 'caste'], "action": 'gloss',
                            "note": "'Revere Brahmins' is reverence toward the priestly class, glossed as the learned/priestly class of its time and kept (tag caste). The father-loss clause is kept as the text's dated stated-effect with not-a-prediction framing (tag health). 'Children and relations' is already progeny-neutral and kept plainly."},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with the Sun in the 10th bhava as blessed with offspring, vehicles, praise, intelligence, wealth, strength and fame — a figure of authority and leadership (the text says 'king').",
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise',
                            "note": "'Sons' is neutralised to progeny-neutral 'offspring/children' per gender policy (c). 'King' is glossed as authority/leadership and kept per the archaic policy. Intelligence, vehicles, praise, wealth, strength and fame kept plainly."},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with the Sun in the 11th bhava as very wealthy, long of life and free of sorrow, and a figure of authority and leadership (the text says 'king').",
            "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss',
                            "note": "'King' is glossed as authority/leadership and kept per the archaic policy. The 'long-lived' life-span clause is kept as the text's dated view with not-a-prediction framing (tag health). Wealth and freedom from sorrow kept plainly."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with the Sun in the 12th bhava as estranged from and resentful of the father, with defective eyesight and lacking wealth and children — offered as the text's dated view, not a medical or predictive claim.",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "The defective-eyesight clause and the lack of wealth (poverty) are kept as the text's own dated stated-effects with not-medical, not-a-prediction framing. 'Hate his father' is a plain relational statement kept as-is; 'without children' is already progeny-neutral and kept plainly."},
            "confidence": "corroborated",
        },
    },
    'moon': {
        1: {  # 1st
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native born with a waxing Moon in the first bhava as strong in constitution and long-lived, fearless, powerful and wealthy; a waning Moon, the text adds, turns these effects to their reverse.',
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "Kept as the classical text's own dated statement on vitality and longevity, framed as its view and not as a medical or life-span prediction. 'Powerful/wealthy' are plain and left as stated."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with the Moon in the second bhava as sensual in temperament yet, in the text's words, defective in some limb.",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "'Sensualist' is a plain character word carrying no dated social ranking and is left unsoftened. The limb-defect clause is kept as the text's own dated stated-effect, not a medical claim."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Moon in the third bhava as having siblings and being strong and powerful, and drawn to sensual enjoyment.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Lascivious' is neutralised to partner-neutral language about the native's own appetite for pleasure. Brothers, strength and power are kept plainly. Source clause is truncated by OCR after 'powerful'."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with the Moon in the fourth bhava as happy and given to life's pleasures, generous with gifts, well supplied with friends and conveyances, and renowned.",
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "No dated social content. 'Sensual pleasures' is a plain term and is kept as-is."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Moon in the fifth bhava as blessed with worthy children, highly intelligent, gentle in bearing, and rising to become a counsellor to those in authority.',
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise',
                            "note": "'Good sons' is neutralised to progeny-neutral 'worthy children'. 'Minister' is glossed to a leadership/advisory role of its era and kept."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Moon in the sixth bhava as, in its dated view, short in years and unlearned, troubled by stomach ailments and subject to humiliation.',
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "Short-life timing and the named stomach ailment are kept as the classical text's own dated stated-effects, explicitly not a prediction and not medical advice. 'Ignorant' and 'humiliation' are plain and left as stated."},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Moon in the seventh bhava as pleasing in appearance, exceedingly lovely, and cherished by a beloved partner.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "The native's own attractiveness is kept plainly. The 'beautiful damsel' clause, a verdict on a woman's looks, is neutralised to a partner-neutral rendering of being loved."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Moon in the eighth bhava as, in its dated view, prone to illness and short in years.',
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "Disease and short-life timing are kept as the classical text's own dated stated-effects, framed as its view and not as a prediction or medical claim."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Moon in the ninth bhava as prosperous and virtuous, blessed with children, victorious, and successful in every undertaking from its very outset.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Blessed with children' is rendered progeny-neutral. The rest is plainly positive and kept."},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Moon in the tenth bhava as a doer of good deeds and a helper of the virtuous.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content.'},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Moon in the eleventh bhava as high-minded and long-lived, endowed with wealth, children and a household of attendants.',
            "adaptation": {"classes": ['health', 'gender', 'slavery'], "action": 'historicise',
                            "note": "Longevity is kept as the text's dated view (not a life-span prediction). 'Children' is rendered progeny-neutral. 'Servants' is historicised to a household of attendants of its era, dropping any servile ranking."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with the Moon in the twelfth bhava as disagreeable to others, beset by misery and insult, and most indolent.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'Plain character and circumstance words (odious, misery, insulted, indolent) carry no dated social ranking and are kept unsoftened.'},
            "confidence": "corroborated",
        },
    },
    'mars': {
        1: {  # 1st
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Mars in the 1st bhava (lagna) as bearing an injured or maimed limb and as cruel and adventurous in temperament; the text further gives — as its own dated view and not a forecast — a short span of life.',
            "adaptation": {"classes": ['health'], "action": 'keep-dated',
                            "note": "Injured limb and short life kept as the source's own dated stated-effect, not medical or predictive; the clean character words 'cruel' and 'adventurous' kept plainly."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Mars in the 2nd bhava as harsh or ill-favoured in face, wanting learning and — in the text's dated idiom — wealth, and thrown among low or bad company.",
            "adaptation": {"classes": ['health'], "action": 'keep-dated',
                            "note": "Poverty ('devoid of wealth') kept as the source's dated stated-effect, not a prediction; 'devoid of learning' and 'dependent on bad people' kept plainly."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Mars in the 3rd bhava as of good qualities, wealthy, brave, unassailable and happy, though without brothers.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "No dated social content; positive reading and the 'no brothers' clause kept plainly."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Mars in the 4th bhava as deprived of friends, mother, lands, domestic happiness, house and vehicles.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'A plain reading of deprivation with no protected-class content; kept as written.'},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Mars in the 5th bhava as unhappy, beset by reverses, back-biting and weak-minded, and without progeny.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "Progeny clause rendered progeny-neutral ('without progeny'); the clean words 'back-biting' and 'weak-minded' kept plainly."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Mars in the 6th bhava as victorious in conflict and rising to authority — the text's 'king' — triumphant over rivals.",
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'King' glossed as authority/leadership of its time and kept; victory in battle kept plainly."},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Mars in the 7th bhava as given to improper acts, afflicted by disease (the text's own dated view, not medical counsel), wandering the roads, and meeting loss or strain in marriage.",
            "adaptation": {"classes": ['health', 'gender'], "action": 'neutralise',
                            "note": "Disease kept as the source's dated stated-effect, not medical; the spousal-loss clause neutralised to marriage loss/strain and never rendered as fatal; 'improper acts' kept plainly as the native's own conduct."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Mars in the 8th bhava as of deformed body and poor, and censured by people; the text also gives, as its dated view and not a prediction, a short life.',
            "adaptation": {"classes": ['health'], "action": 'keep-dated',
                            "note": "Bodily deformity, poverty and short life kept as the source's own dated stated-effect, not medical or predictive; 'cursed by the people' kept plainly."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Mars in the 9th bhava as, though a friend of the ruler (the text's sovereign, read as one in authority), disliked by others, without a father, and prone to bloodshed.",
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'Sovereign' glossed as authority of its time and kept; the loss of father and the homicide clause kept plainly."},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Mars in the 10th bhava as rising to authority — the text's 'king' — cruel yet liberal, and praised by persons of standing.",
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'King' glossed as authority/leadership of its time and kept; the clean words 'cruel' and 'liberal' kept plainly."},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Mars in the 11th bhava as endowed with riches and happiness, brave, free from sorrow, and of good character.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'A wholly positive reading with no dated social content; kept as written.'},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Mars in the 12th bhava as having defective or deformed eyes (the text's own dated view, not medical counsel), cruel in temper, without a spouse, and given to slander.",
            "adaptation": {"classes": ['health', 'gender'], "action": 'neutralise',
                            "note": "Eye affliction kept as the source's dated stated-effect, not medical; the 'without a wife' clause neutralised to partner-neutral ('without a spouse'); the clean words 'cruel' and 'slanderer' kept plainly."},
            "confidence": "corroborated",
        },
    },
    'mercury': {
        1: {  # 1st
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 1st bhava as long-lived, sweet and clever in speech, sharp-witted, and learned across all the sciences.',
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "'Long-lived' is kept as the source's own dated statement of lifespan, framed as the classical view and not a prediction or a medical claim."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 2nd bhava as one who wins wealth through his own talents, a poet, sincere and pleasing in speech, and enjoying fine food.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content; the reading is rendered plainly.'},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 3rd bhava as brave and blessed with good brothers, yet of middling lifespan and prone to fatigue and low spirits.',
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "'Of medium life' is kept as the source's own dated statement of lifespan, framed as the classical view and not a prediction or a medical claim."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 4th bhava as learned and witty in speech, contented, and provided with friends, land, grain, wealth and enjoyment.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content; the reading is rendered plainly.'},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 5th bhava as learned, cheerful and courageous, blessed with progeny, and versed in charms and spells.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": 'The progeny count is rendered in progeny-neutral terms per policy; the rest is kept plainly.'},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 6th bhava as quarrelsome and angered by disputes, harsh in speech and idle, yet one who breaks the strength of his enemies.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content; the plain character words (harsh, idle) are kept as stated.'},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 7th bhava as learned, finely dressed and enjoying every greatness, and marrying into wealth.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": 'The clause describing the spouse is rendered partner-neutral (a prosperous marriage) rather than as a verdict on the wife.'},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 8th bhava as widely renowned and long-lived, the mainstay of his family, and rising to leadership and command in the manner of its era.',
            "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss',
                            "note": "'Lord and commander of the army' is glossed to authority and leadership of its time; 'long-lived' is kept as the source's dated view of lifespan, not a prediction or medical claim."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 9th bhava as endowed with learning and wealth, devout, widely knowledgeable, and highly eloquent in speech.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content; the reading is rendered plainly.'},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 10th bhava as successful in all undertakings, well-learned, strong, intelligent and content, doing good deeds and truthful.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content; the reading is rendered plainly.'},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 11th bhava as long-lived, truthful, very wealthy and content, attended by a household of its era.',
            "adaptation": {"classes": ['slavery', 'health'], "action": 'historicise',
                            "note": "'Possessed of servants' is historicised to an attended household of its time; 'long-lived' is kept as the source's dated view of lifespan, not a prediction or medical claim."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with mercury in the 12th bhava as miserable and unlearned, meeting humiliation, and cruel and inactive.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content; the plain character words (cruel, inactive) are kept as stated.'},
            "confidence": "corroborated",
        },
    },
    'jupiter': {
        1: {  # 1st
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with jupiter in the 1st bhava as handsome, fortunate and fearless, long of life and enriched in offspring — a favourable placement in the text's view.",
            "adaptation": {"classes": ['health', 'gender'], "action": 'neutralise',
                            "note": "'Blessed with children' rendered progeny-neutral as offspring; long life kept as the source's dated view, not a health prediction."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with jupiter in the 2nd bhava as eloquent and a fine connoisseur of food, lovely of face, wealthy and learned.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content; rendered plainly.'},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with jupiter in the 3rd bhava as meeting disrespect and inclined to miserliness, sinful and wicked in disposition, though possessed of a renowned brother.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'Clean character words (miserly, sinful, wicked) kept plainly and unsoftened; no dated social content.'},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with jupiter in the 4th bhava as living happily surrounded by mother, friends, household, spouse and offspring, with abundant grain.',
            "adaptation": {"classes": ['gender', 'slavery'], "action": 'neutralise',
                            "note": "'Sons' rendered progeny-neutral as offspring; 'attendants' historicised as household/retinue."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with jupiter in the 5th bhava as intelligent and a counsellor to ruling authority (an 'adviser to the king' in the text's idiom), yet troubled through their offspring.",
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise',
                            "note": "'Distress through sons' rendered progeny-neutral; 'king's adviser' glossed as counsel to authority of its time."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with jupiter in the 6th bhava as quite inactive and meeting disrespect, yet overcoming enemies and skilled in charms and exorcism.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No dated social content; clean word (inactive) kept plainly.'},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with jupiter in the 7th bhava as amiable and more open-handed than the parent before them, with a settled married and family life.',
            "adaptation": {"classes": ['gender'], "action": 'refuse',
                            "note": "The source's quality-verdict on the spouse ('good wife') is declined; marriage kept partner-neutral and sons rendered as offspring."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with jupiter in the 8th bhava as living by humble service and in poverty, sinful yet long of life — the text's own dated verdict, not fate or a medical prediction.",
            "adaptation": {"classes": ['slavery', 'health'], "action": 'historicise',
                            "note": "'Menial' historicised to a service livelihood without the servile ranking; poverty and long life kept as the source's dated stated-effect, not medical or predictive."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with jupiter in the 9th bhava as a renowned figure of authority (a 'minister' in the text's idiom), rich, devoted to virtuous deeds and blessed with offspring.",
            "adaptation": {"classes": ['archaic', 'gender'], "action": 'gloss',
                            "note": "'Minister' glossed as leadership/authority of its time; children rendered progeny-neutral as offspring."},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with jupiter in the 10th bhava as upright in conduct and renowned for virtue, very wealthy, and close to ruling authority (a 'friend of the king' in the text's idiom).",
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'Friend of the king' glossed as closeness to leadership/authority of its time."},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with jupiter in the 11th bhava as wealthy and fearless, long of life, moving about in fine conveyances, with few offspring.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "'Few children' rendered progeny-neutral; long life kept as the source's dated view, not a health prediction."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with jupiter in the 12th bhava as disliked by others and foul of speech, sinful and idle, living by humble service and without offspring.',
            "adaptation": {"classes": ['gender', 'slavery'], "action": 'neutralise',
                            "note": "'No children' rendered progeny-neutral; 'menial' historicised to humble service; clean words (foul-mouthed, sinful, idle) kept plainly."},
            "confidence": "corroborated",
        },
    },
    'venus': {
        1: {  # 1st
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Venus in the 1st bhava as one of healthy, well-formed body, cheerful and happy, and blessed with long life — the text's own dated view of vitality, offered as its classical reading rather than as fate or medical assessment.",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "Bodily health and longevity kept as the source's dated stated effect, with a not-medical, not-a-prediction framing."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Venus in the 2nd bhava as gifted in poetry and endowed with wealth of many kinds.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "No dated social content requiring adaptation; 'poet' is a plain livelihood with no moral ranking, kept as stated."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Venus in the 3rd bhava as unpartnered, unhappy, poor, miserly and unpopular — the plain character word 'miser' kept exactly as the text states it.",
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "'Wifeless' neutralised to partner-neutral (without a partner/unmarried); poverty kept as the text's dated stated effect, not fate; 'miserly' is a clean word, kept plainly and unsoftened."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Venus in the 4th bhava as possessing good conveyances and a good home — material comforts of hearth and movement.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "No dated social content requiring adaptation; the source line is cut off after 'good house', so only the comfort/home theme is rendered."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Venus in the 5th bhava as owning immense wealth, a protector of others, very wise, and blessed with progeny.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Children' rendered progeny-neutral; the remaining wealth, wisdom and protective themes are clean and kept as stated."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Venus in the 6th bhava as free of enemies yet without riches, liable to be led astray in matters of desire, and touched by grief.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "'Corrupted by young females' neutralised to the native's own conduct in partner-neutral terms; poverty ('no riches') kept as the text's dated stated effect, framed as the classical view and not a prediction."},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Venus in the 7th bhava as one whose partnerships are marked by entanglement and strain, who may undergo the loss of a marriage, yet who becomes wealthy.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "Verdicts on a spouse's or a category of women's character are set aside per policy; the native's conduct is rendered partner-neutral, and the marital-loss clause is rendered as strain or loss of the marriage, never as harm; 'wealthy' is kept plainly."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Venus in the 8th bhava as long-lived, wealthy, and a ruler of the earth — 'ruler' read as a figure of authority and leadership of its time, and longevity kept as the text's dated view rather than a medical claim.",
            "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss',
                            "note": "'Ruler of the earth' glossed as authority/leadership of its era; longevity kept as the source's dated stated effect with a not-a-prediction framing."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Venus in the 9th bhava as blessed with a partner, friends and progeny, and prospering through the favour of those in power.',
            "adaptation": {"classes": ['gender', 'archaic'], "action": 'neutralise',
                            "note": "'Wife' rendered partner-neutral and 'children' progeny-neutral; 'royal favour' glossed as the patronage of authority of its time."},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Venus in the 10th bhava as widely renowned, well-befriended, and a person of standing happily employed — 'lord' glossed as a figure of authority and standing.",
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'Lord' glossed as authority/standing of its time; renown and friendship kept plainly."},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Venus in the 11th bhava as rich, fond of company and pleasures, and endowed with many comforts.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Fond of the company of other females' rendered as the native's own inclination in partner-neutral terms; wealth and comforts kept as stated."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Venus in the 12th bhava as enjoying sensual pleasures, wealth and splendour.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "Rendered as the native's own sensual enjoyment in partner-neutral terms; 'sensual' carries no class and is kept plainly alongside the wealth and splendour themes."},
            "confidence": "corroborated",
        },
    },
    'saturn': {
        1: {  # 1st
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Saturn in the first bhava (lagna) as, when Saturn there is exalted or in its own sign, attaining a station of civic authority and leadership on a par with a ruler, chief or city headman of its time; but when Saturn rises in any other sign, the text states the native meets sorrow and hardship from early childhood, falls into want, and tends to be slovenly and indolent. Framed as the classical view of that era, not a prediction and not medical or financial advice.',
            "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss',
                            "note": "'On a par with king / chief / mayor of a city' glossed to authority and civic leadership of its time (archaic). The sorrow-from-childhood and indigence clause kept as the text's own dated stated effect with a not-a-prediction, not-medical framing (health). Clean words 'slovenly' and 'indolent' kept plainly."},
            "confidence": "corroborated",
        },
        2: {  # 2nd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Saturn in the second bhava as, in earlier life, lacking wealth and inclined to evil courses, yet in later life dwelling in a foreign land furnished with conveyances, wealth and comforts. Stated as the text's own dated view of fortune over a lifetime, not a prediction.",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "'Without wealth' (early poverty) kept as the text's dated stated effect, not a prediction (health). 'Following evil courses' is a clean character phrase and is kept plainly. The foreign-residence and later prosperity are neutral and kept."},
            "confidence": "corroborated",
        },
        3: {  # 3rd
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Saturn in the third bhava as very intelligent, liberal in giving and content in domestic partnership, though inactive in disposition.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Happy with his wife' neutralised to partner-neutral domestic contentment (gender, native's own relationship, positive). 'Very intelligent', 'liberal in gifts' and 'inactive' are clean and kept plainly."},
            "confidence": "corroborated",
        },
        4: {  # 4th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Saturn in the fourth bhava as unhappy, without a settled home or conveyances, parted early from the mother, and sickly in the early years. Kept as the text's dated stated effect, not a prediction and not medical advice.",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "Houselessness/want and early sickliness kept as the text's own dated stated effect with a not-a-prediction, not-medical framing (health). Loss of the mother kept plainly as a stated life-effect, not a category verdict."},
            "confidence": "corroborated",
        },
        5: {  # 5th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Saturn in the fifth bhava as wandering and troubled in mind, wanting for progeny, wealth and happiness, and of a perfidious, ill-disposed bent. Stated as the classical view, not a prediction and not medical advice.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "'Bereft of children' neutralised to progeny-neutral wanting of progeny (gender). 'Lost his reason' and loss of wealth/happiness kept as the text's dated stated effect with a not-medical framing (health). Clean words 'perfidious' and 'evil-minded' kept plainly."},
            "confidence": "corroborated",
        },
        6: {  # 6th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Saturn in the sixth bhava as a hearty eater, wealthy, beset by rivals yet stubborn and holding firm self-respect.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": "No dated social content. 'Voracious eater', 'stubborn' and 'possessed of self-respect' are clean and kept plainly; wealth and being pressed by adversaries are neutral and kept."},
            "confidence": "corroborated",
        },
        7: {  # 7th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Saturn in the seventh bhava as beset by poverty, wandering and distress.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'refuse',
                            "note": "The clause 'wedded to a bad wife' is a verdict on the character of the spouse and is refused per policy (gender). Poverty, roaming and distress kept as the text's dated stated effect with a not-a-prediction framing (health)."},
            "confidence": "corroborated",
        },
        8: {  # 8th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Saturn in the eighth bhava as unclean and without wealth, pinched by hunger, afflicted with piles, cruel-minded, and scorned by others. The named ailment is kept as the text's dated stated effect, not a prediction and not medical advice.",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "'Piles' (named disease) and want/hunger kept as the text's own dated stated effect with a not-a-prediction, not-medical framing (health). 'Unclean' and 'cruel-minded' are clean and kept plainly; being despised kept as stated."},
            "confidence": "corroborated",
        },
        9: {  # 9th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Saturn in the ninth bhava as wanting in fortune, wealth, progeny, father and religious merit, and of a wicked bent. Stated as the classical view, not a prediction.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "'Bereft of children' neutralised to progeny-neutral wanting of progeny (gender). Loss of fortune and wealth kept as the text's dated stated effect (health). Loss of father and of religious merit kept plainly as stated life-effects; 'wicked' is clean and kept plainly."},
            "confidence": "corroborated",
        },
        10: {  # 10th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": 'Phaladipika reads a native with Saturn in the tenth bhava as rising to authority or to a ministerial office of its time, given to husbandry, and brave, wealthy and renowned. Terms of kingship are glossed as leadership of their era.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'King or his minister' glossed to authority and leadership/ministerial office of its time (archaic). Agriculture kept as a neutral livelihood theme (no moral ranking to drop). 'Brave', 'rich' and 'renowned' kept plainly."},
            "confidence": "corroborated",
        },
        11: {  # 11th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Saturn in the eleventh bhava as long-lived, of lasting wealth and steady income, brave, free of disease and moneyed. Kept as the text's dated stated effect, not a prediction and not medical advice.",
            "adaptation": {"classes": ['health'], "action": 'keep',
                            "note": "Longevity and freedom from disease are kept as the text's dated stated effect with a not-a-prediction, not-medical framing (health). Wealth, income and bravery are neutral and kept plainly."},
            "confidence": "corroborated",
        },
        12: {  # 12th
            "citation": 'Phaladīpikā, Adhyāya 8',
            "gist": "Phaladipika reads a native with Saturn in the twelfth bhava as impudent, indigent, wanting progeny, defective in some limb, dull-witted, and driven out by rivals. Kept as the text's dated stated effect, not a prediction and not medical advice.",
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "'Without children' neutralised to progeny-neutral wanting of progeny (gender). Indigence and 'defective of some limb' (physical infirmity) kept as the text's dated stated effect with a not-medical framing (health). Clean words 'impudent' and 'stupid' kept plainly; being driven out by adversaries kept as stated."},
            "confidence": "corroborated",
        },
    },
}
