"""
Sārāvalī of Kalyāṇa Varma (~9-10th c. CE), R. Santhanam tr. (Ranjan) — CLASSICAL tier.

Planet-in-sign: the Sun (ch.22), Moon (ch.23), Mars (ch.25) and Mercury (ch.26) in the
12 rāśis. (Jupiter/Venus/Saturn are in Vol 2, not yet on hand.) Each entry is a concise,
SITE-AUTHORED, cited, adaptation-classified GIST per docs/classical-sources-policy.md — a
rendering of the copyrighted Santhanam translation, NOT a reproduction — verified against
the Vol 1 edition and independently checked for faithfulness, policy (§5) and non-fatalism.
"""
SOURCE = {
    "id": "saravali", "text": "Sārāvalī", "author": "Kalyāṇa Varma",
    "date": "~9-10th c. CE", "translator": "R. Santhanam (Ranjan Publications)",
    "tier": "classical",
}

# graha key -> sign index (0=Meṣa … 11=Mīna) -> entry.
IN_SIGN = {
    'sun': {
        0: {  # Aries
            "citation": 'Sārāvalī 22.2-3',
            "gist": 'Sārāvalī (~10th c.) reads a native with the Sun in Aries — its sign of exaltation — as a scholar who expounds the meaning of the śāstras and wins fame in the arts; martial and fierce in temperament yet firmly attached to duty; fond of travel and roaming (a wandering the text ties to the exalted Sun); strong-boned, splendorous and physically strong; effective and valorous in deed. The text assigns the placement to rank and command — "Narendra," a king or leader in its own idiom — carrying an alternate classical reading as a healer able to cure poisons (a physician\'s calling). The same passage flags, in its period humoral framing, a leaning toward bilious (pitta) and blood-related disorders — recorded as the text\'s stated view of ~1,000 years ago, not as a medical prediction or as fate.',
            "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss + historicise',
                            "note": "Two dated content-classes are present; the rest is clean. Archaic-referent ('king / Narendra') is glossed as authority and leadership in its context, and the alternate classical reading (curer of poisons / physician) is kept as a livelihood theme, not a status ranking. Disease ('bilious and bloody disorders') is kept as the text's stated humoral effect, cited and dated, framed as the ~10th-c. view and never as fate, with a not-medical-advice disclaimer — the §5 death/disease handling, correctly mapped to historicise. No caste, gender/marriage, slavery, occupation-status ranking, remedy, or death-timing content exists in the source, so nothing was wrongly omitted or wrongly retained. The scholarly / martial / dutiful / wandering / valour / vitality traits ship plainly."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Sārāvalī 22.10–11',
            "gist": "Sārāvalī (22.10–11, ~10th c.) reads a Taurus Sun as someone the text calls beautiful — a variant reads fortunate/handsome — dignified in bearing and wise, with a lean, spare build, who nonetheless has hardships to endure. It credits the native with an abundance of fine things (good food, garlands, fine clothing and fragrances) and genuine skill in the arts of song, instrumental music and dance. As its own ~10th-century view — not fate, and not medical guidance — the text also flags a proneness to complaints of the face and eyes and a caution around water, and reads the native as having few children (neutralised from the text's 'few sons'). Sārāvalī 22.10–11 further voices an aversion toward 'barren (or confined) women'; that judgement is not reproduced here — it is a value-laden claim about a category of women, not a reading of the native.",
            "adaptation": {"classes": ['health', 'gender'], "action": "neutralise + refuse (disease/hazard kept as the text's dated stated-effect; remainder clean)",
                            "note": "Health/hazard items (disease of the face and eyes, emaciated/lean body, danger from water) are kept as the text's own dated stated-effect — framed as the ~10th-c. reading, not fate, with no medical claim. 'Few sons' is NEUTRALISED to 'few children': the son-preference is dropped, the progeny principle kept. The aversion to 'barren (or confined) women' is REFUSED as a value-laden gendered judgement about a class of women with no surviving neutral structural core. All remaining themes — beautiful/fortunate, decorum, wisdom, enduring hardship, being endowed with food/garlands/robes/scents, and skill in singing/instrumental music/dance — are CLEAN and ship plainly, attributed and dated. No caste, occupation-status, slavery, remedy, or archaic-referent content present; no death-timing."},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Sārāvalī 22.18-19',
            "gist": 'Sārāvalī reads a Gemini Sun native as a scholar — sweet in speech, well-conducted, modest, and affectionate, particularly toward their own children. The text assigns command of worldly, secular learning (which it explicitly frames as distinct from knowledge of Brahman, the Supreme Spirit — i.e. spiritual self-knowledge, not the brahmin caste) together with mastery of the śāstras, the traditional sciences and scriptures, and an aptitude for astrology. It reads the person as liberal (generous), skilful, exceedingly affluent, and fortunate, though only mediocre in physical appearance. In its own idiom it also assigns "two mothers," traditionally understood as being raised by two mother-figures — for example a birth mother alongside a second, foster or step-maternal figure.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "Two non-clean items, both ARCHAIC-REFERENT, handled by GLOSS (not omission): (1) 'expert in profane/worldly knowledge as opposed to the knowledge of Brahman/the Supreme Spirit, and in the śāstras' — kept and rendered in context as command of secular learning held distinct from Brahman the Supreme Spirit (i.e. spiritual self-knowledge), plus mastery of the traditional śāstras. NB: 'Brahman' here is the metaphysical Absolute, NOT the brahmin varṇa — so this is religious-path framing (gloss), with NO caste verdict to omit. (2) 'two mothers' — kept and glossed as being raised by two mother-figures (e.g. birth mother plus a foster/step maternal figure), offered as illustration, not asserted as fact. Everything else ships CLEAN: scholar, sweet speech, good conduct, affection particularly toward one's own offspring (already offspring-neutral — no number-of-sons claim to neutralise), generosity, skill, exceeding affluence, mediocre appearance, fortune, modesty, and astrologer as a livelihood/aptitude (no high/low status ranking present, so occupation-status has nothing to drop — effectively clean). No caste, slavery/servitude, value-laden gendered, death/disease/poverty, or remedy content is present. Framed throughout as 'the text reads/assigns…' per attribution-over-endorsement, with the ~9–10th-c. date visible."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Sārāvalī 22.26–27',
            "gist": 'Sārāvalī reads the Sun in Cancer as a temperament pulled two ways — restless and not steady of purpose in its undertakings, yet at bottom described as very steady in character. It assigns fame through "royal" qualities (glossed here as leadership and commanding presence in its period sense), a good-looking appearance, eloquence, honourableness, and adherence to virtuous principles. The text also reads the native as burdened and distressed by hard work, drawn to intoxicants, and knowledgeable in geography and the science of the atmosphere and skies. Relationally, it marks the native as at odds with their own people and averse to relatives on the paternal side. On marriage, the surviving structural note — strain or misfortune in the domain of marriage/partnership, which a strong full Moon is said to relieve — is kept partner-neutral; the text\'s judgement of a spouse\'s beauty or ugliness is not reproduced, since a partner\'s looks are not the native\'s to predict. On health, it assigns a classical humoral tendency toward phlegm- and bile- (kapha/pitta) related imbalance — a ~10th-century reading shown for completeness, framed as the text\'s view rather than fate, and not medical advice.',
            "adaptation": {"classes": ['gender', 'health', 'archaic'], "action": 'neutralise + refuse + historicise + gloss (remainder clean)',
                            "note": "GENDER/MARRIAGE ('unfortunate in respect of wife'; 'ugly wife'; full-Moon 'beautiful wife'): neutralised to a partner-neutral structural claim — strain/misfortune in the marriage-partnership domain, relieved by a strong full Moon; the spouse-beauty/ugliness verdict is REFUSED and not reproduced (a partner's looks/character are not the native's to predict). DEATH/DISEASE ('troubled by phlegm and bile'): kept as the text's stated humoral effect, cited + dated (~10th c.), framed as the text's view not fate, with a not-medical-advice note (historicise). ARCHAIC-REFERENT ('famous by royal qualities'): glossed as leadership/authority/commanding presence in its context, kept. All remaining themes are clean and ship plainly: unsteady-in-undertakings yet steady-in-nature, good looks, eloquence, honour, virtuous conduct, drawn to intoxicants, distressed by hard labour, knowledge of geography and atmospheric/space science, aversion to one's own people and to paternal-side relatives. No caste, occupation-status, slavery/servitude, or remedy content is present."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Sārāvalī 22.34-35',
            "gist": 'Sārāvalī reads a Sun-in-Leo native as one who overcomes rivals and adversaries — quick to anger, yet given to notable, memorable deeds. The text assigns a temperament drawn to forests, hills and fortified heights, and describes the native as enthusiastic, valorous, bright in appearance, meat-eating and formidable. Sārāvalī further reads them as restive, durably strong, talkative, abundant in wealth, and famous — rising to "kingship," which here reads as commanding authority and high standing rather than literal royalty.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "One dated referent: 'be a king' is preserved and glossed as authority/leadership/high standing in its ~10th-c. context, per §5 archaic-referent. No caste, gender/marriage, slavery, death/disease/poverty, occupation-status, or remedy content is present in the verse, so every other theme (temperament, valour, appearance, wandering wild/fortified terrain, meat-eating, wealth, fame) ships clean. 'Meat-eating' is kept as the text's plain descriptive trait, not a caste verdict, so it stays clean (no §5 diet class). Framed by attribution ('the text reads…'/'Sārāvalī assigns…'), dated, never as the reader's fate. Forests/hills/fortresses kept as descriptive geography, not a social-rank referent."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Sārāvalī 22.42–43',
            "gist": 'Sārāvalī (22.42–43, ~10th c.) reads a Virgo Sun as giving a delicate, soft build and a somewhat frail, low-stamina constitution (a physical reading, not medical advice). It casts the native as a scholar — learned, an expert writer, and skilled in sacred/classical learning ("the Vedas" in its idiom), in song, and in playing instruments. Sārāvalī also assigns a practical aptitude for repairing driven vehicles (the conveyances of its day), a devout and respectful temper — service to the divine and to elders — and soft, kindly speech.',
            "adaptation": {"classes": ['gender', 'archaic', 'health'], "action": 'neutralise + gloss + historicise',
                            "note": "Three §5 actions apply. Gender/marriage (neutralise): the 'physique akin to that of a female' claim is a reading of the NATIVE's own body, not a spouse-judgement, so a real structural principle survives — it is neutralised to a partner-neutral constitutional reading (delicate/soft build), dropping the gendered comparison; refuse is not warranted here. Archaic-referent (gloss): 'the Vedas' is kept and rendered as the sacred/classical learning of its time, and 'driven vehicles' as the carts/conveyances of its era — both preserved in-context, not modernised into false specifics. Death/disease (historicise, keep-not-fated): 'weak' is kept as the text's stated mild constitutional effect, cited and dated to the ~10th-c. view, framed not as fate and with a not-medical-advice note. No caste, slavery/servitude/rank, remedy/ritual, or occupation-STATUS content is present — the scholar/writer/musician/vehicle-repair/service/soft-speech material carries no high-low ranking and ships clean."},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Sārāvalī 22.44-45',
            "gist": 'Sārāvalī (Kalyāṇa Varma, ~10th c.) reads the Sun in Libra as a hard placement. It assigns the native recurring frustration and setbacks, things coming to ruin, and heavy expenditure or losses, along with a pull toward living in foreign or distant places driven by hardship rather than choice. In temperament it reads the native as ill-natured and mean, short on warmth or affection, as envious, and as prone to taking on other people\'s work; it also flags a leaning toward relationships with people who are already partnered. It ties the livelihood to dealing in gold and other metals, notes neglect of personal cleanliness, and foresees falling out of favor with those in authority ("royal contempt" in its idiom). It closes by calling the native pragalbha — which this edition renders "shameless," though the same word equally means bold, eminent or accomplished, so the sense is genuinely two-sided. This is a ~1,000-year-old text\'s stated reading, cited and dated — not a verdict on any person and not a statement of fate.',
            "adaptation": {"classes": ['health', 'gender', 'occupation', 'archaic'], "action": 'neutralise+gloss',
                            "note": "Ships with adaptations; no full omissions and no refusals (no caste line, no spouse-judgement, no death-timing). gender-marriage: 'co-habits with the wives of others' neutralised to partner-neutral 'relationships with people who are already partnered' — this is the native's OWN conduct, so the structural principle (transgressive/illicit relationships) survives while the gendered 'wives' framing is dropped; not a judgement about a spouse's looks/character, so neutralise, not refuse. occupation-status: 'lives by selling gold and other metals' kept as the livelihood theme (metals/gold trade); any low/mean-status coloring dropped (the source states no explicit rank here, so the flag is precautionary). archaic-referent: 'royal contempt' glossed as disfavor of those in authority/the powerful of its day (king → authority in context). death-disease-poverty: frustration, ruin/destruction and heavy expenditure/loss kept as the TEXT'S stated effect, framed as the ~10th-c. reading and dated, never as fate — a loose class fit since the verse has no death or disease, only loss (the poverty/loss sub-element); not medical/financial advice. Character traits (ill-natured/mean, jealous, unaffectionate, unclean, 'fond of doing others' work') are 'clean' per policy and kept faithfully as the text's reading. Translator's 'shameless' flagged as ambiguous per the source note: pragalbha also = bold/eminent/illustrious/energetic/skilful, so rendered explicitly two-sided rather than as a fixed negative."},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Sārāvalī 22.46-47',
            "gist": 'Sārāvalī (22.46–47, ~10th c.) reads a Scorpio Sun as a combative, war-prone temperament — irascible, quarrelsome and cruel — and as standing apart from the religious/scriptural path of its day (glossing the verse\'s "Vedic path"). It assigns a sharply drawn character: dishonest, dull-witted, miserly, and given to a wayward course and disreputable company (neutralising the verse\'s "attached to mean women"). On marriage, the verse\'s gendered verdict on a spouse\'s character ("base/wicked wife") is not something we forecast — a partner\'s character is not the native\'s to predict; its alternate sense, "loss of wife," is kept partner-neutrally as loss or strain around marriage/partnership. It also reads the native as exposed to harm from weapons, fire and poison, and as ill-fortuned in matters of the parents. This is the text\'s dated view — cited, not asserted as your fate, and not medical advice.',
            "adaptation": {"classes": ['gender', 'archaic', 'health'], "action": 'neutralise+refuse+gloss',
                            "note": "Gender/marriage: REFUSED the value-laden 'base/wicked wife' spouse-character verdict (a spouse's character is not the native's to predict — §5 'wife's character' -> refuse), and the gist now states that refusal explicitly rather than folding it into a marital-strain prediction; NEUTRALISED 'loss of wife' -> partner-neutral loss/strain around marriage/partnership (the structural principle survives) and 'attached to mean women' -> drawn to disreputable company/relationships. Archaic-referent: 'away from the Vedic path' kept but GLOSSED as the religious/scriptural path of its time. Death/disease/poverty: 'troubled by weapons, fire, poison' and 'unfortunate in respect of parents' kept as the text's stated ~10th-c. effects, framed as attribution not fate, with a not-medical-advice note; no outright death-timing present, so nothing to refuse there. Remaining traits (war-prone, irascible, cruel, liar, dunce, miser, quarrelsome, wayward course) are character claims shipped plainly as the text's dated view. No caste, slavery/servitude, occupation-status, or remedy content present in this verse."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Sārāvalī 22.48-49',
            "gist": 'Sārāvalī (22.48-49, ~10th c.) reads the native with the Sun in Sagittarius as prosperous and wealthy, learned, and well-regarded by those in authority — its phrase "dear to the king" being the idiom for standing well with rulers and the powerful of its day. It assigns reverence toward the sacred and toward the learned/priestly class of its time ("gods and brahmins"), and skill in martial disciplines — the handling of weapons and archery — as well as in the management of elephants, the prestige animals and instruments of state in that era. The text further reads the native as approachable and dependable, honourable, even-tempered and peaceable, of broad and well-formed physique, supportive of relatives, and energetic.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "Three archaic referents are preserved and glossed rather than dropped: 'dear to the king' -> standing well with authority/rulers of its context; 'brahmins' -> the learned/priestly class of its time; 'breeding elephants' -> managing the prestige animals and instruments of state of its era. The 'respect gods and brahmins' clause is reverence TOWARD the priestly class, not a caste verdict ON the native, so it is glossed (per the archaic-referent rule), not omitted under the caste-OMIT rule. No caste verdict on the native, no gender/marriage judgement, no slavery/rank, no occupation-status, no death/disease/poverty, and no remedy/ritual content is present. 'Broad and beautiful physique' describes the native's own body (self-description, clean), not a spouse's looks, so nothing is refused or neutralised. All remaining themes (wealth, learning, honour, peaceableness, martial skill, approachability, helpfulness to kin, energy) are clean and ship plainly, attributed and dated to ~10th c."},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Sārāvalī 22.56–57',
            "gist": "Sārāvalī (22.56–57, ~10th c.) reads the native with the Sun in Capricorn as of a low, base disposition — acquisitive, timid, and changeable of mind, drawn to ill-chosen company and fond of wandering. It has them make their way through modest, hard-won work while taking on many and varied undertakings, yet describes them as physically weak, distant from their kin, and — through quarrels with relatives — liable to heavy losses, with a hearty appetite. This is the text's ~10th-century reading of the placement, not a statement of fate, and not medical advice.",
            "adaptation": {"classes": ['gender', 'occupation', 'health'], "action": 'neutralise (gender/marriage) + drop-status (occupation) + keep-cited-not-fated + health-disclaimer (death/disease/poverty); all remaining traits clean',
                            "note": "Gender/marriage: 'interested in bad women' neutralised to partner-neutral 'drawn to ill-chosen company' — this is the native's own inclination toward unwholesome associations (a real structural principle), not a value-laden prediction about a spouse's looks/character, so neutralise (not refuse) is the correct §5 action; the gendered value-judgement is dropped. Occupation-status: 'advance with mean jobs' kept as the livelihood-through-labor theme with the low-status judgement dropped ('modest, hard-won work'). Death/disease/poverty: 'will lose everything due to conflicts with relatives' and 'weak' retained as the text's stated effects, cited and dated, framed as the ~10th-c. view rather than fate; an explicit 'not medical advice' disclaimer is added per §5 for the weakness/poverty content. No outright death-timing appears, so nothing is refused. Remaining traits (base/lowly, greedy, timid, fickle-minded, fond of wandering, endowed with various deeds, devoid of relatives, voracious eater) are clean character/temperament readings, retained and attributed as 'the text reads the native as…', never 'you will'. No caste verdict, slavery/servitude/rank, archaic referent, or remedy content is present in the verse."},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Sārāvalī 22.64–65',
            "gist": 'Sārāvalī reads the Sun in Aquarius as marking a native of great physical strength and courage, but with a short, quick temper. It assigns a nature that is steadfast and firm in its undertakings yet inconstant in friendship, alongside traits it frames unfavourably: fraudulent dealing, miserliness, carelessness about personal cleanliness, and being disliked by learned people. On fortune, the text describes benefit coming through one\'s partner and the domestic sphere [neutralised from the verse\'s "fortunate through housewives"], while otherwise assigning modest wealth and a discontented, unhappy state. It also states — as a ~10th-century reading of the placement, not a prediction and not medical advice — a proneness to heart ailments.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "Verse mixes one gendered fortune-clause with health and wealth content; the rest is clean temperament/character. GENDER (§5 gender & marriage): 'fortunate through housewives' neutralised to partner-/household-neutral — the structural principle (fortune via the marital/domestic sphere) survives, the gendered category-claim is dropped; correctly NOT a refuse case, since it is a fortune clause about the native rather than a value-laden judgement about a category of women. DISEASE (§5 disease timing): 'heart diseases' kept as the text's dated stated-effect, framed as a ~10th-c. view not as fate, with an explicit not-medical-advice disclaimer and no death-timing. POVERTY: 'little wealth' and the emotional 'miserable' kept as dated stated-effects, not fate. No caste, servitude/rank, occupation-ranking, remedy/ritual, or death-timing content present — nothing omitted or refused. Remaining traits (strength/courage, short temper, firmness in activity, inconstant friendship, fraudulence, uncleanliness, miserliness, disliked by the learned) ship clean under dated attribution framing."},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Sārāvalī 22.66-67',
            "gist": "Sārāvalī (~10th c.) reads the Sun in Pisces as marking a friendly, sociable temperament with a strong acquisitive drive — inclined to accumulate wealth and to enjoy pleasure and companionship — together with cheerfulness and learning. It assigns the capacity to overcome many rivals and pronounced prosperity: the native is read as wealthy, endowed with a partner and good children, and — in the text's dated household terms — attended by servants. It ties material gain especially to commerce carried across sea and river (maritime/riverine trade). On character it assigns eloquent, persuasive speech coupled with a tendency to untruth. As the text's dated somatic note — its stated effect, not a prediction and not medical advice — Sārāvalī flags a susceptibility to ailments of the genital/private region. It also assigns many siblings (co-born).",
            "adaptation": {"classes": ['gender', 'offspring', 'slavery/servitude/rank', 'health', 'occupation/commerce'], "action": 'neutralise+historicise',
                            "note": "Multi-class entry; ships with the §5 historical-context badge. NEUTRALISE gender/marriage: 'fond of women' -> pleasure-/company-loving inclination (the native's sensual/sociable disposition survives as a structural principle; it is a judgement about the native, not a value-laden claim about a category of women, so neutralise is correct rather than refuse); 'endowed with wife' -> endowed with a partner. NEUTRALISE offspring: 'good sons' -> good children. HISTORICISE slavery/servitude/rank: 'servants' retained only as a dated marker of household prosperity, badged, not endorsed (§5 permits omit or historicise). DEATH/DISEASE: 'diseases of the private parts' KEPT as the text's dated, cited stated-effect, framed NOT as fate and NOT as medical advice; no death-timing present, so no refusal triggered. OCCUPATION/COMMERCE: 'wealth via sea/river transactions' kept as theme with no high/low status ranking to drop. CLEAN and kept plainly: friendly, tendency to amass, happy, learned, overcomes many enemies (violent 'destroy' softened to 'overcome', theme intact), wealthy/rich, eloquent-but-untruthful (character trait, not caste/gender), many co-born/siblings. No caste verdict, no remedy/ritual/gemstone, and no death-timing appear in this verse, so none required omission or refusal."},
            "confidence": "corroborated",
        },
    },
    'moon': {
        0: {  # Aries
            "citation": 'Sārāvalī 23.1',
            "gist": 'Sārāvalī assigns a golden complexion, enduring wealth, and no siblings, and reads the native as brave, self-respecting, auspicious, prosperous and amorous, though changeable of mind and one who prizes honour above riches. Bodily marks: weak legs, poor nails, sparse hair, reddish hands and feet, round eyes. Friendly by disposition yet uneasy near rivers and wells, and liable to head injuries. The text foresees a large progeny and describes the native as readily swayed by a partner. (Sārāvalī 23.1)',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Won over by women' neutralised to being readily swayed by a partner; 'more sons' rendered as progeny-neutral; remaining character and body traits kept clean."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Sārāvalī 23.8',
            "gist": 'Sārāvalī reads the native as large-hearted and very charitable, famous and brilliant, discerning of good from bad, and forbearing, with happiness that grows in the middle and later stretches of life. Physically: short hair, an amorous nature, bull-like eyes, a strong waist, feet, shoulders and face, marks on the flank and back, and a graceful gait. The text foresees a progeny weighted toward daughters. (Sārāvalī 23.8)',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'More daughters' rendered as a progeny-neutral prediction (progeny weighted toward daughters); rest kept clean."},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Sārāvalī 23.16',
            "gist": 'Sārāvalī assigns a prominent nose and dark eyes, a long, sinewy body and a fish-line in the palm; the text reads the native as highly intelligent, splendid, cheerful and jocular, an eloquent speaker skilled in poetry and the arts of love, and fond of worldly pleasures. It also indicates being raised amid two mother-figures and a wide, easy sociability, and describes the native as readily swayed by a partner. (Sārāvalī 23.16)',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Won over by women' neutralised to being readily swayed by a partner; 'two mothers' kept as a structural family reading (two mother-figures); 'befriends neuters' neutralised to broad sociability, dropping the third-gender categorisation; rest clean."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Sārāvalī 23.23',
            "gist": "Sārāvalī reads the native as fortunate and brave, blessed with home, friends, travel and knowledge of astrology; sensuous, grateful, truthful and passionate, often living abroad, drawn to water and flowers and to building houses and wells. It places the native in a role of counsel and authority (a 'minister' in its idiom), with a hairy body and a prominent neck. (Sārāvalī 23.23)",
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'A minister' glossed as a role of counsel/authority in the text's own idiom; rest kept clean."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Sārāvalī 23.30',
            "gist": 'Sārāvalī assigns sturdy bones, sparse hair, a wide face and small yellowish eyes, a broad chest and majestic looks; the text reads the native as brave, dutiful, charitable yet harsh, respectful to the mother, a flesh-eater who resorts to forests and hills, with a small progeny. As a dated bodily reading it notes a proneness to hunger and thirst, stomach complaints and tooth decay (not fate, not medical advice). (Sārāvalī 23.30)',
            "adaptation": {"classes": ['gender', 'health'], "action": 'refuse; neutralise; keep-as-dated-effect',
                            "note": "'A hater of women' refused and dropped as a blanket gendered verdict; 'few sons' neutralised to a small progeny (now stated in the gist); hunger/thirst/stomach/tooth kept only as the text's dated stated effect, cited, not fate or medical advice; 'seeks union in forests and hills' rendered neutrally as resorting to forests and hills rather than injecting 'solitude'; rest clean."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Sārāvalī 23.37',
            "gist": "Sārāvalī reads the native as learned and pure, an eloquent, truthful speaker and a teacher of scripture, valorous, forgiving, kind to all beings, interested in others' affairs and fortunate; physically graced with long hands, an attractive face and body, and fine teeth, eyes and ears. It foresees a progeny weighted toward daughters. (Sārāvalī 23.37)",
            "adaptation": {"classes": ['gender'], "action": 'refuse; neutralise',
                            "note": "'Addicted to women' refused and dropped as a value-laden pursuit of a whole sex; 'more daughters but not many sons' neutralised to a progeny-neutral prediction; the teaching/preceptor role kept as a plain livelihood; rest clean."},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Sārāvalī 23.44',
            "gist": 'Sārāvalī assigns an elevated nose, broad eyes, an unassuming face and a lean body; the text reads the native as valorous, skilful in work, reverent toward the gods and the wise, helpful to kin and generous with grain, holding cattle, land and varied wealth, though not firm of disposition. It foresees multiple marriages and describes the native as readily swayed by a partner. (Sārāvalī 23.44)',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Many wives' neutralised to multiple marriages/partnerships (structural union reading); 'conquered by women' neutralised to being readily swayed by a partner; rest clean."},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Sārāvalī 23.51',
            "gist": 'Sārāvalī reads the native as miserly, cruel in action, industrious and valorous, without close kin and given to intense passion; physically, well-grown thighs, a coarse frame and nose, a marred chin and nails but beautiful eyes, a large abdomen and head. It notes an acquisitive streak toward what belongs to others and desire that wanders outside the partnership. As dated stated effects it records frailty in childhood and warns of losing wealth through the anger of authority (a ruler, in its idiom). (Sārāvalī 23.51)',
            "adaptation": {"classes": ['occupation', 'gender', 'health', 'archaic'], "action": 'clean; neutralise; keep-as-dated-effect; gloss',
                            "note": "'A thief' stripped of the criminal label and kept only as an acquisitive theme; 'fond of others' wives' neutralised to wandering desire outside the partnership; 'sickly in childhood' kept as the text's dated stated effect, cited; 'royal wrath' glossed as the anger of authority; miser/cruel kept as plain character words."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Sārāvalī 23.58',
            "gist": 'Sārāvalī assigns a short stature, round eyes, a large heart, waist and hands, prominent shoulders and neck, and strong bones, neck and lips; the text reads the native as very strong and courageous, a good speaker versed in the arts and in confidential matters, dwelling near water, attached to relatives, grateful and distinguished. (Sārāvalī 23.58)',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No policy-flagged clauses; body and character traits kept as plain, non-fatalistic readings.'},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Sārāvalī 23.65',
            "gist": 'Sārāvalī reads the native as a singer and poet, distinguished and famous, fond of truth and charity, but irascible, amorous, shameless, unkind, very miserly and not very enthusiastic; averse to cold, with a stout body, beautiful eyes yet a lean frame, round thighs, and a long neck and ears. (Sārāvalī 23.65)',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No policy-flagged clauses; singer/poet kept as neutral vocations and the character words (irascible, miserly, unkind) carry no policy class.'},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Sārāvalī 23.72',
            "gist": 'Sārāvalī assigns an elevated nose, a rough, uneven body, stout hands, legs and head, ugly or ailing eyes, a bright face and a prominent waist; the text reads the native as an artisan, given to intoxicants, ill-disposed of mind, averse to the virtuous and not virtuous himself. It states a tendency to gain by illegitimate means and, as a dated stated effect, hardship and poverty (not fate). (Sārāvalī 23.72)',
            "adaptation": {"classes": ['occupation', 'health'], "action": 'clean; keep-as-dated-effect',
                            "note": "'Gains through illegitimate means' kept as a livelihood theme with the moral ranking softened; 'ugly or diseased eyes' and 'miserable and very poor' kept only as the text's dated stated effects, cited, not fate; 'artisan' kept as a neutral vocation; 'not himself virtuous' restored as a plain character clause; rest clean."},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Sārāvalī 23.79',
            "gist": 'Sārāvalī reads the native as expert in the fine arts and music, learned in the śāstras, very religious and virtuous, a polite speaker able to win over even the hostile, endowed with a beautiful body, happiness and wealth, somewhat irascible, with a large head and a love of sailing, and liberal. It places the native in service to authority (a ruler, in its idiom), notes an amorous nature inclined to several relationships, and describes the native as readily swayed by a partner. (Sārāvalī 23.79)',
            "adaptation": {"classes": ['gender', 'slavery', 'archaic'], "action": 'neutralise; historicise; gloss',
                            "note": "'Consorts with many women' neutralised to an amorous nature inclined to several relationships; 'won over by women' neutralised to being readily swayed by a partner; 'serves the king' historicised and glossed as service to authority of its time; rest clean."},
            "confidence": "corroborated",
        },
    },
    'mars': {
        0: {  # Aries
            "citation": 'Sārāvalī 25.1-2',
            "gist": "Sārāvalī reads the native as radiant, truthful and valorous, drawn to bold and martial undertakings and to positions of command (in the text's terms a leader over a village, band or armed force); high-spirited and generous, prosperous in cattle, goats and grain, and fierce in temper.",
            "adaptation": {"classes": ['archaic', 'gender'], "action": 'gloss+refuse',
                            "note": "Glossed the 'king / army chief / head of a village or band' rank as leadership and authority of its era. Refused the value-laden gendered clause 'consorts with many women' (pursuit of a whole sex). Kept the character, valour and cattle/grain wealth as clean."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Sārāvalī 25.3-4',
            "gist": 'Sārāvalī assigns a voracious appetite, scant wealth and few children, a jealous and distrustful nature that keeps wide company yet trusts no one, roughness in play and very harsh speech, a fondness for music, and a sinful, quarrelsome bent that estranges kin and, the text says, brings the family disrepute.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'refuse+neutralise',
                            "note": "Refused the value-laden gendered clause 'breaks the vows of chaste women'. Neutralised 'few sons' to few children. Kept 'little wealth' as the text's dated, cited stated-effect, not a fated verdict. Plain character words (jealous, harsh, sinful) kept clean; 'keeps company with many' and 'does not trust others' preserved."},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Sārāvalī 25.5-6',
            "gist": 'Sārāvalī reads the native as brilliant and able to endure hardship, deeply learned and versed in the rules of poetry, skilled in many fine arts, fond of foreign travel, of virtuous disposition and high intelligence, warm toward children and friends, and devoted to a variety of undertakings.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "Neutralised 'well-disposed to sons' to children; the surviving principle is a warm familial disposition. Everything else (learning, arts, travel, intelligence) is clean."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Sārāvalī 25.7-8',
            "gist": "Sārāvalī assigns a life often spent under others' roofs and eating at others' tables, with fine food and clothing from early childhood; wealth is said to come through farming and through water, yet the text states bodily frailty and ill health and a temperament of recurring anguish and distress.",
            "adaptation": {"classes": ['health', 'occupation'], "action": 'clean+historicise',
                            "note": "Kept 'deformed / sickly' as the text's dated, cited stated-effect, framed as a ~10th-century view, not fate and not medical advice. Livelihood via agriculture kept as a neutral theme (no status ranking present to drop)."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Sārāvalī 25.9-10',
            "gist": 'Sārāvalī reads the native as impatient yet valorous, acquisitive toward what belongs to others, a forest-dweller fond of meat who hunts snakes and beasts, sparing in charity and ceaselessly busy at work; the text states an early loss in partnership and little or no progeny.',
            "adaptation": {"classes": ['occupation', 'gender'], "action": 'neutralise+clean',
                            "note": "Kept the acquisitive/rapacious theme but dropped any moral-status ranking on it. Rendered 'loses a first spouse' as a partner-neutral structural note and 'bereft of children' as a progeny-neutral stated effect, not fate. Impatience, valour and forest life kept clean."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Sārāvalī 25.11-12',
            "gist": 'Sārāvalī assigns an honourable and splendid person, soft and sweet in speech, fond of intimacy, music, bathing and adornment, and skilled in the śāstras and fine arts; yet the text states he is never wealthy, spends on many fronts, is not very bold, and greatly fears his adversaries.',
            "adaptation": {"classes": ['health'], "action": 'clean+historicise',
                            "note": "Kept 'never rich' as the text's dated, cited stated-effect, not a fated verdict on wealth. 'Fond of union' rendered as fondness for intimacy (no value-laden gendered judgement). Remainder clean."},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Sārāvalī 25.13-14',
            "gist": 'Sārāvalī reads the native as a wanderer and able speaker, fortunate but with few kin, drawn to conflict, earning through liquor-dealing and unsteady ventures where wealth comes and then slips away; the text also states an affliction to one limb and an early loss in partnership.',
            "adaptation": {"classes": ['occupation', 'health', 'gender'], "action": 'clean+neutralise+historicise',
                            "note": "Dropped the 'bad / disreputable' moral-status ranking while keeping the liquor-trade and venture livelihood theme. Kept 'deformed in a limb' as the text's dated stated-effect. Rendered 'loses a first spouse' as a partner-neutral stated note."},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Sārāvalī 25.15-16',
            "gist": 'Sārāvalī assigns a trader drawn to Vedic learning and to war, skilful in his tasks yet highly sinful and given to grave wrongdoing: a ringleader of an outlaw band, treacherous to enemies, disposed to killing, unhelpful and a bearer of tales; endowed with land, a spouse and children, but the text states he is troubled by poison, fire, weapons and wounds.',
            "adaptation": {"classes": ['occupation', 'gender', 'health'], "action": 'neutralise+clean+historicise',
                            "note": "Kept the outlaw/thieving theme ('leader of thieves') but dropped its moral-status ranking. Kept the plain character words undiluted (highly sinful, treacherous, disposed to killing, talebearer). Kept spouse and children as neutral family terms. Kept the poison/fire/weapon/wound afflictions as the text's dated stated-effect, not fate or death-timing."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Sārāvalī 25.17-18',
            "gist": 'Sārāvalī reads the native as a hardened warrior of his age, pictured with chariots, elephants and troops loosing arrows on the foe, harsh-spoken, crafty and estranged from others, thriving on hard work yet squandering contentment and money through anger, and slighting his elders; the text also states many wounds and a lean, wasted frame.',
            "adaptation": {"classes": ['health', 'archaic'], "action": 'gloss+historicise',
                            "note": "Glossed the chariot/elephant/army imagery as the martial vocation of its era. Kept 'many wounds / emaciated' as the text's dated, cited stated-effect. Harshness, craftiness and anger kept clean."},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Sārāvalī 25.19-20',
            "gist": "Sārāvalī assigns a wealthy, fortunate and contented native of excellent character and wide renown, a leader or ruler in the text's terms, victorious in war, dwelling in his own land, independent, protective, virtuous, and engaged in many undertakings.",
            "adaptation": {"classes": ['archaic', 'gender'], "action": 'gloss+refuse',
                            "note": "Glossed 'army chief or king' as leadership and authority of its era. Refused the value-laden spouse verdict 'a good spouse' (a judgement on a partner's character). Wealth, fame and virtue kept clean."},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Sārāvalī 25.21-22',
            "gist": 'Sārāvalī reads the native as cold and impure in nature, spiteful, jealous and untruthful, aged and unappealing in looks with heavy body-hair and impaired speech; the text states lost wealth, gambling losses, straitened means, a fondness for liquor, and general misfortune.',
            "adaptation": {"classes": ['health', 'occupation'], "action": 'omit+clean+historicise',
                            "note": "Omitted the doom verdict 'a bad end' (refused as fatal-outcome prediction). Dropped the 'wretched' status-ranking of the livelihood while keeping the straitened-means theme. Kept lost wealth, gambling losses and misfortune as the text's dated, cited stated-effects, not fate. Appearance and character terms kept as the text's plain stated description."},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Sārāvalī 25.23-24',
            "gist": 'Sārāvalī assigns a native dwelling in foreign lands and famous there, yet slighted by his own kin, low-spirited and much troubled, unkind, covetous, disrespectful of elders and fond of flattery, who through his own cunning forfeits his wealth; the text also states illness and children who remain indifferent.',
            "adaptation": {"classes": ['health', 'gender'], "action": 'historicise+neutralise+clean',
                            "note": "Kept 'troubled by diseases' and the loss of wealth as the text's dated, cited stated-effects, not fate or medical advice. Kept 'indifferent children' as a progeny-neutral relational note. Character words (unkind, covetous) and foreign-residence/fame kept clean."},
            "confidence": "corroborated",
        },
    },
    'mercury': {
        0: {  # Aries
            "citation": 'Sārāvalī 26.1-2',
            "gist": 'Sārāvalī assigns Mercury in Aries a quarrelsome, uncompromising temper joined to real learning and a love of music, dance and writing; the text reads the native as wicked, untruthful and pleasure-attached, given to fabrication, eating heartily, and — in its own dated telling — losing hard-earned money and running into debt and even imprisonment, with a mind that swings between fickle and firm.',
            "adaptation": {"classes": ['health'], "action": 'clean',
                            "note": "No caste or gender clauses present. The plain character words (quarrelsome, wicked, untruthful) are kept unsoftened — the source's 'wicked' had been softened to 'clever', which is both a softening and a fabrication, so 'wicked' is restored and 'clever' removed. Wealth-loss, debt and imprisonment are retained as the text's dated stated effects under the site's non-fatalist voice, not as predictions; the bare physical descriptor 'emaciated' is dropped for concision."},
            "confidence": "corroborated",
        },
        1: {  # Taurus
            "citation": 'Sārāvalī 26.3-4',
            "gist": 'Sārāvalī assigns Mercury in Taurus a skilful, notably liberal and famous nature grounded in scriptural learning; the text reads the native as firm in disposition, fond of exercise, fine robes, ornaments and garlands, honest in earning wealth, and a soft, sweet speaker.',
            "adaptation": {"classes": ['gender'], "action": 'refuse',
                            "note": "The 'chaste spouse' clause is a chastity verdict on the partner and is refused and omitted; everything else is kept clean."},
            "confidence": "corroborated",
        },
        2: {  # Gemini
            "citation": 'Sārāvalī 26.5-6',
            "gist": 'Sārāvalī assigns Mercury in Gemini an auspicious look, sweet and able speech, and genuine affluence; the text reads the native as honourable, self-denying, fond of debate, learned in the scriptures, a poet, independent, widely liked, very munificent and capable at work — with more than one marriage and many children and friends.',
            "adaptation": {"classes": ['gender'], "action": 'neutralise',
                            "note": "'Two spouses' neutralised to more-than-one marriage and 'many sons' to many children, both partner/progeny-neutral where the structural principle survives; the rest is clean."},
            "confidence": "corroborated",
        },
        3: {  # Cancer
            "citation": 'Sārāvalī 26.7-8',
            "gist": "Sārāvalī assigns Mercury in Cancer a learned but restless cast — the text reads the native as drawn to foreign residence and music, fickle, talkative, argumentative and at odds with relatives, of unsteady disposition yet interested in many pursuits and a good poet, popular on the strength of ancestral fame, and (in the text's dated telling) losing wealth through quarrels with others.",
            "adaptation": {"classes": ['health'], "action": 'clean',
                            "note": "Wealth-loss through enmity is retained as the text's dated stated effect, not fate; the remainder is plain character kept clean."},
            "confidence": "corroborated",
        },
        4: {  # Leo
            "citation": 'Sārāvalī 26.9-10',
            "gist": "Sārāvalī assigns Mercury in Leo worldly fame paired with weak judgement — the text reads the native as untruthful, poor in memory, wealthy but not robust, beset by family strife, independent yet mean in conduct, working in others' employ, childless, and opposed to his own kin while favourable to outsiders.",
            "adaptation": {"classes": ['slavery', 'gender'], "action": 'historicise',
                            "note": "'A dependent worker' is historicised to working in others' employ, dropping the servile framing while keeping the livelihood theme; 'devoid of children' is kept as a progeny-neutral stated effect; the rest is clean."},
            "confidence": "corroborated",
        },
        5: {  # Virgo
            "citation": 'Sārāvalī 26.11-12',
            "gist": 'Sārāvalī assigns Mercury in Virgo a virtuous, eloquent and skilful nature — the text reads the native as an exponent of writing and poetry, learned in the fine and mechanical arts, sweet-tempered and personable, the eldest of the family, honoured by the good, modest, argumentative, famous, charitable and strong.',
            "adaptation": {"classes": ['gender'], "action": 'refuse',
                            "note": "The 'not much virile' verdict on the impotence category is refused and omitted; 'liked by women' is neutralised to personable/well-liked; 'eldest son' and the remaining traits are kept clean."},
            "confidence": "corroborated",
        },
        6: {  # Libra
            "citation": 'Sārāvalī 26.13-14',
            "gist": 'Sārāvalī assigns Mercury in Libra an arts-loving, argument-ready and articulate nature — the text reads the native as a lavish spender with business in many directions, respectful to the wise, to guests, gods and elders, outwardly amiable and pious yet given to feigned service and fraud, fickle, and swinging between irritability and marked calm.',
            "adaptation": {"classes": [], "action": 'clean',
                            "note": 'No policy-flagged clauses; the plain character and livelihood traits are kept as written.'},
            "confidence": "corroborated",
        },
        7: {  # Scorpio
            "citation": 'Sārāvalī 26.15-16',
            "gist": 'Sārāvalī assigns Mercury in Scorpio a troubled, embittered cast — the text reads the native as beset by grief and adversity, hostile to the virtuous, wanting in truth, piety and shame, dull, miserly and secretive, keeping disreputable company, drawn to harsh punishment and to disreputable work, and inclined to irregular gains and debt.',
            "adaptation": {"classes": ['health', 'gender', 'occupation'], "action": 'neutralise',
                            "note": "'Consorts with wicked women' neutralised to keeping disreputable company; 'blameworthy jobs' and 'steals others' property' kept as a livelihood/acquisitive theme with the moral-status label dropped; trouble, grief and debt kept as the text's dated stated effects, not fate."},
            "confidence": "corroborated",
        },
        8: {  # Sagittarius
            "citation": 'Sārāvalī 26.17-18',
            "gist": 'Sārāvalī assigns Mercury in Sagittarius a distinguished, generous nature grounded in scriptural learning — the text reads the native as valorous and meditative, holding an advisory or priestly office (in the idiom of its day, a minister or family priest), foremost among his kin, very wealthy, given to sacred rites and teaching, a skilful speaker, charitable and expert in writing and the fine arts.',
            "adaptation": {"classes": ['archaic'], "action": 'gloss',
                            "note": "'Minister', 'family priest' and 'yajña' are glossed in context as the advisory/priestly roles and religious rites of their era; the rest is clean."},
            "confidence": "corroborated",
        },
        9: {  # Capricorn
            "citation": 'Sārāvalī 26.19-20',
            "gist": 'Sārāvalī assigns Mercury in Capricorn a mean, dull cast — the text reads the native as devoid of virtues, working under others, a restless day-dreamer and wanderer, a talebearer, untruthful, without relatives, unclean and timid, and (in its own dated telling) subject to many miseries.',
            "adaptation": {"classes": ['gender', 'slavery', 'health'], "action": 'refuse',
                            "note": "The 'impotent' verdict on the impotence category is refused and omitted; 'does others' work' is historicised to working under others, keeping the livelihood theme; 'many miseries' is kept as a dated stated effect; the rest is clean."},
            "confidence": "corroborated",
        },
        10: {  # Aquarius
            "citation": 'Sārāvalī 26.21-22',
            "gist": 'Sārāvalī assigns Mercury in Aquarius an ill-disposed cast — the text reads the native as wanting in good conduct and deeds, drawn to many religious observances yet abandoning worthy pursuits, slighted by others, impure and wicked, at odds with the partner, joyless, timid, and unclean though modest, and (in its own dated telling) very unfortunate.',
            "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                            "note": "'Inimical to spouse' is neutralised to marital discord / being at odds with the partner (partner-neutral); 'very unfortunate' and 'devoid of pleasures' are kept as the text's dated stated effects; the rest is clean."},
            "confidence": "corroborated",
        },
        11: {  # Pisces
            "citation": 'Sārāvalī 26.23-24',
            "gist": "Sārāvalī assigns Mercury in Pisces a well-conducted, pure and generally fortunate nature — the text reads the native as virtuous yet wanting in formal religion, living abroad, skilled at stitching, versed in the scriptures and fine arts though not in profane learning, and adept at turning others' resources to his own use, while (in the text's dated telling) childless and poor.",
            "adaptation": {"classes": ['gender', 'health', 'occupation'], "action": 'refuse',
                            "note": "The 'chaste spouse' chastity verdict is refused and omitted; 'proficient at appropriating others' wealth' is rendered as an acquisitive-livelihood theme with the moral-status label dropped; stitching is kept as a trade; issueless, poor and devoid-of-wealth are kept as the text's dated stated effects."},
            "confidence": "corroborated",
        },
    },
}
