"""
Sārāvalī of Kalyāṇa Varma (~9-10th c. CE), R. Santhanam tr. (Ranjan) — CLASSICAL tier.

The Sun in the 12 rāśis (Sārāvalī ch.22). Each entry is a site-authored, cited,
adaptation-classified GIST per docs/classical-sources-policy.md — a rendering, NOT a
reproduction of the copyrighted translation. Every gist was verified against the Vol 1
edition and independently checked for faithfulness, policy (§5), and non-fatalism.

adaptation.classes uses the §5 tags: caste / gender / slavery / occupation / health /
archaic (empty = clean). action/note record how each dated class was handled.
"""

SOURCE = {
    "id": "saravali", "text": "Sārāvalī", "author": "Kalyāṇa Varma",
    "date": "~9-10th c. CE", "translator": "R. Santhanam (Ranjan Publications)",
    "tier": "classical",
}

# graha key -> sign index (0=Meṣa … 11=Mīna) -> entry. Sun-in-sign complete (12/12).
SUN_IN_SIGN = {
    0: {  # Aries
        "citation": 'Sārāvalī 22.2-3',
        "gist": 'Sārāvalī (~10th c.) reads a native with the Sun in Aries — its sign of exaltation — as a scholar who expounds the meaning of the śāstras and wins fame in the arts; martial and fierce in temperament yet firmly attached to duty; fond of travel and roaming (a wandering the text ties to the exalted Sun); strong-boned, splendorous and physically strong; effective and valorous in deed. The text assigns the placement to rank and command — "Narendra," a king or leader in its own idiom — carrying an alternate classical reading as a healer able to cure poisons (a physician\'s calling). The same passage flags, in its period humoral framing, a leaning toward bilious (pitta) and blood-related disorders — recorded as the text\'s stated view of ~1,000 years ago, not as a medical prediction or as fate.',
        "adaptation": {"classes": ['archaic', 'health'], "action": 'gloss + historicise',
                        "note": "Two dated content-classes are present; the rest is clean. Archaic-referent ('king / Narendra') is glossed as authority and leadership in its context, and the alternate classical reading (curer of poisons / physician) is kept as a livelihood theme, not a status ranking. Disease ('bilious and bloody disorders') is kept as the text's stated humoral effect, cited and dated, framed as the ~10th-c. view and never as fate, with a not-medical-advice disclaimer — the §5 death/disease handling, correctly mapped to historicise. No caste, gender/marriage, slavery, occupation-status ranking, remedy, or death-timing content exists in the source, so nothing was wrongly omitted or wrongly retained. The scholarly / martial / dutiful / wandering / valour / vitality traits ship plainly."},
        "confidence": "corroborated",
    },
    1: {  # Taurus
        "citation": 'Sārāvalī 22.10–11',
        "gist": "Sārāvalī (22.10–11, ~10th c.) reads a Taurus Sun as someone the text calls beautiful — a variant reads fortunate/handsome — dignified in bearing and wise, with a lean, spare build, who nonetheless has hardships to endure. It credits the native with an abundance of fine things (good food, garlands, fine clothing and fragrances) and genuine skill in the arts of song, instrumental music and dance. As its own ~10th-century view — not fate, and not medical guidance — the text also flags a proneness to complaints of the face and eyes and a caution around water, and reads the native as having few children (neutralised from the text's 'few sons'). Sārāvalī 22.10–11 further voices an aversion toward 'barren (or confined) women'; that judgement is not reproduced here — it is a value-laden claim about a category of women, not a reading of the native.",
        "adaptation": {"classes": ['health', 'gender'], "action": "neutralise + refuse (disease/hazard kept as the text's dated stated-effect; remainder clean)",
                        "note": "Health/hazard items (disease of the face and eyes, emaciated/lean body, danger from water) are kept as the text's own dated stated-effect — framed as the ~10th-c. reading, not fate, with no medical claim. 'Few sons' is NEUTRALISED to 'few children': the son-preference is dropped, the progeny principle kept. The aversion to 'barren (or confined) women' is REFUSED as a value-laden gendered judgement about a class of women with no surviving neutral structural core. All remaining themes — beautiful/fortunate, decorum, wisdom, enduring hardship, being endowed with food/garlands/robes/scents, and skill in singing/instrumental music/dance — are CLEAN and ship plainly, attributed and dated. No caste, occupation-status, slavery, remedy, or archaic-referent content present; no death-timing."},
        "confidence": "corroborated",
    },
    2: {  # Gemini
        "citation": 'Sārāvalī 22.18-19',
        "gist": 'Sārāvalī reads a Gemini Sun native as a scholar — sweet in speech, well-conducted, modest, and affectionate, particularly toward their own children. The text assigns command of worldly, secular learning (which it explicitly frames as distinct from knowledge of Brahman, the Supreme Spirit — i.e. spiritual self-knowledge, not the brahmin caste) together with mastery of the śāstras, the traditional sciences and scriptures, and an aptitude for astrology. It reads the person as liberal (generous), skilful, exceedingly affluent, and fortunate, though only mediocre in physical appearance. In its own idiom it also assigns "two mothers," traditionally understood as being raised by two mother-figures — for example a birth mother alongside a second, foster or step-maternal figure.',
        "adaptation": {"classes": ['archaic'], "action": 'gloss',
                        "note": "Two non-clean items, both ARCHAIC-REFERENT, handled by GLOSS (not omission): (1) 'expert in profane/worldly knowledge as opposed to the knowledge of Brahman/the Supreme Spirit, and in the śāstras' — kept and rendered in context as command of secular learning held distinct from Brahman the Supreme Spirit (i.e. spiritual self-knowledge), plus mastery of the traditional śāstras. NB: 'Brahman' here is the metaphysical Absolute, NOT the brahmin varṇa — so this is religious-path framing (gloss), with NO caste verdict to omit. (2) 'two mothers' — kept and glossed as being raised by two mother-figures (e.g. birth mother plus a foster/step maternal figure), offered as illustration, not asserted as fact. Everything else ships CLEAN: scholar, sweet speech, good conduct, affection particularly toward one's own offspring (already offspring-neutral — no number-of-sons claim to neutralise), generosity, skill, exceeding affluence, mediocre appearance, fortune, modesty, and astrologer as a livelihood/aptitude (no high/low status ranking present, so occupation-status has nothing to drop — effectively clean). No caste, slavery/servitude, value-laden gendered, death/disease/poverty, or remedy content is present. Framed throughout as 'the text reads/assigns…' per attribution-over-endorsement, with the ~9–10th-c. date visible."},
        "confidence": "corroborated",
    },
    3: {  # Cancer
        "citation": 'Sārāvalī 22.26–27',
        "gist": 'Sārāvalī reads the Sun in Cancer as a temperament pulled two ways — restless and not steady of purpose in its undertakings, yet at bottom described as very steady in character. It assigns fame through "royal" qualities (glossed here as leadership and commanding presence in its period sense), a good-looking appearance, eloquence, honourableness, and adherence to virtuous principles. The text also reads the native as burdened and distressed by hard work, drawn to intoxicants, and knowledgeable in geography and the science of the atmosphere and skies. Relationally, it marks the native as at odds with their own people and averse to relatives on the paternal side. On marriage, the surviving structural note — strain or misfortune in the domain of marriage/partnership, which a strong full Moon is said to relieve — is kept partner-neutral; the text\'s judgement of a spouse\'s beauty or ugliness is not reproduced, since a partner\'s looks are not the native\'s to predict. On health, it assigns a classical humoral tendency toward phlegm- and bile- (kapha/pitta) related imbalance — a ~10th-century reading shown for completeness, framed as the text\'s view rather than fate, and not medical advice.',
        "adaptation": {"classes": ['gender', 'health', 'archaic'], "action": 'neutralise + refuse + historicise + gloss (remainder clean)',
                        "note": "GENDER/MARRIAGE ('unfortunate in respect of wife'; 'ugly wife'; full-Moon 'beautiful wife'): neutralised to a partner-neutral structural claim — strain/misfortune in the marriage-partnership domain, relieved by a strong full Moon; the spouse-beauty/ugliness verdict is REFUSED and not reproduced (a partner's looks/character are not the native's to predict). DEATH/DISEASE ('troubled by phlegm and bile'): kept as the text's stated humoral effect, cited + dated (~10th c.), framed as the text's view not fate, with a not-medical-advice note (historicise). ARCHAIC-REFERENT ('famous by royal qualities'): glossed as leadership/authority/commanding presence in its context, kept. All remaining themes are clean and ship plainly: unsteady-in-undertakings yet steady-in-nature, good looks, eloquence, honour, virtuous conduct, drawn to intoxicants, distressed by hard labour, knowledge of geography and atmospheric/space science, aversion to one's own people and to paternal-side relatives. No caste, occupation-status, slavery/servitude, or remedy content is present."},
        "confidence": "corroborated",
    },
    4: {  # Leo
        "citation": 'Sārāvalī 22.34-35',
        "gist": 'Sārāvalī reads a Sun-in-Leo native as one who overcomes rivals and adversaries — quick to anger, yet given to notable, memorable deeds. The text assigns a temperament drawn to forests, hills and fortified heights, and describes the native as enthusiastic, valorous, bright in appearance, meat-eating and formidable. Sārāvalī further reads them as restive, durably strong, talkative, abundant in wealth, and famous — rising to "kingship," which here reads as commanding authority and high standing rather than literal royalty.',
        "adaptation": {"classes": ['archaic'], "action": 'gloss',
                        "note": "One dated referent: 'be a king' is preserved and glossed as authority/leadership/high standing in its ~10th-c. context, per §5 archaic-referent. No caste, gender/marriage, slavery, death/disease/poverty, occupation-status, or remedy content is present in the verse, so every other theme (temperament, valour, appearance, wandering wild/fortified terrain, meat-eating, wealth, fame) ships clean. 'Meat-eating' is kept as the text's plain descriptive trait, not a caste verdict, so it stays clean (no §5 diet class). Framed by attribution ('the text reads…'/'Sārāvalī assigns…'), dated, never as the reader's fate. Forests/hills/fortresses kept as descriptive geography, not a social-rank referent."},
        "confidence": "corroborated",
    },
    5: {  # Virgo
        "citation": 'Sārāvalī 22.42–43',
        "gist": 'Sārāvalī (22.42–43, ~10th c.) reads a Virgo Sun as giving a delicate, soft build and a somewhat frail, low-stamina constitution (a physical reading, not medical advice). It casts the native as a scholar — learned, an expert writer, and skilled in sacred/classical learning ("the Vedas" in its idiom), in song, and in playing instruments. Sārāvalī also assigns a practical aptitude for repairing driven vehicles (the conveyances of its day), a devout and respectful temper — service to the divine and to elders — and soft, kindly speech.',
        "adaptation": {"classes": ['gender', 'archaic', 'health'], "action": 'neutralise + gloss + historicise',
                        "note": "Three §5 actions apply. Gender/marriage (neutralise): the 'physique akin to that of a female' claim is a reading of the NATIVE's own body, not a spouse-judgement, so a real structural principle survives — it is neutralised to a partner-neutral constitutional reading (delicate/soft build), dropping the gendered comparison; refuse is not warranted here. Archaic-referent (gloss): 'the Vedas' is kept and rendered as the sacred/classical learning of its time, and 'driven vehicles' as the carts/conveyances of its era — both preserved in-context, not modernised into false specifics. Death/disease (historicise, keep-not-fated): 'weak' is kept as the text's stated mild constitutional effect, cited and dated to the ~10th-c. view, framed not as fate and with a not-medical-advice note. No caste, slavery/servitude/rank, remedy/ritual, or occupation-STATUS content is present — the scholar/writer/musician/vehicle-repair/service/soft-speech material carries no high-low ranking and ships clean."},
        "confidence": "corroborated",
    },
    6: {  # Libra
        "citation": 'Sārāvalī 22.44-45',
        "gist": 'Sārāvalī (Kalyāṇa Varma, ~10th c.) reads the Sun in Libra as a hard placement. It assigns the native recurring frustration and setbacks, things coming to ruin, and heavy expenditure or losses, along with a pull toward living in foreign or distant places driven by hardship rather than choice. In temperament it reads the native as ill-natured and mean, short on warmth or affection, as envious, and as prone to taking on other people\'s work; it also flags a leaning toward relationships with people who are already partnered. It ties the livelihood to dealing in gold and other metals, notes neglect of personal cleanliness, and foresees falling out of favor with those in authority ("royal contempt" in its idiom). It closes by calling the native pragalbha — which this edition renders "shameless," though the same word equally means bold, eminent or accomplished, so the sense is genuinely two-sided. This is a ~1,000-year-old text\'s stated reading, cited and dated — not a verdict on any person and not a statement of fate.',
        "adaptation": {"classes": ['health', 'gender', 'occupation', 'archaic'], "action": 'neutralise+gloss',
                        "note": "Ships with adaptations; no full omissions and no refusals (no caste line, no spouse-judgement, no death-timing). gender-marriage: 'co-habits with the wives of others' neutralised to partner-neutral 'relationships with people who are already partnered' — this is the native's OWN conduct, so the structural principle (transgressive/illicit relationships) survives while the gendered 'wives' framing is dropped; not a judgement about a spouse's looks/character, so neutralise, not refuse. occupation-status: 'lives by selling gold and other metals' kept as the livelihood theme (metals/gold trade); any low/mean-status coloring dropped (the source states no explicit rank here, so the flag is precautionary). archaic-referent: 'royal contempt' glossed as disfavor of those in authority/the powerful of its day (king → authority in context). death-disease-poverty: frustration, ruin/destruction and heavy expenditure/loss kept as the TEXT'S stated effect, framed as the ~10th-c. reading and dated, never as fate — a loose class fit since the verse has no death or disease, only loss (the poverty/loss sub-element); not medical/financial advice. Character traits (ill-natured/mean, jealous, unaffectionate, unclean, 'fond of doing others' work') are 'clean' per policy and kept faithfully as the text's reading. Translator's 'shameless' flagged as ambiguous per the source note: pragalbha also = bold/eminent/illustrious/energetic/skilful, so rendered explicitly two-sided rather than as a fixed negative."},
        "confidence": "corroborated",
    },
    7: {  # Scorpio
        "citation": 'Sārāvalī 22.46-47',
        "gist": 'Sārāvalī (22.46–47, ~10th c.) reads a Scorpio Sun as a combative, war-prone temperament — irascible, quarrelsome and cruel — and as standing apart from the religious/scriptural path of its day (glossing the verse\'s "Vedic path"). It assigns a sharply drawn character: dishonest, dull-witted, miserly, and given to a wayward course and disreputable company (neutralising the verse\'s "attached to mean women"). On marriage, the verse\'s gendered verdict on a spouse\'s character ("base/wicked wife") is not something we forecast — a partner\'s character is not the native\'s to predict; its alternate sense, "loss of wife," is kept partner-neutrally as loss or strain around marriage/partnership. It also reads the native as exposed to harm from weapons, fire and poison, and as ill-fortuned in matters of the parents. This is the text\'s dated view — cited, not asserted as your fate, and not medical advice.',
        "adaptation": {"classes": ['gender', 'archaic', 'health'], "action": 'neutralise+refuse+gloss',
                        "note": "Gender/marriage: REFUSED the value-laden 'base/wicked wife' spouse-character verdict (a spouse's character is not the native's to predict — §5 'wife's character' -> refuse), and the gist now states that refusal explicitly rather than folding it into a marital-strain prediction; NEUTRALISED 'loss of wife' -> partner-neutral loss/strain around marriage/partnership (the structural principle survives) and 'attached to mean women' -> drawn to disreputable company/relationships. Archaic-referent: 'away from the Vedic path' kept but GLOSSED as the religious/scriptural path of its time. Death/disease/poverty: 'troubled by weapons, fire, poison' and 'unfortunate in respect of parents' kept as the text's stated ~10th-c. effects, framed as attribution not fate, with a not-medical-advice note; no outright death-timing present, so nothing to refuse there. Remaining traits (war-prone, irascible, cruel, liar, dunce, miser, quarrelsome, wayward course) are character claims shipped plainly as the text's dated view. No caste, slavery/servitude, occupation-status, or remedy content present in this verse."},
        "confidence": "corroborated",
    },
    8: {  # Sagittarius
        "citation": 'Sārāvalī 22.48-49',
        "gist": 'Sārāvalī (22.48-49, ~10th c.) reads the native with the Sun in Sagittarius as prosperous and wealthy, learned, and well-regarded by those in authority — its phrase "dear to the king" being the idiom for standing well with rulers and the powerful of its day. It assigns reverence toward the sacred and toward the learned/priestly class of its time ("gods and brahmins"), and skill in martial disciplines — the handling of weapons and archery — as well as in the management of elephants, the prestige animals and instruments of state in that era. The text further reads the native as approachable and dependable, honourable, even-tempered and peaceable, of broad and well-formed physique, supportive of relatives, and energetic.',
        "adaptation": {"classes": ['archaic'], "action": 'gloss',
                        "note": "Three archaic referents are preserved and glossed rather than dropped: 'dear to the king' -> standing well with authority/rulers of its context; 'brahmins' -> the learned/priestly class of its time; 'breeding elephants' -> managing the prestige animals and instruments of state of its era. The 'respect gods and brahmins' clause is reverence TOWARD the priestly class, not a caste verdict ON the native, so it is glossed (per the archaic-referent rule), not omitted under the caste-OMIT rule. No caste verdict on the native, no gender/marriage judgement, no slavery/rank, no occupation-status, no death/disease/poverty, and no remedy/ritual content is present. 'Broad and beautiful physique' describes the native's own body (self-description, clean), not a spouse's looks, so nothing is refused or neutralised. All remaining themes (wealth, learning, honour, peaceableness, martial skill, approachability, helpfulness to kin, energy) are clean and ship plainly, attributed and dated to ~10th c."},
        "confidence": "corroborated",
    },
    9: {  # Capricorn
        "citation": 'Sārāvalī 22.56–57',
        "gist": "Sārāvalī (22.56–57, ~10th c.) reads the native with the Sun in Capricorn as of a low, base disposition — acquisitive, timid, and changeable of mind, drawn to ill-chosen company and fond of wandering. It has them make their way through modest, hard-won work while taking on many and varied undertakings, yet describes them as physically weak, distant from their kin, and — through quarrels with relatives — liable to heavy losses, with a hearty appetite. This is the text's ~10th-century reading of the placement, not a statement of fate, and not medical advice.",
        "adaptation": {"classes": ['gender', 'occupation', 'health'], "action": 'neutralise (gender/marriage) + drop-status (occupation) + keep-cited-not-fated + health-disclaimer (death/disease/poverty); all remaining traits clean',
                        "note": "Gender/marriage: 'interested in bad women' neutralised to partner-neutral 'drawn to ill-chosen company' — this is the native's own inclination toward unwholesome associations (a real structural principle), not a value-laden prediction about a spouse's looks/character, so neutralise (not refuse) is the correct §5 action; the gendered value-judgement is dropped. Occupation-status: 'advance with mean jobs' kept as the livelihood-through-labor theme with the low-status judgement dropped ('modest, hard-won work'). Death/disease/poverty: 'will lose everything due to conflicts with relatives' and 'weak' retained as the text's stated effects, cited and dated, framed as the ~10th-c. view rather than fate; an explicit 'not medical advice' disclaimer is added per §5 for the weakness/poverty content. No outright death-timing appears, so nothing is refused. Remaining traits (base/lowly, greedy, timid, fickle-minded, fond of wandering, endowed with various deeds, devoid of relatives, voracious eater) are clean character/temperament readings, retained and attributed as 'the text reads the native as…', never 'you will'. No caste verdict, slavery/servitude/rank, archaic referent, or remedy content is present in the verse."},
        "confidence": "corroborated",
    },
    10: {  # Aquarius
        "citation": 'Sārāvalī 22.64–65',
        "gist": 'Sārāvalī reads the Sun in Aquarius as marking a native of great physical strength and courage, but with a short, quick temper. It assigns a nature that is steadfast and firm in its undertakings yet inconstant in friendship, alongside traits it frames unfavourably: fraudulent dealing, miserliness, carelessness about personal cleanliness, and being disliked by learned people. On fortune, the text describes benefit coming through one\'s partner and the domestic sphere [neutralised from the verse\'s "fortunate through housewives"], while otherwise assigning modest wealth and a discontented, unhappy state. It also states — as a ~10th-century reading of the placement, not a prediction and not medical advice — a proneness to heart ailments.',
        "adaptation": {"classes": ['gender', 'health'], "action": 'neutralise',
                        "note": "Verse mixes one gendered fortune-clause with health and wealth content; the rest is clean temperament/character. GENDER (§5 gender & marriage): 'fortunate through housewives' neutralised to partner-/household-neutral — the structural principle (fortune via the marital/domestic sphere) survives, the gendered category-claim is dropped; correctly NOT a refuse case, since it is a fortune clause about the native rather than a value-laden judgement about a category of women. DISEASE (§5 disease timing): 'heart diseases' kept as the text's dated stated-effect, framed as a ~10th-c. view not as fate, with an explicit not-medical-advice disclaimer and no death-timing. POVERTY: 'little wealth' and the emotional 'miserable' kept as dated stated-effects, not fate. No caste, servitude/rank, occupation-ranking, remedy/ritual, or death-timing content present — nothing omitted or refused. Remaining traits (strength/courage, short temper, firmness in activity, inconstant friendship, fraudulence, uncleanliness, miserliness, disliked by the learned) ship clean under dated attribution framing."},
        "confidence": "corroborated",
    },
    11: {  # Pisces
        "citation": 'Sārāvalī 22.66-67',
        "gist": "Sārāvalī (~10th c.) reads the Sun in Pisces as marking a friendly, sociable temperament with a strong acquisitive drive — inclined to accumulate wealth and to enjoy pleasure and companionship — together with cheerfulness and learning. It assigns the capacity to overcome many rivals and pronounced prosperity: the native is read as wealthy, endowed with a partner and good children, and — in the text's dated household terms — attended by servants. It ties material gain especially to commerce carried across sea and river (maritime/riverine trade). On character it assigns eloquent, persuasive speech coupled with a tendency to untruth. As the text's dated somatic note — its stated effect, not a prediction and not medical advice — Sārāvalī flags a susceptibility to ailments of the genital/private region. It also assigns many siblings (co-born).",
        "adaptation": {"classes": ['gender', 'offspring', 'slavery/servitude/rank', 'health', 'occupation/commerce'], "action": 'neutralise+historicise',
                        "note": "Multi-class entry; ships with the §5 historical-context badge. NEUTRALISE gender/marriage: 'fond of women' -> pleasure-/company-loving inclination (the native's sensual/sociable disposition survives as a structural principle; it is a judgement about the native, not a value-laden claim about a category of women, so neutralise is correct rather than refuse); 'endowed with wife' -> endowed with a partner. NEUTRALISE offspring: 'good sons' -> good children. HISTORICISE slavery/servitude/rank: 'servants' retained only as a dated marker of household prosperity, badged, not endorsed (§5 permits omit or historicise). DEATH/DISEASE: 'diseases of the private parts' KEPT as the text's dated, cited stated-effect, framed NOT as fate and NOT as medical advice; no death-timing present, so no refusal triggered. OCCUPATION/COMMERCE: 'wealth via sea/river transactions' kept as theme with no high/low status ranking to drop. CLEAN and kept plainly: friendly, tendency to amass, happy, learned, overcomes many enemies (violent 'destroy' softened to 'overcome', theme intact), wealthy/rich, eloquent-but-untruthful (character trait, not caste/gender), many co-born/siblings. No caste verdict, no remedy/ritual/gemstone, and no death-timing appear in this verse, so none required omission or refusal."},
        "confidence": "corroborated",
    },
}
