"""BPHS yoga catalogue — GENERATED, do not hand-edit.

Effect + citation + computability per detectable yoga, mined from BPHS Vol I chs
35-39 + Vol II ch.75 (Santhanam tr.), Notes EXCLUDED (numbered ślokas only,
verified clean of non-Parāśara commentary). tier = "sloka" (all BPHS). The
DETECTION conditions live in yogas.py as code; this holds the cited RESULT text.
strength_gated yogas: geometry is detected, the strength claim is refused.
"""

YOGAS = {
    "Rajju": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.7 (printed p.358), effect v.18 (p.360)",
        "effect": "One born in Rajju yoga will be fond of wandering, be charming, will earn in foreign countries, and be cruel and mischievous.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Musala": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.7 (printed p.358), effect v.19 (pp.360–361)",
        "effect": "One born in Musala yoga will be endowed with honour, wisdom, wealth etc., be dear to king, famous, will have many sons and be firm in disposition.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Nala": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.7 (printed p.358), effect v.20 (p.361)",
        "effect": "One born in Nala yoga will have uneven physique, be interested in accumulating money, very skilful, helpful to relatives, and charming.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Maala": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.8 (printed p.358), effect v.21 (p.361)",
        "effect": "One born in Maala yoga will be ever happy, endowed with conveyances, robes, food and pleasures, be splendorous and endowed with many females.",
        "computability": "clean", "strength_note": "Not Ṣaḍbala-gated. But requires the natural benefic/malefic assignment; Mercury's and the Moon's benefic status is context-dependent (association / waxing-waning) — an engine choice, not stated in the śloka.", "tier": "sloka"},
    "Sarpa": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.8 (printed pp.358–359), effect v.22 (p.361)",
        "effect": "One born in Sarpa (Bhujanga) yoga will be crooked, cruel, poor, miserable and will depend on others for food and drinks.",
        "computability": "clean", "strength_note": "Not Ṣaḍbala-gated. Requires natural benefic/malefic assignment (Moon waxing/waning, Mercury association) which the śloka does not spell out.", "tier": "sloka"},
    "Gada": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.9–11 (printed p.359), effect v.23 (p.361)",
        "effect": "One born in Gada yoga will always make efforts to earn wealth, will perform sacrificial rites, be skilful in Sastras and songs and endowed with wealth, gold and precious stones.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Sakata": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.9–11 (printed p.359), effect v.24 (pp.361–362)",
        "effect": "One born in Sakata yoga will be afflicted by diseases, will have diseased or ugly nails, be foolish, will live by pulling carts, be poor and devoid of friends and relatives.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Vihaga": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.9–11 (printed p.359), effect v.25 (p.362)",
        "effect": "One born in Vihaga yoga will be fond of roaming, be a messenger, will live by sexual dealings, be shameless and interested in quarrels.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Sringataka": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.9–11 (printed p.359), effect v.26 (p.362)",
        "effect": "One born in Sringataka yoga will be fond of quarrels and battles, be happy, dear to king, endowed with an auspicious wife, be rich and will hate women.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Hala": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.9–11 (printed p.359), effect v.27 (p.362)",
        "effect": "One born in Hala yoga will eat a lot, be very poor, be a farmer, be miserable, agitated, given up by friends and relatives and be a servant.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Vajra": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.9–11 (printed p.359), effect v.28 (p.362)",
        "effect": "One born in Vajra yoga will be happy in the beginning and at the end of life, be valorous, charming, devoid of desires and fortunes and be inimical.",
        "computability": "clean", "strength_note": "Not Ṣaḍbala-gated; requires natural benefic/malefic split (Moon phase, Mercury association) — an engine convention, not fixed by the śloka. Santhanam's 'or' is inclusive of both axis-conditions holding jointly (the classical reading).", "tier": "sloka"},
    "Yava": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.9–11 (printed p.359), effect v.29 (p.362)",
        "effect": "One born in Yava yoga will observe fasts and other religious rules, will do auspicious acts, will obtain happiness, wealth and sons in his mid-life, be charitable and firm.",
        "computability": "clean", "strength_note": "Not Ṣaḍbala-gated; requires natural benefic/malefic split, an engine convention not fixed by the śloka.", "tier": "sloka"},
    "Kamala": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.12 (printed p.359), effect v.30 (p.363)",
        "effect": "One born in Kamala yoga will be rich and virtuous, be long-lived, very famous, pure, will perform hundreds of auspicious acts and be a king.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Vapi": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.12 (printed p.359), effect v.31 (p.363)",
        "effect": "One born in Vapi yoga will be capable of accumulating wealth, be endowed with lasting wealth, and happiness and sons, be free from eye afflictions and be a king.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Yupa": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.13–14 (printed pp.359–360), effect v.32 (p.363)",
        "effect": "One born in Yupa yoga will have spiritual knowledge, be interested in sacrificial rites, endowed with a wife, be strong, interested in fasts and other religious observations and be distinguished.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Sara": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.13–14 (printed p.360), effect v.33 (p.363)",
        "effect": "One born in Sara yoga will make arrows, will be head of prison, will earn through animals, will eat meat and indulge in torture and mean handiworks.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Sakthi": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.13–14 (printed p.360), effect v.34 (p.363)",
        "effect": "One born in Sakthi yoga will be bereft of wealth, be unsuccessful, miserable, mean, lazy, long-lived, interested and skilful in war, firm and auspicious.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Danda": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.13–14 (printed p.360), effect v.35 (p.363)",
        "effect": "One born in Danda yoga will lose his sons and wife, be indigent, unkind, away from his men, miserable and will serve mean people.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Nauka": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.14 (printed p.360), effect v.36 (p.364)",
        "effect": "One born in Nauka yoga will derive his livelihood through water, be wealthy, famous, wicked, wretched, dirty and miserly.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Koota": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.14 (printed p.360), effect v.37 (p.364)",
        "effect": "One born in Koota yoga will be a liar, will head a jail, be poor, crafty, cruel and will live in hills and fortresses.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Chatra": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.14 (printed p.360), effect v.38 (p.364)",
        "effect": "One born in Chatra yoga will help his own men, be kind, dear to many kings, be very intelligent, be happy at the beginning and end of his life and be long-lived.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Chapa": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.14 (printed p.360), effect v.39 (p.364)",
        "effect": "One born in Chapa yoga will be a liar, will protect secrets, be a thief, be fond of wandering in forests, be devoid of luck and be happy in the middle of his life.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Chakra": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.15 (printed p.360), effect v.41 (p.364)",
        "effect": "One born in Chakra yoga will be an emperor at whose feet will be the prostrating kings' heads adoring gem-studded diadems.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Samudra": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def v.15 (printed p.360), effect v.42 (p.365)",
        "effect": "One born in Samudra yoga will have many precious stones and abundant wealth, will be endowed with pleasures, dear to people, will have firm wealth and be well-disposed.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Veena": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.16–17 (printed p.360), effect v.43 (p.365)",
        "effect": "One born in Veena yoga will be fond of songs, dance and musical instruments, be skilful, happy, wealthy and be a leader of men.",
        "computability": "clean", "strength_note": "The void-if-earlier-Nabhasa exclusion (v.17) requires the engine to first evaluate all Asraya/Dala/Akriti yogas and suppress this Sankhya yoga if any fires.", "tier": "sloka"},
    "Daama": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.16–17 (printed p.360), effect v.44 titled 'Daamini' (p.365)",
        "effect": "One born in Daamini yoga will be helpful to others, will have righteously earned wealth, be very affluent, famous, will have many sons and gems, be courageous and red-lettered.",
        "computability": "clean", "strength_note": "Void-if-earlier-Nabhasa exclusion applies (v.17).", "tier": "sloka"},
    "Paasa": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.16–17 (printed p.360), effect v.45 (p.365)",
        "effect": "One born in Pasa yoga will be liable to be imprisoned, be skilful in work, be deceiving in disposition, will talk much, be bereft of good qualities and will have many servants.",
        "computability": "clean", "strength_note": "Void-if-earlier-Nabhasa exclusion applies (v.17).", "tier": "sloka"},
    "Kedara": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.16–17 (printed p.360), effect v.46 (p.365)",
        "effect": "One born in Kedara yoga will be useful to many, be an agriculturist, be truthful, happy, fickle-minded and wealthy.",
        "computability": "clean", "strength_note": "Void-if-earlier-Nabhasa exclusion applies (v.17).", "tier": "sloka"},
    "Soola": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.16–17 (printed p.360), effect v.47 (pp.365–366)",
        "effect": "One born in Soola yoga will be sharp, indolent, bereft of wealth, be torturous, prohibited, valiant, and famous through war.",
        "computability": "clean", "strength_note": "Void-if-earlier-Nabhasa exclusion applies (v.17).", "tier": "sloka"},
    "Yuga": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.16–17 (printed p.360), effect v.48 (p.366)",
        "effect": "One born in Yuga yoga will be heretic, be devoid of wealth, be discarded by others, and be devoid of sons, mother and virtues.",
        "computability": "clean", "strength_note": "Void-if-earlier-Nabhasa exclusion applies (v.17).", "tier": "sloka"},
    "Gola": {"family": "nabhasa", "citation": "BPHS (Santhanam tr.) Vol I, Ch.35 — def vv.16–17 (printed p.360), effect v.49 (p.366)",
        "effect": "One born in Gola yoga will be strong, be devoid of wealth, learning and intelligence, be dirty, sorrowful and miserable.",
        "computability": "clean", "strength_note": "Void-if-earlier-Nabhasa exclusion applies (v.17).", "tier": "sloka"},
    "Ruchaka": {"family": "mahapurusha", "citation": "BPHS Vol II, Ch.75 (Characteristic Features of Panchamahapurushas), shared condition v.1-2; effect v.3-7 (printed p.924-925 / PDF p.434-435)",
        "effect": "3-7. The Ruchaka native possesses a long face, he is very enthusiastic, has spotless lustre, is powerful, has attractive brows, black hair and is fond of all things. He loves to fight wars, is of dark red complexion, is victorious over enemies, is discriminative, is protector of thieves and has cruel temperament and slender thighs. He is a devotee of Brahmins, has marks of veena, varga, dhanus, pasha and vrasha signs in his hands along with chakra rekha. He is well versed in occult sciences. He is 100 angulis in height, his waste [waist] has the circumference equal to the length of his face and is 1000 Karshas (karsh) in weight. He is ruler of Sahyachala and Vindhya Pradesh dies after attaining the age of 70 by fire or weapons.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Bhadra": {"family": "mahapurusha", "citation": "BPHS Vol II, Ch.75, shared condition v.1-2; effect v.8-12 (printed p.925-926 / PDF p.435-436)",
        "effect": "8-12. The Bhadra native is splendorous like a lion, has very developed chest (or chest with well developed muscles), has the gait of an elephant, has long and thick arms, is learned in all respects. He is well versed in yoga performance, is satwaguni and has beautiful feet, mostaches [moustaches] and head. He is fond of luxuries and comforts and has marks of sankha (conch), chakra, gada, arrow, elephant, dhwaja (flag) and hala (plough) in his hands and feet. He is well versed in Shastras, has black and curly hair, possesses independent nature, and is protector of his family. His friends share in the enjoyment of his wealth. He is 20 tulas (one bhara) in weight. He lives happily with his wife and children and as ruler of Madhya Desha lives for one hundred years.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Hamsa": {"family": "mahapurusha", "citation": "BPHS Vol II, Ch.75, shared condition v.1-2; effect v.13-16 (printed p.926 / PDF p.436)",
        "effect": "13-16. The Hamsa native has voice like a hamsa (swan), has a handsome appearance and well developed nose. He is a king with phlegmatic temperament, honey like tawny coloured eyes, red coloured nails, sharp intelligence, sturdy cheeks, round forehead and beautiful feet. He has marks of matsya (fish), ankush (the iron hook with which elephants are driven), dhanus (bow), sankh (conch) and kamal (lotus) in his hands and feet. He is very passionate and his lust remains unfulfilled. He is 96 angulis in height. He is fond of swimming and playing games in watery places. He enjoys life fully and as ruler of a land situated between the Ganga and Yamuna 'dies after attaining the age of 100 years.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Malavya": {"family": "mahapurusha", "citation": "BPHS Vol II, Ch.75, shared condition v.1-2; effect v.17-19 (printed p.926-927 / PDF p.436-437)",
        "effect": "17-19. The Malavya native has beautiful lips and a slender waist. He is lustrous like the Moon and has fragrance in his body. He is of ordinary red complexion, has a medium stature and clean and beautiful teeth. His voice is like that of an elephant and his arms are long enough to reach upto his knees. His face is thirteen angulis in length and ten angulis in breadth. He lives happily for seventy years as ruler of Sindhu and Malwa and then leaves for his heavenly abode.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Sasa": {"family": "mahapurusha", "citation": "BPHS Vol II, Ch.75, shared condition v.1-2; effect v.20-22 (printed p.927 / PDF p.437)",
        "effect": "20-22. The Sasa native has small sized teeth and face but his body is not small. He is valorous. He has a slender waist and beautiful thighs. He is wise and enjoys wandering in forests and mountains. He is well versed in the loopholes (weaknesses) of the enemy. He is lively, virile and fond of women. He usurps other people's wealth. He has marks of mala (garland), veena, mridanga (musical instrument) and weapons in his hands and feet. He rules happily over several parts of the earth and then leaves for his heavenly abode at the age of 70.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Moon's house-class from the Sun (wealth/intelligence/skill)": {"family": "lunar", "citation": "BPHS Ch.37, sloka 1 (Santhanam Vol I, printed p.384 / PDF 383)",
        "effect": "one's wealth, intelligence and skill will be respectively little, meddling and excellent. (Angle -> little wealth; Panaphara -> meddling/moderate intelligence; Apoklima -> excellent skill.)",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Lunar Navamsa-aspect wealth yoga (day/night, Jupiter/Venus)": {"family": "lunar", "citation": "BPHS Ch.37, slokas 2-4 (Santhanam Vol I, printed p.384 / PDF 383)",
        "effect": "one will be endowed with wealth and happiness (positive branches); in a contrary situation the aspect of Jupiter or of Venus on the Moon will make one go with little wealth or even without that.",
        "computability": "clean", "strength_note": "No Sadbala/rupa gating in the sloka; 'friendly Navamsa' is planetary-friendship-based and computable, so left clean.", "tier": "sloka"},
    "Adhi Yoga from the Moon": {"family": "lunar", "citation": "BPHS Ch.37, sloka 5 (Santhanam Vol I, printed p.385 / PDF 384)",
        "effect": "According to the strength of the participating planets, the native concerned will be either a king or a minister or an army chief.",
        "computability": "strength_gated", "strength_note": "The king / minister / army-chief tier is explicitly assigned 'according to the strength of the participating planets' (balakramat). Engine can detect the geometry (benefics in 6/7/8 from Moon) but must refuse to assign the specific tier, which depends on planetary strength (rupas/Sadbala).", "tier": "sloka"},
    "Dhana Yoga from the Moon (benefics in Upachaya)": {"family": "lunar", "citation": "BPHS Ch.37, sloka 6 (Santhanam Vol I, printed p.385 / PDF 384)",
        "effect": "all three benefics in Upachaya from Moon -> one will be very affluent; two benefics -> medium effects in regard to wealth; a single benefic -> the wealth will be negligible.",
        "computability": "clean", "strength_note": "Gradation is by COUNT of benefics, not by rupa-strength, so left clean.", "tier": "sloka"},
    "Sunapha Yoga": {"family": "lunar", "citation": "BPHS Ch.37, slokas 7-10 (Santhanam Vol I, printed p.385 / PDF 384)",
        "effect": "One with Sunapha yoga will be a king or equal to a king endowed with intelligence, wealth, fame and self earned wealth.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Anapha Yoga": {"family": "lunar", "citation": "BPHS Ch.37, slokas 7-10 (Santhanam Vol I, printed p.385 / PDF 384)",
        "effect": "One born in Anapha yoga will be a king, free from diseases, virtuous, famous, charming and happy.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Duradhara (Duradhura) Yoga": {"family": "lunar", "citation": "BPHS Ch.37, slokas 7-10 (Santhanam Vol I, printed p.385 / PDF 384)",
        "effect": "One born in Duradhara yoga will enjoy pleasures, be charitable and endowed with wealth, conveyances and excellent serving force.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Kemadruma Yoga": {"family": "lunar", "citation": "BPHS Ch.37, slokas 11-13 (Santhanam Vol I, printed p.386 / PDF 385)",
        "effect": "One born in Kemadruma yoga will be very much reproached, be bereft of intelligence and learning and reduced to penury and perils.",
        "computability": "clean", "strength_note": "The kendra-from-ascendant cancellation clause (d) is stated in this Santhanam translation as part of the sloka body (not a Notes import); implement it as a defined breaker of the yoga.", "tier": "sloka"},
    "Vesi Yoga": {"family": "solar", "citation": "BPHS Ch.38, sloka 1 & 2-3 (Santhanam Vol I, printed p.386-387 / PDF 385-386)",
        "effect": "One born in Vesi yoga will be even sighted, truthful, long-bodied, indolent, happy and endowed with negligible wealth.",
        "computability": "clean", "strength_note": "Sloka 4: benefics causing the yoga give the stated effects; malefics produce contrary effects. So the sign of each effect clause flips by the benefic/malefic nature of the planet(s) forming the yoga — a defined (non-strength) modifier.", "tier": "sloka"},
    "Vasi (Vosi) Yoga": {"family": "solar", "citation": "BPHS Ch.38, sloka 1 & 2-3 (Santhanam Vol I, printed p.386-387 / PDF 385-386)",
        "effect": "One born with Vosi yoga will be skilful, charitable and endowed with fame, learning and strength.",
        "computability": "clean", "strength_note": "Sloka 4 benefic/malefic polarity modifier applies (benefic -> stated effects, malefic -> contrary).", "tier": "sloka"},
    "Ubhayachari Yoga": {"family": "solar", "citation": "BPHS Ch.38, sloka 1 & 2-3 (Santhanam Vol I, printed p.386-387 / PDF 385-386)",
        "effect": "The Ubhayachari native will be a king or equal to a king and be happy.",
        "computability": "clean", "strength_note": "Sloka 4 benefic/malefic polarity modifier applies (benefic -> stated effects, malefic -> contrary).", "tier": "sloka"},
    "Subha Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.1-2 (printed pp.366-367)",
        "effect": "One born in Subha yoga will be eloquent, charming and virtuous.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Asubha Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.1-2 (printed pp.366-367)",
        "effect": "...his counterpart will be sensuous, will do sinful acts and will enjoy (or swallow) others' wealth.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Gajakesari Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.3-4 (printed p.368)",
        "effect": "One born in Gaja Kesari yoga will be splendorous, wealthy, intelligent endowed with many laudable virtues and will please the king.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Amala Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.5-6 (printed p.370)",
        "effect": "Amala yoga will confer fame lasting till the moon and stars exist and will make the native honoured by the king, enjoy abundant pleasures, be charitable, fond of relatives, helpful to others, pious and virtuous.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Parvata Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.7-8 (printed pp.371-372)",
        "effect": "One born in Parvatha yoga will be wealthy, eloquent, charitable, learned in Sastras, fond of mirth, famous, splendorous and be the leader of a city.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Kahala Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.9-10 (printed p.373)",
        "effect": "In effect, the native will be energetic, adeventurous, cunning, endowed with a complete army consisting of chariots, elephants, horses and infantry and will lord over a few villages.",
        "computability": "strength_gated", "strength_note": "Primary clause requires 'the ascendant lord is strong' (Sadbala/rupas). Engine can detect 4th-lord/Jupiter mutual angularity and the alternative parivartana-free clause, but must refuse the strength claim. The alternative clause (4th-lord own/exalt + conjunct 10th-lord) is fully computable from D1.", "tier": "sloka"},
    "Chamara Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.11-12 (printed p.374)",
        "effect": "The effects of Chamara Yoga are: the native will be a king or honoured by the king, long-lived, scholarly, eloquent and versed in all arts.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Sankha Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.13-14 (printed pp.374-375)",
        "effect": "One born with Sankha yoga will be endowed with wealth, spouse and sons, be kindly disposed, propitious, intelligent, meritorious and long-lived.",
        "computability": "strength_gated", "strength_note": "Both clauses gate on 'ascendant lord is strong' / '9th lord is strong' (Sadbala). Engine detects the 5th-6th-lord mutual angularity and the asc-lord+10th-lord-in-movable-sign geometry, but must refuse the strength claim.", "tier": "sloka"},
    "Bheri Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.15-16 (printed p.375)",
        "effect": "The results of Bheri yoga are the native will be endowed with wealth, wife and sons, be a king, be famous, virtuous and endowed with good behaviour, happiness and pleasures.",
        "computability": "strength_gated", "strength_note": "Both clauses gate on '9th lord is strong' (Sadbala). 'Occupied' in the primary clause is unspecified as to which planets. Engine detects the house-occupancy and Venus/Jupiter/asc-lord-in-kendra geometry, but must refuse the strength claim.", "tier": "sloka"},
    "Mridanga Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.17 (printed p.375)",
        "effect": "The native concerned will be a king or equal to a king and be happy.",
        "computability": "strength_gated", "strength_note": "Gates on 'ascendant lord is strong' (Sadbala). Also under-specified: the sloka does not say which planets or how many must occupy the good positions. Engine can flag the dignity placements but must refuse the strength claim and cannot pin an exact predicate count.", "tier": "sloka"},
    "Srinatha Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.18 (printed p.375)",
        "effect": "The native with this yoga will be equal to lord Devendra (the god of gods).",
        "computability": "clean", "strength_note": "FLAG: the task grouped Srinatha with the strength-gated yogas, but the numbered sloka contains NO Sadbala/'is strong' term — its only 'strength' element is the 10th-lord's exaltation, which is a D1 dignity. Marked clean per CITE-OR-REFUSE. If the engine is to honour the task's blanket strength-gate label, override here; otherwise it is fully computable.", "tier": "sloka"},
    "Matsya Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.21-22 (printed p.376)",
        "effect": "In effect, the native will be an astrologer, be a synonym of kindness, be virtuous, strong, beautiful, famous, learned and pious.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Koorma Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.23-24 (printed pp.376-377)",
        "effect": "The results of Koorma yoga are: the native will be a king, be courageous, virtuous, famous, helpful, happy and be leader of men.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Khadga Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.25-26 (printed p.377)",
        "effect": "One with Khadga yoga will be endowed with wealth, fortunes and happiness, be learned in sastras, be intelligent, mighty, grateful and skilful.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Kusuma Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.29-30 (printed p.378)",
        "effect": "Such a native will be a king or equal to him, be charitable, will enjoy pleasures, be happy, prime among his race men, virtuous and red-lettered.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Kalanidhi Yoga": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.31-32 (printed p.378)",
        "effect": "In effect, the native will be virtuous, honoured by the kings, bereft of diseases, be happy, wealthy and learned.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Kalpadruma Yoga (a.k.a. Parijata Yoga)": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.33-34 (printed pp.378-380)",
        "effect": "One with this yoga will be endowed with all kinds of wealth, be a king, pious, strong, fond of war and merciful.",
        "computability": "clean", "strength_note": "Uses D9 for the fourth chain member (Navamsa dispositor). D9 is within the permitted D1/D9 scope, so marked clean rather than partial; note the D9 dependence for implementation.", "tier": "sloka"},
    "Hari Yoga (Trimurthi)": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.35-36 (printed pp.380-382)",
        "effect": "One born in anyone of the said three yogas [Hari/Hara/Brahma] will be happy, learned and endowed with wealth and sons.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Hara Yoga (Trimurthi)": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.35-36 (printed pp.380-382)",
        "effect": "One born in anyone of the said three yogas [Hari/Hara/Brahma] will be happy, learned and endowed with wealth and sons.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Brahma Yoga (Trimurthi)": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.35-36 (printed pp.380-382)",
        "effect": "One born in anyone of the said three yogas [Hari/Hara/Brahma] will be happy, learned and endowed with wealth and sons.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Lagnadhi Yoga (Adhi Yoga from lagna)": {"family": "other", "citation": "BPHS (Santhanam) Vol I, Ch.36, v.37 (printed p.383)",
        "effect": "...Lagnadhi yoga is produced making one a great person, learned in Sastras and happy.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Mahā Rāja Yoga (lagna-lord ↔ 5th-lord exchange)": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.6–7, printed p.389",
        "effect": "Maha Raja yoga is produced. The native so born will be famous and happy.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Benefics in 1st/2nd/4th, malefic in 3rd": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.17, printed p.392",
        "effect": "one will become a king or equal to a king.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Luminary/benefic exalted in 2nd (wealth)": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.18, printed p.392",
        "effect": "The native will be wealthy.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Dusthana debilitation + exalted lagna-lord aspecting lagna": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.19, printed p.392",
        "effect": "there is a Raja yoga.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Weak 6/8/12 lords + exalted-or-own lagna-lord aspecting lagna": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.20, printed p.393",
        "effect": "a Raja yoga is formed.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "10th-lord (own/exalted) aspecting lagna; benefics in kendras": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.21, printed p.393",
        "effect": "a Raja yoga is formed. Similar is the case if benefics are in angles.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "5th-lord – 9th-lord association (minister yoga)": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.33–34, printed p.395",
        "effect": "the native will obtain a kingdom ... one born of royal scion will become a king.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "4th–10th exchange aspecting 5th & 9th lords": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.35, printed p.395",
        "effect": "The native will attain kingdom.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "5th/10th/4th/lagna lords conjoined in the 9th": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.36, printed p.395",
        "effect": "one will become a ruler with fame spreading over the four directions.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Kendra-lord + trikona-lord conjunction (4th/10th with 5th/9th)": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.37, printed p.395",
        "effect": "the native will obtain kingdom.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "5th-lord in kendra with 9th-lord or lagna-lord": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.38, printed p.396",
        "effect": "the native will become a king.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Jupiter in own 9th with Venus or 5th-lord": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.39, printed p.396",
        "effect": "the native will obtain kinghood.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Moon–Venus mutual 3rd/11th or mutual aspect": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.41, printed p.397",
        "effect": "a Raja yoga is obtained.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Strong Vargottama Moon aspected by 4+ planets": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.42, printed p.398",
        "effect": "the native will become a king.",
        "computability": "strength_gated", "strength_note": "Gated on 'the Moon endowed with strength' (bala). Engine can verify vargottama (D9 available) and the 4+ aspect count but must refuse the strength claim (implies Ṣaḍbala/Chandra-bala not modelled).", "tier": "sloka"},
    "Ascendant in Uttamāmśa aspected by 4+ (non-Moon)": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.43, printed p.398",
        "effect": "One will become a king.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "1–3 planets in exaltation": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.44, printed p.398",
        "effect": "one of a royal scion will become a king while another will be equal to a king or be wealthy.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "4 or 5 planets in exaltation or Moolatrikona": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.45, printed p.398",
        "effect": "even a person of base-birth will become a king.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "6 planets exalted (emperor)": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.46, printed p.398",
        "effect": "the native will become an emperor and will enjoy various kinds of royal paraphernalia.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "Jup/Ven/Mer exalted + a benefic in a kendra": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.47, printed p.398–399",
        "effect": "the native will become a king or be equal to him.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
    "All benefics in kendras, malefics in 3/6/11": {"family": "raja", "citation": "BPHS Vol I (Santhanam), Ch.39, v.48, printed p.399",
        "effect": "the native, though may be of mean descent will ascend, the throne.",
        "computability": "clean", "strength_note": "", "tier": "sloka"},
}